// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: schemapb/service.proto

package schemapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// How list (repeated) values merge in Merge.
type ListMerge int32

const (
	// Concatenate base + override lists (proto.Merge default).
	ListMerge_LIST_MERGE_APPEND ListMerge = 0
	// Override list replaces the base list wholesale.
	ListMerge_LIST_MERGE_REPLACE ListMerge = 1
)

// Enum value maps for ListMerge.
var (
	ListMerge_name = map[int32]string{
		0: "LIST_MERGE_APPEND",
		1: "LIST_MERGE_REPLACE",
	}
	ListMerge_value = map[string]int32{
		"LIST_MERGE_APPEND":  0,
		"LIST_MERGE_REPLACE": 1,
	}
)

func (x ListMerge) Enum() *ListMerge {
	p := new(ListMerge)
	*p = x
	return p
}

func (x ListMerge) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ListMerge) Descriptor() protoreflect.EnumDescriptor {
	return file_schemapb_service_proto_enumTypes[0].Descriptor()
}

func (ListMerge) Type() protoreflect.EnumType {
	return &file_schemapb_service_proto_enumTypes[0]
}

func (x ListMerge) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ListMerge.Descriptor instead.
func (ListMerge) EnumDescriptor() ([]byte, []int) {
	return file_schemapb_service_proto_rawDescGZIP(), []int{0}
}

// Filter narrows ListSchemas. Unset fields are not constrained; all set fields
// must match (AND). An empty Filter lists everything.
type Filter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Exact namespace match.
	Namespace *string `protobuf:"bytes,1,opt,name=namespace,proto3,oneof" json:"namespace,omitempty"`
	// Exact name match.
	Name *string `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// Exact version match.
	Version *string `protobuf:"bytes,3,opt,name=version,proto3,oneof" json:"version,omitempty"`
	// Case-insensitive substring match against the name.
	NameContains  *string `protobuf:"bytes,4,opt,name=name_contains,json=nameContains,proto3,oneof" json:"name_contains,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_schemapb_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_schemapb_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_schemapb_service_proto_rawDescGZIP(), []int{0}
}

func (x *Filter) GetNamespace() string {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return ""
}

func (x *Filter) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Filter) GetVersion() string {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return ""
}

func (x *Filter) GetNameContains() string {
	if x != nil && x.NameContains != nil {
		return *x.NameContains
	}
	return ""
}

// SchemaSummary is the lightweight listing entry; fetch the full Schema with GetSchema.
type SchemaSummary struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Schema identity.
	Id *SchemaIdentity `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Schema description, if any.
	Description   *string `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemaSummary) Reset() {
	*x = SchemaSummary{}
	mi := &file_schemapb_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaSummary) ProtoMessage() {}

func (x *SchemaSummary) ProtoReflect() protoreflect.Message {
	mi := &file_schemapb_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaSummary.ProtoReflect.Descriptor instead.
func (*SchemaSummary) Descriptor() ([]byte, []int) {
	return file_schemapb_service_proto_rawDescGZIP(), []int{1}
}

func (x *SchemaSummary) GetId() *SchemaIdentity {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *SchemaSummary) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type RegisterSchemaResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identity the schema is stored under (its own id).
	Id *SchemaIdentity `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// True if the schema is well-formed and was stored.
	Valid bool `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	// Descriptor problems; non-empty means the schema was rejected.
	Errors        []*FieldError `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterSchemaResponse) Reset() {
	*x = RegisterSchemaResponse{}
	mi := &file_schemapb_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterSchemaResponse) ProtoMessage() {}

func (x *RegisterSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schemapb_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterSchemaResponse.ProtoReflect.Descriptor instead.
func (*RegisterSchemaResponse) Descriptor() ([]byte, []int) {
	return file_schemapb_service_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterSchemaResponse) GetId() *SchemaIdentity {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *RegisterSchemaResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *RegisterSchemaResponse) GetErrors() []*FieldError {
	if x != nil {
		return x.Errors
	}
	return nil
}

type ListSchemasResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Matching schemas (summaries).
	Schemas       []*SchemaSummary `protobuf:"bytes,1,rep,name=schemas,proto3" json:"schemas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSchemasResponse) Reset() {
	*x = ListSchemasResponse{}
	mi := &file_schemapb_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSchemasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSchemasResponse) ProtoMessage() {}

func (x *ListSchemasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schemapb_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSchemasResponse.ProtoReflect.Descriptor instead.
func (*ListSchemasResponse) Descriptor() ([]byte, []int) {
	return file_schemapb_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListSchemasResponse) GetSchemas() []*SchemaSummary {
	if x != nil {
		return x.Schemas
	}
	return nil
}

type ValidateSchemaResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True if the descriptor is well-formed.
	Valid bool `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	// Descriptor problems.
	Errors        []*FieldError `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateSchemaResponse) Reset() {
	*x = ValidateSchemaResponse{}
	mi := &file_schemapb_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateSchemaResponse) ProtoMessage() {}

func (x *ValidateSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schemapb_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateSchemaResponse.ProtoReflect.Descriptor instead.
func (*ValidateSchemaResponse) Descriptor() ([]byte, []int) {
	return file_schemapb_service_proto_rawDescGZIP(), []int{4}
}

func (x *ValidateSchemaResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateSchemaResponse) GetErrors() []*FieldError {
	if x != nil {
		return x.Errors
	}
	return nil
}

type ValidateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True if there are no ERROR-severity failures.
	Valid bool `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	// Validation failures (errors and warnings).
	Errors        []*FieldError `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateResponse) Reset() {
	*x = ValidateResponse{}
	mi := &file_schemapb_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateResponse) ProtoMessage() {}

func (x *ValidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schemapb_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateResponse.ProtoReflect.Descriptor instead.
func (*ValidateResponse) Descriptor() ([]byte, []int) {
	return file_schemapb_service_proto_rawDescGZIP(), []int{5}
}

func (x *ValidateResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateResponse) GetErrors() []*FieldError {
	if x != nil {
		return x.Errors
	}
	return nil
}

type MergeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The sealed base to layer onto (carries its own schema).
	Base *Baked `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	// Partial values to merge over base.values.
	Overrides *structpb.Struct `protobuf:"bytes,2,opt,name=overrides,proto3" json:"overrides,omitempty"`
	// How list values combine.
	Lists         ListMerge `protobuf:"varint,3,opt,name=lists,proto3,enum=schemapb.ListMerge" json:"lists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MergeRequest) Reset() {
	*x = MergeRequest{}
	mi := &file_schemapb_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MergeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeRequest) ProtoMessage() {}

func (x *MergeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schemapb_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeRequest.ProtoReflect.Descriptor instead.
func (*MergeRequest) Descriptor() ([]byte, []int) {
	return file_schemapb_service_proto_rawDescGZIP(), []int{6}
}

func (x *MergeRequest) GetBase() *Baked {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *MergeRequest) GetOverrides() *structpb.Struct {
	if x != nil {
		return x.Overrides
	}
	return nil
}

func (x *MergeRequest) GetLists() ListMerge {
	if x != nil {
		return x.Lists
	}
	return ListMerge_LIST_MERGE_APPEND
}

// BakeResponse is the result of Bake or Merge: a sealed Baked, or the errors
// that prevented sealing.
type BakeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Set only if validation passed.
	Baked *Baked `protobuf:"bytes,1,opt,name=baked,proto3" json:"baked,omitempty"`
	// Non-empty means the values were rejected; baked is unset.
	Errors        []*FieldError `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BakeResponse) Reset() {
	*x = BakeResponse{}
	mi := &file_schemapb_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BakeResponse) ProtoMessage() {}

func (x *BakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schemapb_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BakeResponse.ProtoReflect.Descriptor instead.
func (*BakeResponse) Descriptor() ([]byte, []int) {
	return file_schemapb_service_proto_rawDescGZIP(), []int{7}
}

func (x *BakeResponse) GetBaked() *Baked {
	if x != nil {
		return x.Baked
	}
	return nil
}

func (x *BakeResponse) GetErrors() []*FieldError {
	if x != nil {
		return x.Errors
	}
	return nil
}

type ComputeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The fully resolved form: the provided inputs, plus values filled from the
	// schema's defaults, plus the evaluated Computed (derived) fields.
	Values *structpb.Struct `protobuf:"bytes,1,opt,name=values,proto3" json:"values,omitempty"`
	// Errors raised while evaluating expressions.
	Errors        []*FieldError `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComputeResponse) Reset() {
	*x = ComputeResponse{}
	mi := &file_schemapb_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeResponse) ProtoMessage() {}

func (x *ComputeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schemapb_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputeResponse.ProtoReflect.Descriptor instead.
func (*ComputeResponse) Descriptor() ([]byte, []int) {
	return file_schemapb_service_proto_rawDescGZIP(), []int{8}
}

func (x *ComputeResponse) GetValues() *structpb.Struct {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *ComputeResponse) GetErrors() []*FieldError {
	if x != nil {
		return x.Errors
	}
	return nil
}

var File_schemapb_service_proto protoreflect.FileDescriptor

const file_schemapb_service_proto_rawDesc = "" +
	"\n" +
	"\x16schemapb/service.proto\x12\bschemapb\x1a\x1cgoogle/protobuf/struct.proto\x1a\x15schemapb/schema.proto\"\xc2\x01\n" +
	"\x06Filter\x12!\n" +
	"\tnamespace\x18\x01 \x01(\tH\x00R\tnamespace\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x01R\x04name\x88\x01\x01\x12\x1d\n" +
	"\aversion\x18\x03 \x01(\tH\x02R\aversion\x88\x01\x01\x12(\n" +
	"\rname_contains\x18\x04 \x01(\tH\x03R\fnameContains\x88\x01\x01B\f\n" +
	"\n" +
	"_namespaceB\a\n" +
	"\x05_nameB\n" +
	"\n" +
	"\b_versionB\x10\n" +
	"\x0e_name_contains\"p\n" +
	"\rSchemaSummary\x12(\n" +
	"\x02id\x18\x01 \x01(\v2\x18.schemapb.SchemaIdentityR\x02id\x12%\n" +
	"\vdescription\x18\x02 \x01(\tH\x00R\vdescription\x88\x01\x01B\x0e\n" +
	"\f_description\"\x86\x01\n" +
	"\x16RegisterSchemaResponse\x12(\n" +
	"\x02id\x18\x01 \x01(\v2\x18.schemapb.SchemaIdentityR\x02id\x12\x14\n" +
	"\x05valid\x18\x02 \x01(\bR\x05valid\x12,\n" +
	"\x06errors\x18\x03 \x03(\v2\x14.schemapb.FieldErrorR\x06errors\"H\n" +
	"\x13ListSchemasResponse\x121\n" +
	"\aschemas\x18\x01 \x03(\v2\x17.schemapb.SchemaSummaryR\aschemas\"\\\n" +
	"\x16ValidateSchemaResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12,\n" +
	"\x06errors\x18\x02 \x03(\v2\x14.schemapb.FieldErrorR\x06errors\"V\n" +
	"\x10ValidateResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12,\n" +
	"\x06errors\x18\x02 \x03(\v2\x14.schemapb.FieldErrorR\x06errors\"\x95\x01\n" +
	"\fMergeRequest\x12#\n" +
	"\x04base\x18\x01 \x01(\v2\x0f.schemapb.BakedR\x04base\x125\n" +
	"\toverrides\x18\x02 \x01(\v2\x17.google.protobuf.StructR\toverrides\x12)\n" +
	"\x05lists\x18\x03 \x01(\x0e2\x13.schemapb.ListMergeR\x05lists\"c\n" +
	"\fBakeResponse\x12%\n" +
	"\x05baked\x18\x01 \x01(\v2\x0f.schemapb.BakedR\x05baked\x12,\n" +
	"\x06errors\x18\x02 \x03(\v2\x14.schemapb.FieldErrorR\x06errors\"p\n" +
	"\x0fComputeResponse\x12/\n" +
	"\x06values\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x06values\x12,\n" +
	"\x06errors\x18\x02 \x03(\v2\x14.schemapb.FieldErrorR\x06errors*:\n" +
	"\tListMerge\x12\x15\n" +
	"\x11LIST_MERGE_APPEND\x10\x00\x12\x16\n" +
	"\x12LIST_MERGE_REPLACE\x10\x012\xf1\x03\n" +
	"\rSchemaService\x12D\n" +
	"\x0eRegisterSchema\x12\x10.schemapb.Schema\x1a .schemapb.RegisterSchemaResponse\x127\n" +
	"\tGetSchema\x12\x18.schemapb.SchemaIdentity\x1a\x10.schemapb.Schema\x12>\n" +
	"\vListSchemas\x12\x10.schemapb.Filter\x1a\x1d.schemapb.ListSchemasResponse\x12D\n" +
	"\x0eValidateSchema\x12\x10.schemapb.Schema\x1a .schemapb.ValidateSchemaResponse\x128\n" +
	"\bValidate\x12\x10.schemapb.Filled\x1a\x1a.schemapb.ValidateResponse\x126\n" +
	"\aCompute\x12\x10.schemapb.Filled\x1a\x19.schemapb.ComputeResponse\x120\n" +
	"\x04Bake\x12\x10.schemapb.Filled\x1a\x16.schemapb.BakeResponse\x127\n" +
	"\x05Merge\x12\x16.schemapb.MergeRequest\x1a\x16.schemapb.BakeResponseB)Z'github.com/stroppy-io/schemapb/schemapbb\x06proto3"

var (
	file_schemapb_service_proto_rawDescOnce sync.Once
	file_schemapb_service_proto_rawDescData []byte
)

func file_schemapb_service_proto_rawDescGZIP() []byte {
	file_schemapb_service_proto_rawDescOnce.Do(func() {
		file_schemapb_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_schemapb_service_proto_rawDesc), len(file_schemapb_service_proto_rawDesc)))
	})
	return file_schemapb_service_proto_rawDescData
}

var file_schemapb_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_schemapb_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_schemapb_service_proto_goTypes = []any{
	(ListMerge)(0),                 // 0: schemapb.ListMerge
	(*Filter)(nil),                 // 1: schemapb.Filter
	(*SchemaSummary)(nil),          // 2: schemapb.SchemaSummary
	(*RegisterSchemaResponse)(nil), // 3: schemapb.RegisterSchemaResponse
	(*ListSchemasResponse)(nil),    // 4: schemapb.ListSchemasResponse
	(*ValidateSchemaResponse)(nil), // 5: schemapb.ValidateSchemaResponse
	(*ValidateResponse)(nil),       // 6: schemapb.ValidateResponse
	(*MergeRequest)(nil),           // 7: schemapb.MergeRequest
	(*BakeResponse)(nil),           // 8: schemapb.BakeResponse
	(*ComputeResponse)(nil),        // 9: schemapb.ComputeResponse
	(*SchemaIdentity)(nil),         // 10: schemapb.SchemaIdentity
	(*FieldError)(nil),             // 11: schemapb.FieldError
	(*Baked)(nil),                  // 12: schemapb.Baked
	(*structpb.Struct)(nil),        // 13: google.protobuf.Struct
	(*Schema)(nil),                 // 14: schemapb.Schema
	(*Filled)(nil),                 // 15: schemapb.Filled
}
var file_schemapb_service_proto_depIdxs = []int32{
	10, // 0: schemapb.SchemaSummary.id:type_name -> schemapb.SchemaIdentity
	10, // 1: schemapb.RegisterSchemaResponse.id:type_name -> schemapb.SchemaIdentity
	11, // 2: schemapb.RegisterSchemaResponse.errors:type_name -> schemapb.FieldError
	2,  // 3: schemapb.ListSchemasResponse.schemas:type_name -> schemapb.SchemaSummary
	11, // 4: schemapb.ValidateSchemaResponse.errors:type_name -> schemapb.FieldError
	11, // 5: schemapb.ValidateResponse.errors:type_name -> schemapb.FieldError
	12, // 6: schemapb.MergeRequest.base:type_name -> schemapb.Baked
	13, // 7: schemapb.MergeRequest.overrides:type_name -> google.protobuf.Struct
	0,  // 8: schemapb.MergeRequest.lists:type_name -> schemapb.ListMerge
	12, // 9: schemapb.BakeResponse.baked:type_name -> schemapb.Baked
	11, // 10: schemapb.BakeResponse.errors:type_name -> schemapb.FieldError
	13, // 11: schemapb.ComputeResponse.values:type_name -> google.protobuf.Struct
	11, // 12: schemapb.ComputeResponse.errors:type_name -> schemapb.FieldError
	14, // 13: schemapb.SchemaService.RegisterSchema:input_type -> schemapb.Schema
	10, // 14: schemapb.SchemaService.GetSchema:input_type -> schemapb.SchemaIdentity
	1,  // 15: schemapb.SchemaService.ListSchemas:input_type -> schemapb.Filter
	14, // 16: schemapb.SchemaService.ValidateSchema:input_type -> schemapb.Schema
	15, // 17: schemapb.SchemaService.Validate:input_type -> schemapb.Filled
	15, // 18: schemapb.SchemaService.Compute:input_type -> schemapb.Filled
	15, // 19: schemapb.SchemaService.Bake:input_type -> schemapb.Filled
	7,  // 20: schemapb.SchemaService.Merge:input_type -> schemapb.MergeRequest
	3,  // 21: schemapb.SchemaService.RegisterSchema:output_type -> schemapb.RegisterSchemaResponse
	14, // 22: schemapb.SchemaService.GetSchema:output_type -> schemapb.Schema
	4,  // 23: schemapb.SchemaService.ListSchemas:output_type -> schemapb.ListSchemasResponse
	5,  // 24: schemapb.SchemaService.ValidateSchema:output_type -> schemapb.ValidateSchemaResponse
	6,  // 25: schemapb.SchemaService.Validate:output_type -> schemapb.ValidateResponse
	9,  // 26: schemapb.SchemaService.Compute:output_type -> schemapb.ComputeResponse
	8,  // 27: schemapb.SchemaService.Bake:output_type -> schemapb.BakeResponse
	8,  // 28: schemapb.SchemaService.Merge:output_type -> schemapb.BakeResponse
	21, // [21:29] is the sub-list for method output_type
	13, // [13:21] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_schemapb_service_proto_init() }
func file_schemapb_service_proto_init() {
	if File_schemapb_service_proto != nil {
		return
	}
	file_schemapb_schema_proto_init()
	file_schemapb_service_proto_msgTypes[0].OneofWrappers = []any{}
	file_schemapb_service_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_schemapb_service_proto_rawDesc), len(file_schemapb_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_schemapb_service_proto_goTypes,
		DependencyIndexes: file_schemapb_service_proto_depIdxs,
		EnumInfos:         file_schemapb_service_proto_enumTypes,
		MessageInfos:      file_schemapb_service_proto_msgTypes,
	}.Build()
	File_schemapb_service_proto = out.File
	file_schemapb_service_proto_goTypes = nil
	file_schemapb_service_proto_depIdxs = nil
}
