// Package emit renders a model.File into gofmt'd Go source.
package emit

import (
	"bytes"
	"fmt"
	"go/format"

	"github.com/stroppy-io/schemapb/cmd/schemapbgen/internal/model"
)

// Emit renders the file and runs it through gofmt.
func Emit(f *model.File) ([]byte, error) {
	var b bytes.Buffer
	writeHeader(&b, f)
	writeStructs(&b, f)
	writeEnums(&b, f)
	// sugar/roundtrip/schemawrap appended by later tasks:
	writeSchemaWrap(&b, f)
	writeRoundtrip(&b, f)
	writeSugar(&b, f)
	writeCustomJSON(&b, f)

	src, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("gofmt failed: %w\n--- raw ---\n%s", err, b.String())
	}
	return src, nil
}

func writeHeader(b *bytes.Buffer, f *model.File) {
	fmt.Fprintf(b, "// Code generated by schemapbgen. DO NOT EDIT.\n\n")
	fmt.Fprintf(b, "package %s\n\n", f.Package)
	fmt.Fprintf(b, "import (\n\t\"encoding/json\"\n\t\"fmt\"\n\t\"sync\"\n\t\"time\"\n\n")
	fmt.Fprintf(b, "\t\"google.golang.org/protobuf/proto\"\n")
	fmt.Fprintf(b, "\t\"google.golang.org/protobuf/types/known/structpb\"\n\n")
	fmt.Fprintf(b, "\t\"github.com/stroppy-io/schemapb/schemapb\"\n)\n\n")
	fmt.Fprintf(b, "var _ = time.Second // keep imports used\n")
	fmt.Fprintf(b, "var _ = fmt.Sprintf\n")
	fmt.Fprintf(b, "var _ = sync.Once{}\n")
	fmt.Fprintf(b, "var _ *schemapb.Schema\n")
	fmt.Fprintf(b, "var _ *structpb.Struct\n")
	fmt.Fprintf(b, "var _ = proto.Marshal\n\n")
}
