// Package emit renders a model.File into gofmt'd Go source.
package emit

import (
	"bytes"
	"fmt"
	"go/format"

	"github.com/stroppy-io/schemapb/cmd/schemapbgen/internal/model"
)

// Emit renders one file (header + body) and runs it through gofmt.
func Emit(f *model.File) ([]byte, error) {
	return EmitMulti([]*model.File{f})
}

// EmitMulti renders several schemas into a single Go file: one shared header
// (package + imports) followed by each schema's body. All bodies share the same
// fixed import set, and every generated identifier is root-prefixed, so distinct
// roots never collide. Files must share the same package.
func EmitMulti(files []*model.File) ([]byte, error) {
	if len(files) == 0 {
		return nil, fmt.Errorf("no schemas to emit")
	}
	var b bytes.Buffer
	writeHeader(&b, files[0])
	for _, f := range files {
		writeBody(&b, f)
	}
	src, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("gofmt failed: %w\n--- raw ---\n%s", err, b.String())
	}
	return src, nil
}

// writeBody renders everything for one schema except the file header.
func writeBody(b *bytes.Buffer, f *model.File) {
	writeStructs(b, f)
	writeEnums(b, f)
	writeStrEnums(b, f)
	writeSchemaWrap(b, f)
	writeRoundtrip(b, f)
	writeSugar(b, f)
	writeCustomJSON(b, f)
}

func writeHeader(b *bytes.Buffer, f *model.File) {
	fmt.Fprintf(b, "// Code generated by schemapbgen. DO NOT EDIT.\n\n")
	fmt.Fprintf(b, "package %s\n\n", f.Package)
	fmt.Fprintf(b, "import (\n\t\"encoding/json\"\n\t\"fmt\"\n\t\"sync\"\n\t\"time\"\n\n")
	fmt.Fprintf(b, "\t\"google.golang.org/protobuf/proto\"\n")
	fmt.Fprintf(b, "\t\"google.golang.org/protobuf/types/known/structpb\"\n\n")
	fmt.Fprintf(b, "\t\"github.com/stroppy-io/schemapb/schemapb\"\n)\n\n")
	fmt.Fprintf(b, "var _ = time.Second // keep imports used\n")
	fmt.Fprintf(b, "var _ = fmt.Sprintf\n")
	fmt.Fprintf(b, "var _ = sync.Once{}\n")
	fmt.Fprintf(b, "var _ *schemapb.Schema\n")
	fmt.Fprintf(b, "var _ *structpb.Struct\n")
	fmt.Fprintf(b, "var _ = proto.Marshal\n\n")
}
