// Code generated by protoc-gen-go-hashpb. DO NOT EDIT.
// protoc-gen-go-hashpb v0.5.0

package schemapb

import (
	protowire "google.golang.org/protobuf/encoding/protowire"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	hash "hash"
	maps "maps"
	math "math"
	slices "slices"
	sync "sync"
	unsafe "unsafe"
)

var hashpb_bufPool = sync.Pool{
	New: func() any { return new([10]byte) },
}

var hashpb_stringKeyPool = sync.Pool{
	New: func() any { return make([]string, 0, 32) },
}

var hashpb_int32KeyPool = sync.Pool{
	New: func() any { return make([]int32, 0, 32) },
}

var hashpb_int64KeyPool = sync.Pool{
	New: func() any { return make([]int64, 0, 32) },
}

var hashpb_uint32KeyPool = sync.Pool{
	New: func() any { return make([]uint32, 0, 32) },
}

var hashpb_uint64KeyPool = sync.Pool{
	New: func() any { return make([]uint64, 0, 32) },
}

func google_protobuf_Duration_hashpb_sum(m *durationpb.Duration, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["google.protobuf.Duration.seconds"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(m.GetSeconds())))
	}
	if _, ok := ignore["google.protobuf.Duration.nanos"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(m.GetNanos())))
	}
}

func google_protobuf_ListValue_hashpb_sum(m *structpb.ListValue, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["google.protobuf.ListValue.values"]; !ok {
		if len(m.Values) > 0 {
			for _, v := range m.Values {
				if v != nil {
					google_protobuf_Value_hashpb_sum(v, hasher, ignore, b)
				}
			}
		}
	}
}

func google_protobuf_Struct_hashpb_sum(m *structpb.Struct, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["google.protobuf.Struct.fields"]; !ok {
		if len(m.Fields) > 0 {
			if len(m.Fields) <= 32 {
				keys := hashpb_stringKeyPool.Get().([]string)[:0]
				for k := range m.Fields {
					keys = append(keys, k)
				}
				slices.Sort(keys)
				for _, k := range keys {
					_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(k))))
					_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(k), len(k)))
					if m.Fields[k] != nil {
						google_protobuf_Value_hashpb_sum(m.Fields[k], hasher, ignore, b)
					}
				}
				hashpb_stringKeyPool.Put(keys)
			} else {
				for _, k := range slices.Sorted(maps.Keys(m.Fields)) {
					_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(k))))
					_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(k), len(k)))
					if m.Fields[k] != nil {
						google_protobuf_Value_hashpb_sum(m.Fields[k], hasher, ignore, b)
					}
				}
			}
		}
	}
}

func google_protobuf_Timestamp_hashpb_sum(m *timestamppb.Timestamp, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["google.protobuf.Timestamp.seconds"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(m.GetSeconds())))
	}
	if _, ok := ignore["google.protobuf.Timestamp.nanos"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(m.GetNanos())))
	}
}

func google_protobuf_Value_hashpb_sum(m *structpb.Value, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if m.Kind != nil {
		if _, ok := ignore["google.protobuf.Value.kind"]; !ok {
			switch t := m.Kind.(type) {
			case *structpb.Value_NullValue:
				_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(t.NullValue)))
			case *structpb.Value_NumberValue:
				_, _ = hasher.Write(protowire.AppendFixed64(b[:0], math.Float64bits(t.NumberValue)))
			case *structpb.Value_StringValue:
				_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(t.StringValue))))
				_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(t.StringValue), len(t.StringValue)))
			case *structpb.Value_BoolValue:
				_, _ = hasher.Write(protowire.AppendVarint(b[:0], protowire.EncodeBool(t.BoolValue)))
			case *structpb.Value_StructValue:
				if t.StructValue != nil {
					google_protobuf_Struct_hashpb_sum(t.StructValue, hasher, ignore, b)
				}
			case *structpb.Value_ListValue:
				if t.ListValue != nil {
					google_protobuf_ListValue_hashpb_sum(t.ListValue, hasher, ignore, b)
				}
			}
		}
	}
}

func schemapb_BakeResponse_hashpb_sum(m *BakeResponse, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["schemapb.BakeResponse.baked"]; !ok {
		if m.GetBaked() != nil {
			schemapb_Baked_hashpb_sum(m.GetBaked(), hasher, ignore, b)
		}
	}
	if _, ok := ignore["schemapb.BakeResponse.errors"]; !ok {
		if len(m.Errors) > 0 {
			for _, v := range m.Errors {
				if v != nil {
					schemapb_FieldError_hashpb_sum(v, hasher, ignore, b)
				}
			}
		}
	}
}

func schemapb_Baked_hashpb_sum(m *Baked, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["schemapb.Baked.schema"]; !ok {
		if m.GetSchema() != nil {
			schemapb_Schema_hashpb_sum(m.GetSchema(), hasher, ignore, b)
		}
	}
	if _, ok := ignore["schemapb.Baked.values"]; !ok {
		if m.GetValues() != nil {
			google_protobuf_Struct_hashpb_sum(m.GetValues(), hasher, ignore, b)
		}
	}
}

func schemapb_ComputeResponse_hashpb_sum(m *ComputeResponse, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["schemapb.ComputeResponse.values"]; !ok {
		if m.GetValues() != nil {
			google_protobuf_Struct_hashpb_sum(m.GetValues(), hasher, ignore, b)
		}
	}
	if _, ok := ignore["schemapb.ComputeResponse.errors"]; !ok {
		if len(m.Errors) > 0 {
			for _, v := range m.Errors {
				if v != nil {
					schemapb_FieldError_hashpb_sum(v, hasher, ignore, b)
				}
			}
		}
	}
}

func schemapb_FieldError_hashpb_sum(m *FieldError, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["schemapb.FieldError.field"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetField()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetField()), len(m.GetField())))
	}
	if _, ok := ignore["schemapb.FieldError.message"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetMessage()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetMessage()), len(m.GetMessage())))
	}
	if _, ok := ignore["schemapb.FieldError.rule_id"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetRuleId()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetRuleId()), len(m.GetRuleId())))
	}
	if _, ok := ignore["schemapb.FieldError.severity"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(m.GetSeverity())))
	}
	if _, ok := ignore["schemapb.FieldError.code"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetCode()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetCode()), len(m.GetCode())))
	}
	if _, ok := ignore["schemapb.FieldError.params"]; !ok {
		if len(m.Params) > 0 {
			if len(m.Params) <= 32 {
				keys := hashpb_stringKeyPool.Get().([]string)[:0]
				for k := range m.Params {
					keys = append(keys, k)
				}
				slices.Sort(keys)
				for _, k := range keys {
					_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(k))))
					_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(k), len(k)))
					_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.Params[k]))))
					_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.Params[k]), len(m.Params[k])))
				}
				hashpb_stringKeyPool.Put(keys)
			} else {
				for _, k := range slices.Sorted(maps.Keys(m.Params)) {
					_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(k))))
					_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(k), len(k)))
					_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.Params[k]))))
					_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.Params[k]), len(m.Params[k])))
				}
			}
		}
	}
}

func schemapb_Filled_hashpb_sum(m *Filled, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["schemapb.Filled.schema"]; !ok {
		if m.GetSchema() != nil {
			schemapb_SchemaRef_hashpb_sum(m.GetSchema(), hasher, ignore, b)
		}
	}
	if _, ok := ignore["schemapb.Filled.values"]; !ok {
		if m.GetValues() != nil {
			google_protobuf_Struct_hashpb_sum(m.GetValues(), hasher, ignore, b)
		}
	}
}

func schemapb_Filter_hashpb_sum(m *Filter, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["schemapb.Filter.namespace"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetNamespace()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetNamespace()), len(m.GetNamespace())))
	}
	if _, ok := ignore["schemapb.Filter.name"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetName()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetName()), len(m.GetName())))
	}
	if _, ok := ignore["schemapb.Filter.version"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetVersion()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetVersion()), len(m.GetVersion())))
	}
	if _, ok := ignore["schemapb.Filter.name_contains"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetNameContains()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetNameContains()), len(m.GetNameContains())))
	}
}

func schemapb_ListSchemasResponse_hashpb_sum(m *ListSchemasResponse, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["schemapb.ListSchemasResponse.schemas"]; !ok {
		if len(m.Schemas) > 0 {
			for _, v := range m.Schemas {
				if v != nil {
					schemapb_SchemaSummary_hashpb_sum(v, hasher, ignore, b)
				}
			}
		}
	}
}

func schemapb_MergeRequest_hashpb_sum(m *MergeRequest, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["schemapb.MergeRequest.base"]; !ok {
		if m.GetBase() != nil {
			schemapb_Baked_hashpb_sum(m.GetBase(), hasher, ignore, b)
		}
	}
	if _, ok := ignore["schemapb.MergeRequest.overrides"]; !ok {
		if m.GetOverrides() != nil {
			google_protobuf_Struct_hashpb_sum(m.GetOverrides(), hasher, ignore, b)
		}
	}
	if _, ok := ignore["schemapb.MergeRequest.lists"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(m.GetLists())))
	}
}

func schemapb_RegisterSchemaResponse_hashpb_sum(m *RegisterSchemaResponse, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["schemapb.RegisterSchemaResponse.id"]; !ok {
		if m.GetId() != nil {
			schemapb_SchemaIdentity_hashpb_sum(m.GetId(), hasher, ignore, b)
		}
	}
	if _, ok := ignore["schemapb.RegisterSchemaResponse.valid"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], protowire.EncodeBool(m.GetValid())))
	}
	if _, ok := ignore["schemapb.RegisterSchemaResponse.errors"]; !ok {
		if len(m.Errors) > 0 {
			for _, v := range m.Errors {
				if v != nil {
					schemapb_FieldError_hashpb_sum(v, hasher, ignore, b)
				}
			}
		}
	}
}

func schemapb_SchemaIdentity_hashpb_sum(m *SchemaIdentity, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["schemapb.SchemaIdentity.namespace"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetNamespace()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetNamespace()), len(m.GetNamespace())))
	}
	if _, ok := ignore["schemapb.SchemaIdentity.name"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetName()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetName()), len(m.GetName())))
	}
	if _, ok := ignore["schemapb.SchemaIdentity.version"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetVersion()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetVersion()), len(m.GetVersion())))
	}
}

func schemapb_SchemaRef_hashpb_sum(m *SchemaRef, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if m.Source != nil {
		if _, ok := ignore["schemapb.SchemaRef.source"]; !ok {
			switch t := m.Source.(type) {
			case *SchemaRef_Id:
				if t.Id != nil {
					schemapb_SchemaIdentity_hashpb_sum(t.Id, hasher, ignore, b)
				}
			case *SchemaRef_Schema:
				if t.Schema != nil {
					schemapb_Schema_hashpb_sum(t.Schema, hasher, ignore, b)
				}
			}
		}
	}
}

func schemapb_SchemaSummary_hashpb_sum(m *SchemaSummary, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["schemapb.SchemaSummary.id"]; !ok {
		if m.GetId() != nil {
			schemapb_SchemaIdentity_hashpb_sum(m.GetId(), hasher, ignore, b)
		}
	}
	if _, ok := ignore["schemapb.SchemaSummary.description"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetDescription()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetDescription()), len(m.GetDescription())))
	}
}

func schemapb_Schema_Filed_Bool_hashpb_sum(m *Schema_Filed_Bool, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["schemapb.Schema.Filed.Bool.default"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], protowire.EncodeBool(m.GetDefault())))
	}
	if _, ok := ignore["schemapb.Schema.Filed.Bool.const"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], protowire.EncodeBool(m.GetConst())))
	}
}

func schemapb_Schema_Filed_Computed_hashpb_sum(m *Schema_Filed_Computed, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["schemapb.Schema.Filed.Computed.expr"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetExpr()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetExpr()), len(m.GetExpr())))
	}
	if _, ok := ignore["schemapb.Schema.Filed.Computed.result"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(m.GetResult())))
	}
}

func schemapb_Schema_Filed_Double_hashpb_sum(m *Schema_Filed_Double, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["schemapb.Schema.Filed.Double.default"]; !ok {
		_, _ = hasher.Write(protowire.AppendFixed64(b[:0], math.Float64bits(m.GetDefault())))
	}
	if _, ok := ignore["schemapb.Schema.Filed.Double.const"]; !ok {
		_, _ = hasher.Write(protowire.AppendFixed64(b[:0], math.Float64bits(m.GetConst())))
	}
	if _, ok := ignore["schemapb.Schema.Filed.Double.gt"]; !ok {
		_, _ = hasher.Write(protowire.AppendFixed64(b[:0], math.Float64bits(m.GetGt())))
	}
	if _, ok := ignore["schemapb.Schema.Filed.Double.gte"]; !ok {
		_, _ = hasher.Write(protowire.AppendFixed64(b[:0], math.Float64bits(m.GetGte())))
	}
	if _, ok := ignore["schemapb.Schema.Filed.Double.lt"]; !ok {
		_, _ = hasher.Write(protowire.AppendFixed64(b[:0], math.Float64bits(m.GetLt())))
	}
	if _, ok := ignore["schemapb.Schema.Filed.Double.lte"]; !ok {
		_, _ = hasher.Write(protowire.AppendFixed64(b[:0], math.Float64bits(m.GetLte())))
	}
	if _, ok := ignore["schemapb.Schema.Filed.Double.in"]; !ok {
		if len(m.In) > 0 {
			for _, v := range m.In {
				_, _ = hasher.Write(protowire.AppendFixed64(b[:0], math.Float64bits(v)))
			}
		}
	}
	if _, ok := ignore["schemapb.Schema.Filed.Double.not_in"]; !ok {
		if len(m.NotIn) > 0 {
			for _, v := range m.NotIn {
				_, _ = hasher.Write(protowire.AppendFixed64(b[:0], math.Float64bits(v)))
			}
		}
	}
	if _, ok := ignore["schemapb.Schema.Filed.Double.multiple_of"]; !ok {
		_, _ = hasher.Write(protowire.AppendFixed64(b[:0], math.Float64bits(m.GetMultipleOf())))
	}
}

func schemapb_Schema_Filed_Duration_hashpb_sum(m *Schema_Filed_Duration, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["schemapb.Schema.Filed.Duration.default"]; !ok {
		if m.GetDefault() != nil {
			google_protobuf_Duration_hashpb_sum(m.GetDefault(), hasher, ignore, b)
		}
	}
	if _, ok := ignore["schemapb.Schema.Filed.Duration.gt"]; !ok {
		if m.GetGt() != nil {
			google_protobuf_Duration_hashpb_sum(m.GetGt(), hasher, ignore, b)
		}
	}
	if _, ok := ignore["schemapb.Schema.Filed.Duration.gte"]; !ok {
		if m.GetGte() != nil {
			google_protobuf_Duration_hashpb_sum(m.GetGte(), hasher, ignore, b)
		}
	}
	if _, ok := ignore["schemapb.Schema.Filed.Duration.lt"]; !ok {
		if m.GetLt() != nil {
			google_protobuf_Duration_hashpb_sum(m.GetLt(), hasher, ignore, b)
		}
	}
	if _, ok := ignore["schemapb.Schema.Filed.Duration.lte"]; !ok {
		if m.GetLte() != nil {
			google_protobuf_Duration_hashpb_sum(m.GetLte(), hasher, ignore, b)
		}
	}
}

func schemapb_Schema_Filed_Enum_hashpb_sum(m *Schema_Filed_Enum, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["schemapb.Schema.Filed.Enum.default"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(m.GetDefault())))
	}
	if _, ok := ignore["schemapb.Schema.Filed.Enum.values"]; !ok {
		if len(m.Values) > 0 {
			if len(m.Values) <= 32 {
				keys := hashpb_int32KeyPool.Get().([]int32)[:0]
				for k := range m.Values {
					keys = append(keys, k)
				}
				slices.Sort(keys)
				for _, k := range keys {
					_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(k)))
					_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.Values[k]))))
					_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.Values[k]), len(m.Values[k])))
				}
				hashpb_int32KeyPool.Put(keys)
			} else {
				for _, k := range slices.Sorted(maps.Keys(m.Values)) {
					_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(k)))
					_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.Values[k]))))
					_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.Values[k]), len(m.Values[k])))
				}
			}
		}
	}
	if _, ok := ignore["schemapb.Schema.Filed.Enum.defined_only"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], protowire.EncodeBool(m.GetDefinedOnly())))
	}
	if _, ok := ignore["schemapb.Schema.Filed.Enum.in"]; !ok {
		if len(m.In) > 0 {
			for _, v := range m.In {
				_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(v)))
			}
		}
	}
	if _, ok := ignore["schemapb.Schema.Filed.Enum.not_in"]; !ok {
		if len(m.NotIn) > 0 {
			for _, v := range m.NotIn {
				_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(v)))
			}
		}
	}
}

func schemapb_Schema_Filed_Float_hashpb_sum(m *Schema_Filed_Float, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["schemapb.Schema.Filed.Float.default"]; !ok {
		_, _ = hasher.Write(protowire.AppendFixed32(b[:0], math.Float32bits(m.GetDefault())))
	}
	if _, ok := ignore["schemapb.Schema.Filed.Float.const"]; !ok {
		_, _ = hasher.Write(protowire.AppendFixed32(b[:0], math.Float32bits(m.GetConst())))
	}
	if _, ok := ignore["schemapb.Schema.Filed.Float.gt"]; !ok {
		_, _ = hasher.Write(protowire.AppendFixed32(b[:0], math.Float32bits(m.GetGt())))
	}
	if _, ok := ignore["schemapb.Schema.Filed.Float.gte"]; !ok {
		_, _ = hasher.Write(protowire.AppendFixed32(b[:0], math.Float32bits(m.GetGte())))
	}
	if _, ok := ignore["schemapb.Schema.Filed.Float.lt"]; !ok {
		_, _ = hasher.Write(protowire.AppendFixed32(b[:0], math.Float32bits(m.GetLt())))
	}
	if _, ok := ignore["schemapb.Schema.Filed.Float.lte"]; !ok {
		_, _ = hasher.Write(protowire.AppendFixed32(b[:0], math.Float32bits(m.GetLte())))
	}
	if _, ok := ignore["schemapb.Schema.Filed.Float.in"]; !ok {
		if len(m.In) > 0 {
			for _, v := range m.In {
				_, _ = hasher.Write(protowire.AppendFixed32(b[:0], math.Float32bits(v)))
			}
		}
	}
	if _, ok := ignore["schemapb.Schema.Filed.Float.not_in"]; !ok {
		if len(m.NotIn) > 0 {
			for _, v := range m.NotIn {
				_, _ = hasher.Write(protowire.AppendFixed32(b[:0], math.Float32bits(v)))
			}
		}
	}
	if _, ok := ignore["schemapb.Schema.Filed.Float.multiple_of"]; !ok {
		_, _ = hasher.Write(protowire.AppendFixed32(b[:0], math.Float32bits(m.GetMultipleOf())))
	}
}

func schemapb_Schema_Filed_Int32_hashpb_sum(m *Schema_Filed_Int32, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["schemapb.Schema.Filed.Int32.default"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(m.GetDefault())))
	}
	if _, ok := ignore["schemapb.Schema.Filed.Int32.const"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(m.GetConst())))
	}
	if _, ok := ignore["schemapb.Schema.Filed.Int32.gt"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(m.GetGt())))
	}
	if _, ok := ignore["schemapb.Schema.Filed.Int32.gte"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(m.GetGte())))
	}
	if _, ok := ignore["schemapb.Schema.Filed.Int32.lt"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(m.GetLt())))
	}
	if _, ok := ignore["schemapb.Schema.Filed.Int32.lte"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(m.GetLte())))
	}
	if _, ok := ignore["schemapb.Schema.Filed.Int32.in"]; !ok {
		if len(m.In) > 0 {
			for _, v := range m.In {
				_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(v)))
			}
		}
	}
	if _, ok := ignore["schemapb.Schema.Filed.Int32.not_in"]; !ok {
		if len(m.NotIn) > 0 {
			for _, v := range m.NotIn {
				_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(v)))
			}
		}
	}
	if _, ok := ignore["schemapb.Schema.Filed.Int32.multiple_of"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(m.GetMultipleOf())))
	}
}

func schemapb_Schema_Filed_Int64_hashpb_sum(m *Schema_Filed_Int64, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["schemapb.Schema.Filed.Int64.default"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(m.GetDefault())))
	}
	if _, ok := ignore["schemapb.Schema.Filed.Int64.const"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(m.GetConst())))
	}
	if _, ok := ignore["schemapb.Schema.Filed.Int64.gt"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(m.GetGt())))
	}
	if _, ok := ignore["schemapb.Schema.Filed.Int64.gte"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(m.GetGte())))
	}
	if _, ok := ignore["schemapb.Schema.Filed.Int64.lt"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(m.GetLt())))
	}
	if _, ok := ignore["schemapb.Schema.Filed.Int64.lte"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(m.GetLte())))
	}
	if _, ok := ignore["schemapb.Schema.Filed.Int64.in"]; !ok {
		if len(m.In) > 0 {
			for _, v := range m.In {
				_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(v)))
			}
		}
	}
	if _, ok := ignore["schemapb.Schema.Filed.Int64.not_in"]; !ok {
		if len(m.NotIn) > 0 {
			for _, v := range m.NotIn {
				_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(v)))
			}
		}
	}
	if _, ok := ignore["schemapb.Schema.Filed.Int64.multiple_of"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(m.GetMultipleOf())))
	}
}

func schemapb_Schema_Filed_List_hashpb_sum(m *Schema_Filed_List, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["schemapb.Schema.Filed.List.items"]; !ok {
		if len(m.Items) > 0 {
			for _, v := range m.Items {
				if v != nil {
					schemapb_Schema_Filed_hashpb_sum(v, hasher, ignore, b)
				}
			}
		}
	}
	if _, ok := ignore["schemapb.Schema.Filed.List.min_items"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], m.GetMinItems()))
	}
	if _, ok := ignore["schemapb.Schema.Filed.List.max_items"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], m.GetMaxItems()))
	}
	if _, ok := ignore["schemapb.Schema.Filed.List.unique"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], protowire.EncodeBool(m.GetUnique())))
	}
}

func schemapb_Schema_Filed_Object_hashpb_sum(m *Schema_Filed_Object, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["schemapb.Schema.Filed.Object.schema"]; !ok {
		if m.GetSchema() != nil {
			schemapb_Schema_hashpb_sum(m.GetSchema(), hasher, ignore, b)
		}
	}
}

func schemapb_Schema_Filed_Rule_hashpb_sum(m *Schema_Filed_Rule, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["schemapb.Schema.Filed.Rule.expr"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetExpr()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetExpr()), len(m.GetExpr())))
	}
	if _, ok := ignore["schemapb.Schema.Filed.Rule.message"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetMessage()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetMessage()), len(m.GetMessage())))
	}
	if _, ok := ignore["schemapb.Schema.Filed.Rule.id"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetId()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetId()), len(m.GetId())))
	}
	if _, ok := ignore["schemapb.Schema.Filed.Rule.severity"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(m.GetSeverity())))
	}
}

func schemapb_Schema_Filed_String_hashpb_sum(m *Schema_Filed_String, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["schemapb.Schema.Filed.String.default"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetDefault()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetDefault()), len(m.GetDefault())))
	}
	if _, ok := ignore["schemapb.Schema.Filed.String.const"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetConst()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetConst()), len(m.GetConst())))
	}
	if _, ok := ignore["schemapb.Schema.Filed.String.len"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], m.GetLen()))
	}
	if _, ok := ignore["schemapb.Schema.Filed.String.min_len"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], m.GetMinLen()))
	}
	if _, ok := ignore["schemapb.Schema.Filed.String.max_len"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], m.GetMaxLen()))
	}
	if _, ok := ignore["schemapb.Schema.Filed.String.pattern"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetPattern()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetPattern()), len(m.GetPattern())))
	}
	if _, ok := ignore["schemapb.Schema.Filed.String.in"]; !ok {
		if len(m.In) > 0 {
			for _, v := range m.In {
				_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(v))))
				_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(v), len(v)))
			}
		}
	}
	if _, ok := ignore["schemapb.Schema.Filed.String.not_in"]; !ok {
		if len(m.NotIn) > 0 {
			for _, v := range m.NotIn {
				_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(v))))
				_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(v), len(v)))
			}
		}
	}
	if _, ok := ignore["schemapb.Schema.Filed.String.format"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(m.GetFormat())))
	}
}

func schemapb_Schema_Filed_Timestamp_hashpb_sum(m *Schema_Filed_Timestamp, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["schemapb.Schema.Filed.Timestamp.default"]; !ok {
		if m.GetDefault() != nil {
			google_protobuf_Timestamp_hashpb_sum(m.GetDefault(), hasher, ignore, b)
		}
	}
	if _, ok := ignore["schemapb.Schema.Filed.Timestamp.gt"]; !ok {
		if m.GetGt() != nil {
			google_protobuf_Timestamp_hashpb_sum(m.GetGt(), hasher, ignore, b)
		}
	}
	if _, ok := ignore["schemapb.Schema.Filed.Timestamp.gte"]; !ok {
		if m.GetGte() != nil {
			google_protobuf_Timestamp_hashpb_sum(m.GetGte(), hasher, ignore, b)
		}
	}
	if _, ok := ignore["schemapb.Schema.Filed.Timestamp.lt"]; !ok {
		if m.GetLt() != nil {
			google_protobuf_Timestamp_hashpb_sum(m.GetLt(), hasher, ignore, b)
		}
	}
	if _, ok := ignore["schemapb.Schema.Filed.Timestamp.lte"]; !ok {
		if m.GetLte() != nil {
			google_protobuf_Timestamp_hashpb_sum(m.GetLte(), hasher, ignore, b)
		}
	}
}

func schemapb_Schema_Filed_UInt32_hashpb_sum(m *Schema_Filed_UInt32, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["schemapb.Schema.Filed.UInt32.default"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(m.GetDefault())))
	}
	if _, ok := ignore["schemapb.Schema.Filed.UInt32.const"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(m.GetConst())))
	}
	if _, ok := ignore["schemapb.Schema.Filed.UInt32.gt"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(m.GetGt())))
	}
	if _, ok := ignore["schemapb.Schema.Filed.UInt32.gte"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(m.GetGte())))
	}
	if _, ok := ignore["schemapb.Schema.Filed.UInt32.lt"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(m.GetLt())))
	}
	if _, ok := ignore["schemapb.Schema.Filed.UInt32.lte"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(m.GetLte())))
	}
	if _, ok := ignore["schemapb.Schema.Filed.UInt32.in"]; !ok {
		if len(m.In) > 0 {
			for _, v := range m.In {
				_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(v)))
			}
		}
	}
	if _, ok := ignore["schemapb.Schema.Filed.UInt32.not_in"]; !ok {
		if len(m.NotIn) > 0 {
			for _, v := range m.NotIn {
				_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(v)))
			}
		}
	}
	if _, ok := ignore["schemapb.Schema.Filed.UInt32.multiple_of"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(m.GetMultipleOf())))
	}
}

func schemapb_Schema_Filed_UInt64_hashpb_sum(m *Schema_Filed_UInt64, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["schemapb.Schema.Filed.UInt64.default"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], m.GetDefault()))
	}
	if _, ok := ignore["schemapb.Schema.Filed.UInt64.const"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], m.GetConst()))
	}
	if _, ok := ignore["schemapb.Schema.Filed.UInt64.gt"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], m.GetGt()))
	}
	if _, ok := ignore["schemapb.Schema.Filed.UInt64.gte"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], m.GetGte()))
	}
	if _, ok := ignore["schemapb.Schema.Filed.UInt64.lt"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], m.GetLt()))
	}
	if _, ok := ignore["schemapb.Schema.Filed.UInt64.lte"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], m.GetLte()))
	}
	if _, ok := ignore["schemapb.Schema.Filed.UInt64.in"]; !ok {
		if len(m.In) > 0 {
			for _, v := range m.In {
				_, _ = hasher.Write(protowire.AppendVarint(b[:0], v))
			}
		}
	}
	if _, ok := ignore["schemapb.Schema.Filed.UInt64.not_in"]; !ok {
		if len(m.NotIn) > 0 {
			for _, v := range m.NotIn {
				_, _ = hasher.Write(protowire.AppendVarint(b[:0], v))
			}
		}
	}
	if _, ok := ignore["schemapb.Schema.Filed.UInt64.multiple_of"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], m.GetMultipleOf()))
	}
}

func schemapb_Schema_Filed_hashpb_sum(m *Schema_Filed, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["schemapb.Schema.Filed.name"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetName()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetName()), len(m.GetName())))
	}
	if _, ok := ignore["schemapb.Schema.Filed.description"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetDescription()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetDescription()), len(m.GetDescription())))
	}
	if _, ok := ignore["schemapb.Schema.Filed.nullable"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], protowire.EncodeBool(m.GetNullable())))
	}
	if _, ok := ignore["schemapb.Schema.Filed.required"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], protowire.EncodeBool(m.GetRequired())))
	}
	if _, ok := ignore["schemapb.Schema.Filed.rules"]; !ok {
		if len(m.Rules) > 0 {
			for _, v := range m.Rules {
				if v != nil {
					schemapb_Schema_Filed_Rule_hashpb_sum(v, hasher, ignore, b)
				}
			}
		}
	}
	if m.Kind != nil {
		if _, ok := ignore["schemapb.Schema.Filed.kind"]; !ok {
			switch t := m.Kind.(type) {
			case *Schema_Filed_Float_:
				if t.Float != nil {
					schemapb_Schema_Filed_Float_hashpb_sum(t.Float, hasher, ignore, b)
				}
			case *Schema_Filed_Double_:
				if t.Double != nil {
					schemapb_Schema_Filed_Double_hashpb_sum(t.Double, hasher, ignore, b)
				}
			case *Schema_Filed_Int32_:
				if t.Int32 != nil {
					schemapb_Schema_Filed_Int32_hashpb_sum(t.Int32, hasher, ignore, b)
				}
			case *Schema_Filed_Int64_:
				if t.Int64 != nil {
					schemapb_Schema_Filed_Int64_hashpb_sum(t.Int64, hasher, ignore, b)
				}
			case *Schema_Filed_Uint32:
				if t.Uint32 != nil {
					schemapb_Schema_Filed_UInt32_hashpb_sum(t.Uint32, hasher, ignore, b)
				}
			case *Schema_Filed_Uint64:
				if t.Uint64 != nil {
					schemapb_Schema_Filed_UInt64_hashpb_sum(t.Uint64, hasher, ignore, b)
				}
			case *Schema_Filed_Bool_:
				if t.Bool != nil {
					schemapb_Schema_Filed_Bool_hashpb_sum(t.Bool, hasher, ignore, b)
				}
			case *Schema_Filed_String_:
				if t.String_ != nil {
					schemapb_Schema_Filed_String_hashpb_sum(t.String_, hasher, ignore, b)
				}
			case *Schema_Filed_Enum_:
				if t.Enum != nil {
					schemapb_Schema_Filed_Enum_hashpb_sum(t.Enum, hasher, ignore, b)
				}
			case *Schema_Filed_Duration_:
				if t.Duration != nil {
					schemapb_Schema_Filed_Duration_hashpb_sum(t.Duration, hasher, ignore, b)
				}
			case *Schema_Filed_Timestamp_:
				if t.Timestamp != nil {
					schemapb_Schema_Filed_Timestamp_hashpb_sum(t.Timestamp, hasher, ignore, b)
				}
			case *Schema_Filed_List_:
				if t.List != nil {
					schemapb_Schema_Filed_List_hashpb_sum(t.List, hasher, ignore, b)
				}
			case *Schema_Filed_Object_:
				if t.Object != nil {
					schemapb_Schema_Filed_Object_hashpb_sum(t.Object, hasher, ignore, b)
				}
			case *Schema_Filed_Computed_:
				if t.Computed != nil {
					schemapb_Schema_Filed_Computed_hashpb_sum(t.Computed, hasher, ignore, b)
				}
			}
		}
	}
	if _, ok := ignore["schemapb.Schema.Filed.immutable"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], protowire.EncodeBool(m.GetImmutable())))
	}
	if _, ok := ignore["schemapb.Schema.Filed.group"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetGroup()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetGroup()), len(m.GetGroup())))
	}
	if _, ok := ignore["schemapb.Schema.Filed.unit"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetUnit()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetUnit()), len(m.GetUnit())))
	}
	if _, ok := ignore["schemapb.Schema.Filed.title"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetTitle()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetTitle()), len(m.GetTitle())))
	}
	if _, ok := ignore["schemapb.Schema.Filed.deprecated"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], protowire.EncodeBool(m.GetDeprecated())))
	}
	if _, ok := ignore["schemapb.Schema.Filed.examples"]; !ok {
		if len(m.Examples) > 0 {
			for _, v := range m.Examples {
				if v != nil {
					google_protobuf_Value_hashpb_sum(v, hasher, ignore, b)
				}
			}
		}
	}
	if _, ok := ignore["schemapb.Schema.Filed.secret"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], protowire.EncodeBool(m.GetSecret())))
	}
}

func schemapb_Schema_hashpb_sum(m *Schema, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["schemapb.Schema.id"]; !ok {
		if m.GetId() != nil {
			schemapb_SchemaIdentity_hashpb_sum(m.GetId(), hasher, ignore, b)
		}
	}
	if _, ok := ignore["schemapb.Schema.description"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetDescription()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetDescription()), len(m.GetDescription())))
	}
	if _, ok := ignore["schemapb.Schema.fields"]; !ok {
		if len(m.Fields) > 0 {
			for _, v := range m.Fields {
				if v != nil {
					schemapb_Schema_Filed_hashpb_sum(v, hasher, ignore, b)
				}
			}
		}
	}
	if _, ok := ignore["schemapb.Schema.rules"]; !ok {
		if len(m.Rules) > 0 {
			for _, v := range m.Rules {
				if v != nil {
					schemapb_Schema_Filed_Rule_hashpb_sum(v, hasher, ignore, b)
				}
			}
		}
	}
	if _, ok := ignore["schemapb.Schema.strict"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], protowire.EncodeBool(m.GetStrict())))
	}
	if _, ok := ignore["schemapb.Schema.min_properties"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], m.GetMinProperties()))
	}
	if _, ok := ignore["schemapb.Schema.max_properties"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], m.GetMaxProperties()))
	}
	if _, ok := ignore["schemapb.Schema.coerce"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], protowire.EncodeBool(m.GetCoerce())))
	}
}

func schemapb_ValidateResponse_hashpb_sum(m *ValidateResponse, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["schemapb.ValidateResponse.valid"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], protowire.EncodeBool(m.GetValid())))
	}
	if _, ok := ignore["schemapb.ValidateResponse.errors"]; !ok {
		if len(m.Errors) > 0 {
			for _, v := range m.Errors {
				if v != nil {
					schemapb_FieldError_hashpb_sum(v, hasher, ignore, b)
				}
			}
		}
	}
}

func schemapb_ValidateSchemaResponse_hashpb_sum(m *ValidateSchemaResponse, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["schemapb.ValidateSchemaResponse.valid"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], protowire.EncodeBool(m.GetValid())))
	}
	if _, ok := ignore["schemapb.ValidateSchemaResponse.errors"]; !ok {
		if len(m.Errors) > 0 {
			for _, v := range m.Errors {
				if v != nil {
					schemapb_FieldError_hashpb_sum(v, hasher, ignore, b)
				}
			}
		}
	}
}
