// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: schemapb/schema.proto

package schemapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ResultType is the wire type a Computed expression yields.
type Schema_Filed_ResultType int32

const (
	// Unset: infer from the expression.
	Schema_Filed_RESULT_TYPE_UNSPECIFIED Schema_Filed_ResultType = 0
	Schema_Filed_RESULT_TYPE_DOUBLE      Schema_Filed_ResultType = 1
	Schema_Filed_RESULT_TYPE_INT64       Schema_Filed_ResultType = 2
	Schema_Filed_RESULT_TYPE_UINT64      Schema_Filed_ResultType = 3
	Schema_Filed_RESULT_TYPE_BOOL        Schema_Filed_ResultType = 4
	Schema_Filed_RESULT_TYPE_STRING      Schema_Filed_ResultType = 5
	Schema_Filed_RESULT_TYPE_DURATION    Schema_Filed_ResultType = 6
)

// Enum value maps for Schema_Filed_ResultType.
var (
	Schema_Filed_ResultType_name = map[int32]string{
		0: "RESULT_TYPE_UNSPECIFIED",
		1: "RESULT_TYPE_DOUBLE",
		2: "RESULT_TYPE_INT64",
		3: "RESULT_TYPE_UINT64",
		4: "RESULT_TYPE_BOOL",
		5: "RESULT_TYPE_STRING",
		6: "RESULT_TYPE_DURATION",
	}
	Schema_Filed_ResultType_value = map[string]int32{
		"RESULT_TYPE_UNSPECIFIED": 0,
		"RESULT_TYPE_DOUBLE":      1,
		"RESULT_TYPE_INT64":       2,
		"RESULT_TYPE_UINT64":      3,
		"RESULT_TYPE_BOOL":        4,
		"RESULT_TYPE_STRING":      5,
		"RESULT_TYPE_DURATION":    6,
	}
)

func (x Schema_Filed_ResultType) Enum() *Schema_Filed_ResultType {
	p := new(Schema_Filed_ResultType)
	*p = x
	return p
}

func (x Schema_Filed_ResultType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Schema_Filed_ResultType) Descriptor() protoreflect.EnumDescriptor {
	return file_schemapb_schema_proto_enumTypes[0].Descriptor()
}

func (Schema_Filed_ResultType) Type() protoreflect.EnumType {
	return &file_schemapb_schema_proto_enumTypes[0]
}

func (x Schema_Filed_ResultType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Schema_Filed_ResultType.Descriptor instead.
func (Schema_Filed_ResultType) EnumDescriptor() ([]byte, []int) {
	return file_schemapb_schema_proto_rawDescGZIP(), []int{0, 0, 0}
}

// Severity of a failed rule.
type Schema_Filed_Severity int32

const (
	// Unset: treated as ERROR.
	Schema_Filed_SEVERITY_UNSPECIFIED Schema_Filed_Severity = 0
	// Blocks submit.
	Schema_Filed_ERROR Schema_Filed_Severity = 1
	// Surfaced to the user but does not block submit.
	Schema_Filed_WARNING Schema_Filed_Severity = 2
)

// Enum value maps for Schema_Filed_Severity.
var (
	Schema_Filed_Severity_name = map[int32]string{
		0: "SEVERITY_UNSPECIFIED",
		1: "ERROR",
		2: "WARNING",
	}
	Schema_Filed_Severity_value = map[string]int32{
		"SEVERITY_UNSPECIFIED": 0,
		"ERROR":                1,
		"WARNING":              2,
	}
)

func (x Schema_Filed_Severity) Enum() *Schema_Filed_Severity {
	p := new(Schema_Filed_Severity)
	*p = x
	return p
}

func (x Schema_Filed_Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Schema_Filed_Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_schemapb_schema_proto_enumTypes[1].Descriptor()
}

func (Schema_Filed_Severity) Type() protoreflect.EnumType {
	return &file_schemapb_schema_proto_enumTypes[1]
}

func (x Schema_Filed_Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Schema_Filed_Severity.Descriptor instead.
func (Schema_Filed_Severity) EnumDescriptor() ([]byte, []int) {
	return file_schemapb_schema_proto_rawDescGZIP(), []int{0, 0, 1}
}

// StringFormat enumerates well-known semantic string formats.
type Schema_Filed_String_StringFormat int32

const (
	Schema_Filed_String_STRING_FORMAT_UNSPECIFIED Schema_Filed_String_StringFormat = 0
	Schema_Filed_String_STRING_FORMAT_EMAIL       Schema_Filed_String_StringFormat = 1
	Schema_Filed_String_STRING_FORMAT_URL         Schema_Filed_String_StringFormat = 2
	Schema_Filed_String_STRING_FORMAT_UUID        Schema_Filed_String_StringFormat = 3
	Schema_Filed_String_STRING_FORMAT_IPV4        Schema_Filed_String_StringFormat = 4
	Schema_Filed_String_STRING_FORMAT_IPV6        Schema_Filed_String_StringFormat = 5
	Schema_Filed_String_STRING_FORMAT_IP          Schema_Filed_String_StringFormat = 6
	Schema_Filed_String_STRING_FORMAT_HOSTNAME    Schema_Filed_String_StringFormat = 7
	Schema_Filed_String_STRING_FORMAT_DATE        Schema_Filed_String_StringFormat = 8
	Schema_Filed_String_STRING_FORMAT_TIME        Schema_Filed_String_StringFormat = 9
	Schema_Filed_String_STRING_FORMAT_DATETIME    Schema_Filed_String_StringFormat = 10
)

// Enum value maps for Schema_Filed_String_StringFormat.
var (
	Schema_Filed_String_StringFormat_name = map[int32]string{
		0:  "STRING_FORMAT_UNSPECIFIED",
		1:  "STRING_FORMAT_EMAIL",
		2:  "STRING_FORMAT_URL",
		3:  "STRING_FORMAT_UUID",
		4:  "STRING_FORMAT_IPV4",
		5:  "STRING_FORMAT_IPV6",
		6:  "STRING_FORMAT_IP",
		7:  "STRING_FORMAT_HOSTNAME",
		8:  "STRING_FORMAT_DATE",
		9:  "STRING_FORMAT_TIME",
		10: "STRING_FORMAT_DATETIME",
	}
	Schema_Filed_String_StringFormat_value = map[string]int32{
		"STRING_FORMAT_UNSPECIFIED": 0,
		"STRING_FORMAT_EMAIL":       1,
		"STRING_FORMAT_URL":         2,
		"STRING_FORMAT_UUID":        3,
		"STRING_FORMAT_IPV4":        4,
		"STRING_FORMAT_IPV6":        5,
		"STRING_FORMAT_IP":          6,
		"STRING_FORMAT_HOSTNAME":    7,
		"STRING_FORMAT_DATE":        8,
		"STRING_FORMAT_TIME":        9,
		"STRING_FORMAT_DATETIME":    10,
	}
)

func (x Schema_Filed_String_StringFormat) Enum() *Schema_Filed_String_StringFormat {
	p := new(Schema_Filed_String_StringFormat)
	*p = x
	return p
}

func (x Schema_Filed_String_StringFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Schema_Filed_String_StringFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_schemapb_schema_proto_enumTypes[2].Descriptor()
}

func (Schema_Filed_String_StringFormat) Type() protoreflect.EnumType {
	return &file_schemapb_schema_proto_enumTypes[2]
}

func (x Schema_Filed_String_StringFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Schema_Filed_String_StringFormat.Descriptor instead.
func (Schema_Filed_String_StringFormat) EnumDescriptor() ([]byte, []int) {
	return file_schemapb_schema_proto_rawDescGZIP(), []int{0, 0, 7, 0}
}

// Schema is a runtime, dynamic form descriptor. The server builds a Schema and
// ships it to the frontend, which renders a form from it.
//
// Validation has two layers:
//   - per-kind structured rules (gt/gte/lt/lte/in/pattern/...) for the common,
//     single-field cases. Ergonomic to author and introspectable by the
//     renderer (e.g. slider bounds, step).
//   - Filed.rules: CEL expressions, for cross-field / conditional validation.
//
// Both layers run through one engine: structured rules are lowered to CEL at
// load time, then evaluated by cel-go (server, authoritative) and cel-es
// (client, live UX) from the same expression. Rendering is described by a
// separate Form (see ui.proto) that references fields by path; the Schema
// itself carries no UI.
//
// The PGV (validate.rules) options below validate the descriptor ITSELF (that a
// Schema is well-formed: names set, expressions non-empty, a kind chosen), not
// the runtime form values it describes.
type Schema struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable identity of this schema. Required: the validator rejects a schema
	// whose id is unset or whose name is empty.
	Id *SchemaIdentity `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Human description of the schema.
	Description *string `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// The fields that make up the form.
	Fields []*Schema_Filed `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	// Form-wide invariant rules (`root` only, no `this`).
	Rules []*Schema_Filed_Rule `protobuf:"bytes,4,rep,name=rules,proto3" json:"rules,omitempty"`
	// If true, any key in the values map that is not a declared field name
	// is an error (code "unknown_field").
	Strict bool `protobuf:"varint,5,opt,name=strict,proto3" json:"strict,omitempty"`
	// Minimum number of properties that must be present in the values map.
	MinProperties *uint64 `protobuf:"varint,6,opt,name=min_properties,json=minProperties,proto3,oneof" json:"min_properties,omitempty"`
	// Maximum number of properties allowed in the values map.
	MaxProperties *uint64 `protobuf:"varint,7,opt,name=max_properties,json=maxProperties,proto3,oneof" json:"max_properties,omitempty"`
	// If true, scalar string inputs are coerced to the field's kind before
	// validation (numeric kinds parse the string as a number; bool parses
	// "true"/"false"; enum parses an integer string). Only applied when the
	// current value is a string but the field's kind expects a different type
	// and parsing succeeds; unparseable strings are left as-is so the type
	// error is reported normally.
	Coerce        bool `protobuf:"varint,8,opt,name=coerce,proto3" json:"coerce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schema) Reset() {
	*x = Schema{}
	mi := &file_schemapb_schema_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema) ProtoMessage() {}

func (x *Schema) ProtoReflect() protoreflect.Message {
	mi := &file_schemapb_schema_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema.ProtoReflect.Descriptor instead.
func (*Schema) Descriptor() ([]byte, []int) {
	return file_schemapb_schema_proto_rawDescGZIP(), []int{0}
}

func (x *Schema) GetId() *SchemaIdentity {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Schema) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Schema) GetFields() []*Schema_Filed {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *Schema) GetRules() []*Schema_Filed_Rule {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *Schema) GetStrict() bool {
	if x != nil {
		return x.Strict
	}
	return false
}

func (x *Schema) GetMinProperties() uint64 {
	if x != nil && x.MinProperties != nil {
		return *x.MinProperties
	}
	return 0
}

func (x *Schema) GetMaxProperties() uint64 {
	if x != nil && x.MaxProperties != nil {
		return *x.MaxProperties
	}
	return 0
}

func (x *Schema) GetCoerce() bool {
	if x != nil {
		return x.Coerce
	}
	return false
}

// SchemaIdentity is the stable, system-assigned identity of a Schema. A Schema
// is addressed by this identity rather than a free-form name.
type SchemaIdentity struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Grouping namespace, e.g. a product or team. Optional.
	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Schema name, unique within its namespace. Required.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Schema version, e.g. "v1" or a semver string. Optional.
	Version       string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemaIdentity) Reset() {
	*x = SchemaIdentity{}
	mi := &file_schemapb_schema_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaIdentity) ProtoMessage() {}

func (x *SchemaIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_schemapb_schema_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaIdentity.ProtoReflect.Descriptor instead.
func (*SchemaIdentity) Descriptor() ([]byte, []int) {
	return file_schemapb_schema_proto_rawDescGZIP(), []int{1}
}

func (x *SchemaIdentity) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *SchemaIdentity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SchemaIdentity) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// FieldError is a single validation failure returned by the server-side
// validator (and reusable to render server errors on the client).
type FieldError struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Field name or dotted path that failed.
	Field string `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	// Human-readable failure message.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Id of the rule that failed, if any.
	RuleId *string `protobuf:"bytes,3,opt,name=rule_id,json=ruleId,proto3,oneof" json:"rule_id,omitempty"`
	// Severity of the failure.
	Severity Schema_Filed_Severity `protobuf:"varint,4,opt,name=severity,proto3,enum=schemapb.Schema_Filed_Severity" json:"severity,omitempty"`
	// Stable machine code identifying the kind of failure.
	Code string `protobuf:"bytes,5,opt,name=code,proto3" json:"code,omitempty"`
	// Template parameters for client-side i18n of the error message.
	Params        map[string]string `protobuf:"bytes,6,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldError) Reset() {
	*x = FieldError{}
	mi := &file_schemapb_schema_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldError) ProtoMessage() {}

func (x *FieldError) ProtoReflect() protoreflect.Message {
	mi := &file_schemapb_schema_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldError.ProtoReflect.Descriptor instead.
func (*FieldError) Descriptor() ([]byte, []int) {
	return file_schemapb_schema_proto_rawDescGZIP(), []int{2}
}

func (x *FieldError) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *FieldError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FieldError) GetRuleId() string {
	if x != nil && x.RuleId != nil {
		return *x.RuleId
	}
	return ""
}

func (x *FieldError) GetSeverity() Schema_Filed_Severity {
	if x != nil {
		return x.Severity
	}
	return Schema_Filed_SEVERITY_UNSPECIFIED
}

func (x *FieldError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *FieldError) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

// SchemaRef selects a schema: either inline, or by identity (resolved from a
// registry).
type SchemaRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Source:
	//
	//	*SchemaRef_Id
	//	*SchemaRef_Schema
	Source        isSchemaRef_Source `protobuf_oneof:"source"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemaRef) Reset() {
	*x = SchemaRef{}
	mi := &file_schemapb_schema_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaRef) ProtoMessage() {}

func (x *SchemaRef) ProtoReflect() protoreflect.Message {
	mi := &file_schemapb_schema_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaRef.ProtoReflect.Descriptor instead.
func (*SchemaRef) Descriptor() ([]byte, []int) {
	return file_schemapb_schema_proto_rawDescGZIP(), []int{3}
}

func (x *SchemaRef) GetSource() isSchemaRef_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *SchemaRef) GetId() *SchemaIdentity {
	if x != nil {
		if x, ok := x.Source.(*SchemaRef_Id); ok {
			return x.Id
		}
	}
	return nil
}

func (x *SchemaRef) GetSchema() *Schema {
	if x != nil {
		if x, ok := x.Source.(*SchemaRef_Schema); ok {
			return x.Schema
		}
	}
	return nil
}

type isSchemaRef_Source interface {
	isSchemaRef_Source()
}

type SchemaRef_Id struct {
	// Resolve a registered schema by identity.
	Id *SchemaIdentity `protobuf:"bytes,1,opt,name=id,proto3,oneof"`
}

type SchemaRef_Schema struct {
	// Use this schema directly, without registering it.
	Schema *Schema `protobuf:"bytes,2,opt,name=schema,proto3,oneof"`
}

func (*SchemaRef_Id) isSchemaRef_Source() {}

func (*SchemaRef_Schema) isSchemaRef_Source() {}

// Filled is a runtime form: a reference to the schema plus the values entered
// for it. The schema says what is allowed/derived; the values are what to
// check/resolve. It is mutable input (the thing being edited/validated).
type Filled struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Schema this form is filled against (baked-by-id or inline).
	Schema *SchemaRef `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	// Form values the expressions read and the validator checks.
	Values        *structpb.Struct `protobuf:"bytes,2,opt,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filled) Reset() {
	*x = Filled{}
	mi := &file_schemapb_schema_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filled) ProtoMessage() {}

func (x *Filled) ProtoReflect() protoreflect.Message {
	mi := &file_schemapb_schema_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filled.ProtoReflect.Descriptor instead.
func (*Filled) Descriptor() ([]byte, []int) {
	return file_schemapb_schema_proto_rawDescGZIP(), []int{4}
}

func (x *Filled) GetSchema() *SchemaRef {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *Filled) GetValues() *structpb.Struct {
	if x != nil {
		return x.Values
	}
	return nil
}

// Baked is a sealed result: the final values together with the schema they were
// validated and resolved against. It is a self-contained, immutable snapshot —
// "these exact values for this exact schema, not to be changed". Unlike Filled
// (which only references a schema and is mutable), Baked embeds the full schema
// and the frozen values, so it is portable and verifiable on its own.
type Baked struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The schema these values were baked against (embedded, self-contained).
	Schema *Schema `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	// The final, resolved values — frozen.
	Values        *structpb.Struct `protobuf:"bytes,2,opt,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Baked) Reset() {
	*x = Baked{}
	mi := &file_schemapb_schema_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Baked) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Baked) ProtoMessage() {}

func (x *Baked) ProtoReflect() protoreflect.Message {
	mi := &file_schemapb_schema_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Baked.ProtoReflect.Descriptor instead.
func (*Baked) Descriptor() ([]byte, []int) {
	return file_schemapb_schema_proto_rawDescGZIP(), []int{5}
}

func (x *Baked) GetSchema() *Schema {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *Baked) GetValues() *structpb.Struct {
	if x != nil {
		return x.Values
	}
	return nil
}

type Schema_Filed struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Field name; the key under which the value lives in the form.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Human description of the field.
	Description *string `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// If true, the value may be null/empty.
	Nullable bool `protobuf:"varint,3,opt,name=nullable,proto3" json:"nullable,omitempty"`
	// If true, the value must be present.
	Required bool `protobuf:"varint,4,opt,name=required,proto3" json:"required,omitempty"`
	// Cross-field CEL validation rules (`this` is bound to this field).
	Rules []*Schema_Filed_Rule `protobuf:"bytes,5,rep,name=rules,proto3" json:"rules,omitempty"`
	// If true, the value is system-fixed: it equals `default` and cannot be
	// changed. The validator forces it to `default` and rejects any
	// different submitted value; renderers show it disabled. A "system
	// value" is therefore immutable + default.
	Immutable bool `protobuf:"varint,20,opt,name=immutable,proto3" json:"immutable,omitempty"`
	// Informative section label for grouping fields (e.g. "WAL"). Purely
	// informative — the validation/compute engine ignores it.
	Group *string `protobuf:"bytes,21,opt,name=group,proto3,oneof" json:"group,omitempty"`
	// Informative unit of the value, e.g. "MB" or "ms". Purely informative —
	// the engine ignores it; it is for renderers/serializers.
	Unit *string `protobuf:"bytes,22,opt,name=unit,proto3,oneof" json:"unit,omitempty"`
	// Informative human title for the field. Purely informative — engine ignores it.
	Title *string `protobuf:"bytes,23,opt,name=title,proto3,oneof" json:"title,omitempty"`
	// If true, this field is deprecated; renderers may warn. Purely informative.
	Deprecated bool `protobuf:"varint,24,opt,name=deprecated,proto3" json:"deprecated,omitempty"`
	// Example values for documentation/rendering. Purely informative.
	Examples []*structpb.Value `protobuf:"bytes,25,rep,name=examples,proto3" json:"examples,omitempty"`
	// If true, the value is sensitive (e.g. a password). Purely informative.
	Secret bool `protobuf:"varint,26,opt,name=secret,proto3" json:"secret,omitempty"`
	// The field kind; exactly one must be set.
	// Types that are valid to be assigned to Kind:
	//
	//	*Schema_Filed_Float_
	//	*Schema_Filed_Double_
	//	*Schema_Filed_Int32_
	//	*Schema_Filed_Int64_
	//	*Schema_Filed_Uint32
	//	*Schema_Filed_Uint64
	//	*Schema_Filed_Bool_
	//	*Schema_Filed_String_
	//	*Schema_Filed_Enum_
	//	*Schema_Filed_Duration_
	//	*Schema_Filed_Timestamp_
	//	*Schema_Filed_List_
	//	*Schema_Filed_Object_
	//	*Schema_Filed_Computed_
	Kind          isSchema_Filed_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schema_Filed) Reset() {
	*x = Schema_Filed{}
	mi := &file_schemapb_schema_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schema_Filed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema_Filed) ProtoMessage() {}

func (x *Schema_Filed) ProtoReflect() protoreflect.Message {
	mi := &file_schemapb_schema_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema_Filed.ProtoReflect.Descriptor instead.
func (*Schema_Filed) Descriptor() ([]byte, []int) {
	return file_schemapb_schema_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Schema_Filed) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Schema_Filed) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Schema_Filed) GetNullable() bool {
	if x != nil {
		return x.Nullable
	}
	return false
}

func (x *Schema_Filed) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *Schema_Filed) GetRules() []*Schema_Filed_Rule {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *Schema_Filed) GetImmutable() bool {
	if x != nil {
		return x.Immutable
	}
	return false
}

func (x *Schema_Filed) GetGroup() string {
	if x != nil && x.Group != nil {
		return *x.Group
	}
	return ""
}

func (x *Schema_Filed) GetUnit() string {
	if x != nil && x.Unit != nil {
		return *x.Unit
	}
	return ""
}

func (x *Schema_Filed) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *Schema_Filed) GetDeprecated() bool {
	if x != nil {
		return x.Deprecated
	}
	return false
}

func (x *Schema_Filed) GetExamples() []*structpb.Value {
	if x != nil {
		return x.Examples
	}
	return nil
}

func (x *Schema_Filed) GetSecret() bool {
	if x != nil {
		return x.Secret
	}
	return false
}

func (x *Schema_Filed) GetKind() isSchema_Filed_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Schema_Filed) GetFloat() *Schema_Filed_Float {
	if x != nil {
		if x, ok := x.Kind.(*Schema_Filed_Float_); ok {
			return x.Float
		}
	}
	return nil
}

func (x *Schema_Filed) GetDouble() *Schema_Filed_Double {
	if x != nil {
		if x, ok := x.Kind.(*Schema_Filed_Double_); ok {
			return x.Double
		}
	}
	return nil
}

func (x *Schema_Filed) GetInt32() *Schema_Filed_Int32 {
	if x != nil {
		if x, ok := x.Kind.(*Schema_Filed_Int32_); ok {
			return x.Int32
		}
	}
	return nil
}

func (x *Schema_Filed) GetInt64() *Schema_Filed_Int64 {
	if x != nil {
		if x, ok := x.Kind.(*Schema_Filed_Int64_); ok {
			return x.Int64
		}
	}
	return nil
}

func (x *Schema_Filed) GetUint32() *Schema_Filed_UInt32 {
	if x != nil {
		if x, ok := x.Kind.(*Schema_Filed_Uint32); ok {
			return x.Uint32
		}
	}
	return nil
}

func (x *Schema_Filed) GetUint64() *Schema_Filed_UInt64 {
	if x != nil {
		if x, ok := x.Kind.(*Schema_Filed_Uint64); ok {
			return x.Uint64
		}
	}
	return nil
}

func (x *Schema_Filed) GetBool() *Schema_Filed_Bool {
	if x != nil {
		if x, ok := x.Kind.(*Schema_Filed_Bool_); ok {
			return x.Bool
		}
	}
	return nil
}

func (x *Schema_Filed) GetString_() *Schema_Filed_String {
	if x != nil {
		if x, ok := x.Kind.(*Schema_Filed_String_); ok {
			return x.String_
		}
	}
	return nil
}

func (x *Schema_Filed) GetEnum() *Schema_Filed_Enum {
	if x != nil {
		if x, ok := x.Kind.(*Schema_Filed_Enum_); ok {
			return x.Enum
		}
	}
	return nil
}

func (x *Schema_Filed) GetDuration() *Schema_Filed_Duration {
	if x != nil {
		if x, ok := x.Kind.(*Schema_Filed_Duration_); ok {
			return x.Duration
		}
	}
	return nil
}

func (x *Schema_Filed) GetTimestamp() *Schema_Filed_Timestamp {
	if x != nil {
		if x, ok := x.Kind.(*Schema_Filed_Timestamp_); ok {
			return x.Timestamp
		}
	}
	return nil
}

func (x *Schema_Filed) GetList() *Schema_Filed_List {
	if x != nil {
		if x, ok := x.Kind.(*Schema_Filed_List_); ok {
			return x.List
		}
	}
	return nil
}

func (x *Schema_Filed) GetObject() *Schema_Filed_Object {
	if x != nil {
		if x, ok := x.Kind.(*Schema_Filed_Object_); ok {
			return x.Object
		}
	}
	return nil
}

func (x *Schema_Filed) GetComputed() *Schema_Filed_Computed {
	if x != nil {
		if x, ok := x.Kind.(*Schema_Filed_Computed_); ok {
			return x.Computed
		}
	}
	return nil
}

type isSchema_Filed_Kind interface {
	isSchema_Filed_Kind()
}

type Schema_Filed_Float_ struct {
	// Float field.
	Float *Schema_Filed_Float `protobuf:"bytes,6,opt,name=float,proto3,oneof"`
}

type Schema_Filed_Double_ struct {
	// Double field.
	Double *Schema_Filed_Double `protobuf:"bytes,7,opt,name=double,proto3,oneof"`
}

type Schema_Filed_Int32_ struct {
	// Int32 field.
	Int32 *Schema_Filed_Int32 `protobuf:"bytes,8,opt,name=int32,proto3,oneof"`
}

type Schema_Filed_Int64_ struct {
	// Int64 field.
	Int64 *Schema_Filed_Int64 `protobuf:"bytes,9,opt,name=int64,proto3,oneof"`
}

type Schema_Filed_Uint32 struct {
	// UInt32 field.
	Uint32 *Schema_Filed_UInt32 `protobuf:"bytes,10,opt,name=uint32,proto3,oneof"`
}

type Schema_Filed_Uint64 struct {
	// UInt64 field.
	Uint64 *Schema_Filed_UInt64 `protobuf:"bytes,11,opt,name=uint64,proto3,oneof"`
}

type Schema_Filed_Bool_ struct {
	// Bool field.
	Bool *Schema_Filed_Bool `protobuf:"bytes,12,opt,name=bool,proto3,oneof"`
}

type Schema_Filed_String_ struct {
	// String field.
	String_ *Schema_Filed_String `protobuf:"bytes,13,opt,name=string,proto3,oneof"`
}

type Schema_Filed_Enum_ struct {
	// Enum field.
	Enum *Schema_Filed_Enum `protobuf:"bytes,14,opt,name=enum,proto3,oneof"`
}

type Schema_Filed_Duration_ struct {
	// Duration field.
	Duration *Schema_Filed_Duration `protobuf:"bytes,15,opt,name=duration,proto3,oneof"`
}

type Schema_Filed_Timestamp_ struct {
	// Timestamp field.
	Timestamp *Schema_Filed_Timestamp `protobuf:"bytes,16,opt,name=timestamp,proto3,oneof"`
}

type Schema_Filed_List_ struct {
	// List field.
	List *Schema_Filed_List `protobuf:"bytes,17,opt,name=list,proto3,oneof"`
}

type Schema_Filed_Object_ struct {
	// Nested object field.
	Object *Schema_Filed_Object `protobuf:"bytes,18,opt,name=object,proto3,oneof"`
}

type Schema_Filed_Computed_ struct {
	// Computed (derived) field.
	Computed *Schema_Filed_Computed `protobuf:"bytes,19,opt,name=computed,proto3,oneof"`
}

func (*Schema_Filed_Float_) isSchema_Filed_Kind() {}

func (*Schema_Filed_Double_) isSchema_Filed_Kind() {}

func (*Schema_Filed_Int32_) isSchema_Filed_Kind() {}

func (*Schema_Filed_Int64_) isSchema_Filed_Kind() {}

func (*Schema_Filed_Uint32) isSchema_Filed_Kind() {}

func (*Schema_Filed_Uint64) isSchema_Filed_Kind() {}

func (*Schema_Filed_Bool_) isSchema_Filed_Kind() {}

func (*Schema_Filed_String_) isSchema_Filed_Kind() {}

func (*Schema_Filed_Enum_) isSchema_Filed_Kind() {}

func (*Schema_Filed_Duration_) isSchema_Filed_Kind() {}

func (*Schema_Filed_Timestamp_) isSchema_Filed_Kind() {}

func (*Schema_Filed_List_) isSchema_Filed_Kind() {}

func (*Schema_Filed_Object_) isSchema_Filed_Kind() {}

func (*Schema_Filed_Computed_) isSchema_Filed_Kind() {}

// Float field kind and its single-field constraints.
// gt = exclusive min (> 0), gte = inclusive min (>= 1).
// lt = exclusive max, lte = inclusive max.
type Schema_Filed_Float struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Default value used when the field is unset.
	Default *float32 `protobuf:"fixed32,1,opt,name=default,proto3,oneof" json:"default,omitempty"`
	// Value must equal exactly this.
	Const *float32 `protobuf:"fixed32,2,opt,name=const,proto3,oneof" json:"const,omitempty"`
	// Exclusive minimum: value > gt.
	Gt *float32 `protobuf:"fixed32,3,opt,name=gt,proto3,oneof" json:"gt,omitempty"`
	// Inclusive minimum: value >= gte.
	Gte *float32 `protobuf:"fixed32,4,opt,name=gte,proto3,oneof" json:"gte,omitempty"`
	// Exclusive maximum: value < lt.
	Lt *float32 `protobuf:"fixed32,5,opt,name=lt,proto3,oneof" json:"lt,omitempty"`
	// Inclusive maximum: value <= lte.
	Lte *float32 `protobuf:"fixed32,6,opt,name=lte,proto3,oneof" json:"lte,omitempty"`
	// Value must be one of these.
	In []float32 `protobuf:"fixed32,7,rep,packed,name=in,proto3" json:"in,omitempty"`
	// Value must not be any of these.
	NotIn []float32 `protobuf:"fixed32,8,rep,packed,name=not_in,json=notIn,proto3" json:"not_in,omitempty"`
	// Divisibility: quotient value/multiple_of must be whole.
	MultipleOf    *float32 `protobuf:"fixed32,9,opt,name=multiple_of,json=multipleOf,proto3,oneof" json:"multiple_of,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schema_Filed_Float) Reset() {
	*x = Schema_Filed_Float{}
	mi := &file_schemapb_schema_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schema_Filed_Float) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema_Filed_Float) ProtoMessage() {}

func (x *Schema_Filed_Float) ProtoReflect() protoreflect.Message {
	mi := &file_schemapb_schema_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema_Filed_Float.ProtoReflect.Descriptor instead.
func (*Schema_Filed_Float) Descriptor() ([]byte, []int) {
	return file_schemapb_schema_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *Schema_Filed_Float) GetDefault() float32 {
	if x != nil && x.Default != nil {
		return *x.Default
	}
	return 0
}

func (x *Schema_Filed_Float) GetConst() float32 {
	if x != nil && x.Const != nil {
		return *x.Const
	}
	return 0
}

func (x *Schema_Filed_Float) GetGt() float32 {
	if x != nil && x.Gt != nil {
		return *x.Gt
	}
	return 0
}

func (x *Schema_Filed_Float) GetGte() float32 {
	if x != nil && x.Gte != nil {
		return *x.Gte
	}
	return 0
}

func (x *Schema_Filed_Float) GetLt() float32 {
	if x != nil && x.Lt != nil {
		return *x.Lt
	}
	return 0
}

func (x *Schema_Filed_Float) GetLte() float32 {
	if x != nil && x.Lte != nil {
		return *x.Lte
	}
	return 0
}

func (x *Schema_Filed_Float) GetIn() []float32 {
	if x != nil {
		return x.In
	}
	return nil
}

func (x *Schema_Filed_Float) GetNotIn() []float32 {
	if x != nil {
		return x.NotIn
	}
	return nil
}

func (x *Schema_Filed_Float) GetMultipleOf() float32 {
	if x != nil && x.MultipleOf != nil {
		return *x.MultipleOf
	}
	return 0
}

// Double field kind and its single-field constraints.
type Schema_Filed_Double struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Default value used when the field is unset.
	Default *float64 `protobuf:"fixed64,1,opt,name=default,proto3,oneof" json:"default,omitempty"`
	// Value must equal exactly this.
	Const *float64 `protobuf:"fixed64,2,opt,name=const,proto3,oneof" json:"const,omitempty"`
	// Exclusive minimum: value > gt.
	Gt *float64 `protobuf:"fixed64,3,opt,name=gt,proto3,oneof" json:"gt,omitempty"`
	// Inclusive minimum: value >= gte.
	Gte *float64 `protobuf:"fixed64,4,opt,name=gte,proto3,oneof" json:"gte,omitempty"`
	// Exclusive maximum: value < lt.
	Lt *float64 `protobuf:"fixed64,5,opt,name=lt,proto3,oneof" json:"lt,omitempty"`
	// Inclusive maximum: value <= lte.
	Lte *float64 `protobuf:"fixed64,6,opt,name=lte,proto3,oneof" json:"lte,omitempty"`
	// Value must be one of these.
	In []float64 `protobuf:"fixed64,7,rep,packed,name=in,proto3" json:"in,omitempty"`
	// Value must not be any of these.
	NotIn []float64 `protobuf:"fixed64,8,rep,packed,name=not_in,json=notIn,proto3" json:"not_in,omitempty"`
	// Divisibility: quotient value/multiple_of must be whole.
	MultipleOf    *float64 `protobuf:"fixed64,9,opt,name=multiple_of,json=multipleOf,proto3,oneof" json:"multiple_of,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schema_Filed_Double) Reset() {
	*x = Schema_Filed_Double{}
	mi := &file_schemapb_schema_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schema_Filed_Double) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema_Filed_Double) ProtoMessage() {}

func (x *Schema_Filed_Double) ProtoReflect() protoreflect.Message {
	mi := &file_schemapb_schema_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema_Filed_Double.ProtoReflect.Descriptor instead.
func (*Schema_Filed_Double) Descriptor() ([]byte, []int) {
	return file_schemapb_schema_proto_rawDescGZIP(), []int{0, 0, 1}
}

func (x *Schema_Filed_Double) GetDefault() float64 {
	if x != nil && x.Default != nil {
		return *x.Default
	}
	return 0
}

func (x *Schema_Filed_Double) GetConst() float64 {
	if x != nil && x.Const != nil {
		return *x.Const
	}
	return 0
}

func (x *Schema_Filed_Double) GetGt() float64 {
	if x != nil && x.Gt != nil {
		return *x.Gt
	}
	return 0
}

func (x *Schema_Filed_Double) GetGte() float64 {
	if x != nil && x.Gte != nil {
		return *x.Gte
	}
	return 0
}

func (x *Schema_Filed_Double) GetLt() float64 {
	if x != nil && x.Lt != nil {
		return *x.Lt
	}
	return 0
}

func (x *Schema_Filed_Double) GetLte() float64 {
	if x != nil && x.Lte != nil {
		return *x.Lte
	}
	return 0
}

func (x *Schema_Filed_Double) GetIn() []float64 {
	if x != nil {
		return x.In
	}
	return nil
}

func (x *Schema_Filed_Double) GetNotIn() []float64 {
	if x != nil {
		return x.NotIn
	}
	return nil
}

func (x *Schema_Filed_Double) GetMultipleOf() float64 {
	if x != nil && x.MultipleOf != nil {
		return *x.MultipleOf
	}
	return 0
}

// Int32 field kind and its single-field constraints.
type Schema_Filed_Int32 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Default value used when the field is unset.
	Default *int32 `protobuf:"varint,1,opt,name=default,proto3,oneof" json:"default,omitempty"`
	// Value must equal exactly this.
	Const *int32 `protobuf:"varint,2,opt,name=const,proto3,oneof" json:"const,omitempty"`
	// Exclusive minimum: value > gt.
	Gt *int32 `protobuf:"varint,3,opt,name=gt,proto3,oneof" json:"gt,omitempty"`
	// Inclusive minimum: value >= gte.
	Gte *int32 `protobuf:"varint,4,opt,name=gte,proto3,oneof" json:"gte,omitempty"`
	// Exclusive maximum: value < lt.
	Lt *int32 `protobuf:"varint,5,opt,name=lt,proto3,oneof" json:"lt,omitempty"`
	// Inclusive maximum: value <= lte.
	Lte *int32 `protobuf:"varint,6,opt,name=lte,proto3,oneof" json:"lte,omitempty"`
	// Value must be one of these.
	In []int32 `protobuf:"varint,7,rep,packed,name=in,proto3" json:"in,omitempty"`
	// Value must not be any of these.
	NotIn []int32 `protobuf:"varint,8,rep,packed,name=not_in,json=notIn,proto3" json:"not_in,omitempty"`
	// Divisibility: value % multiple_of must be 0.
	MultipleOf    *int32 `protobuf:"varint,9,opt,name=multiple_of,json=multipleOf,proto3,oneof" json:"multiple_of,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schema_Filed_Int32) Reset() {
	*x = Schema_Filed_Int32{}
	mi := &file_schemapb_schema_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schema_Filed_Int32) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema_Filed_Int32) ProtoMessage() {}

func (x *Schema_Filed_Int32) ProtoReflect() protoreflect.Message {
	mi := &file_schemapb_schema_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema_Filed_Int32.ProtoReflect.Descriptor instead.
func (*Schema_Filed_Int32) Descriptor() ([]byte, []int) {
	return file_schemapb_schema_proto_rawDescGZIP(), []int{0, 0, 2}
}

func (x *Schema_Filed_Int32) GetDefault() int32 {
	if x != nil && x.Default != nil {
		return *x.Default
	}
	return 0
}

func (x *Schema_Filed_Int32) GetConst() int32 {
	if x != nil && x.Const != nil {
		return *x.Const
	}
	return 0
}

func (x *Schema_Filed_Int32) GetGt() int32 {
	if x != nil && x.Gt != nil {
		return *x.Gt
	}
	return 0
}

func (x *Schema_Filed_Int32) GetGte() int32 {
	if x != nil && x.Gte != nil {
		return *x.Gte
	}
	return 0
}

func (x *Schema_Filed_Int32) GetLt() int32 {
	if x != nil && x.Lt != nil {
		return *x.Lt
	}
	return 0
}

func (x *Schema_Filed_Int32) GetLte() int32 {
	if x != nil && x.Lte != nil {
		return *x.Lte
	}
	return 0
}

func (x *Schema_Filed_Int32) GetIn() []int32 {
	if x != nil {
		return x.In
	}
	return nil
}

func (x *Schema_Filed_Int32) GetNotIn() []int32 {
	if x != nil {
		return x.NotIn
	}
	return nil
}

func (x *Schema_Filed_Int32) GetMultipleOf() int32 {
	if x != nil && x.MultipleOf != nil {
		return *x.MultipleOf
	}
	return 0
}

// Int64 field kind and its single-field constraints.
type Schema_Filed_Int64 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Default value used when the field is unset.
	Default *int64 `protobuf:"varint,1,opt,name=default,proto3,oneof" json:"default,omitempty"`
	// Value must equal exactly this.
	Const *int64 `protobuf:"varint,2,opt,name=const,proto3,oneof" json:"const,omitempty"`
	// Exclusive minimum: value > gt.
	Gt *int64 `protobuf:"varint,3,opt,name=gt,proto3,oneof" json:"gt,omitempty"`
	// Inclusive minimum: value >= gte.
	Gte *int64 `protobuf:"varint,4,opt,name=gte,proto3,oneof" json:"gte,omitempty"`
	// Exclusive maximum: value < lt.
	Lt *int64 `protobuf:"varint,5,opt,name=lt,proto3,oneof" json:"lt,omitempty"`
	// Inclusive maximum: value <= lte.
	Lte *int64 `protobuf:"varint,6,opt,name=lte,proto3,oneof" json:"lte,omitempty"`
	// Value must be one of these.
	In []int64 `protobuf:"varint,7,rep,packed,name=in,proto3" json:"in,omitempty"`
	// Value must not be any of these.
	NotIn []int64 `protobuf:"varint,8,rep,packed,name=not_in,json=notIn,proto3" json:"not_in,omitempty"`
	// Divisibility: value % multiple_of must be 0.
	MultipleOf    *int64 `protobuf:"varint,9,opt,name=multiple_of,json=multipleOf,proto3,oneof" json:"multiple_of,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schema_Filed_Int64) Reset() {
	*x = Schema_Filed_Int64{}
	mi := &file_schemapb_schema_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schema_Filed_Int64) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema_Filed_Int64) ProtoMessage() {}

func (x *Schema_Filed_Int64) ProtoReflect() protoreflect.Message {
	mi := &file_schemapb_schema_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema_Filed_Int64.ProtoReflect.Descriptor instead.
func (*Schema_Filed_Int64) Descriptor() ([]byte, []int) {
	return file_schemapb_schema_proto_rawDescGZIP(), []int{0, 0, 3}
}

func (x *Schema_Filed_Int64) GetDefault() int64 {
	if x != nil && x.Default != nil {
		return *x.Default
	}
	return 0
}

func (x *Schema_Filed_Int64) GetConst() int64 {
	if x != nil && x.Const != nil {
		return *x.Const
	}
	return 0
}

func (x *Schema_Filed_Int64) GetGt() int64 {
	if x != nil && x.Gt != nil {
		return *x.Gt
	}
	return 0
}

func (x *Schema_Filed_Int64) GetGte() int64 {
	if x != nil && x.Gte != nil {
		return *x.Gte
	}
	return 0
}

func (x *Schema_Filed_Int64) GetLt() int64 {
	if x != nil && x.Lt != nil {
		return *x.Lt
	}
	return 0
}

func (x *Schema_Filed_Int64) GetLte() int64 {
	if x != nil && x.Lte != nil {
		return *x.Lte
	}
	return 0
}

func (x *Schema_Filed_Int64) GetIn() []int64 {
	if x != nil {
		return x.In
	}
	return nil
}

func (x *Schema_Filed_Int64) GetNotIn() []int64 {
	if x != nil {
		return x.NotIn
	}
	return nil
}

func (x *Schema_Filed_Int64) GetMultipleOf() int64 {
	if x != nil && x.MultipleOf != nil {
		return *x.MultipleOf
	}
	return 0
}

// UInt32 field kind and its single-field constraints.
type Schema_Filed_UInt32 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Default value used when the field is unset.
	Default *uint32 `protobuf:"varint,1,opt,name=default,proto3,oneof" json:"default,omitempty"`
	// Value must equal exactly this.
	Const *uint32 `protobuf:"varint,2,opt,name=const,proto3,oneof" json:"const,omitempty"`
	// Exclusive minimum: value > gt.
	Gt *uint32 `protobuf:"varint,3,opt,name=gt,proto3,oneof" json:"gt,omitempty"`
	// Inclusive minimum: value >= gte.
	Gte *uint32 `protobuf:"varint,4,opt,name=gte,proto3,oneof" json:"gte,omitempty"`
	// Exclusive maximum: value < lt.
	Lt *uint32 `protobuf:"varint,5,opt,name=lt,proto3,oneof" json:"lt,omitempty"`
	// Inclusive maximum: value <= lte.
	Lte *uint32 `protobuf:"varint,6,opt,name=lte,proto3,oneof" json:"lte,omitempty"`
	// Value must be one of these.
	In []uint32 `protobuf:"varint,7,rep,packed,name=in,proto3" json:"in,omitempty"`
	// Value must not be any of these.
	NotIn []uint32 `protobuf:"varint,8,rep,packed,name=not_in,json=notIn,proto3" json:"not_in,omitempty"`
	// Divisibility: value % multiple_of must be 0.
	MultipleOf    *uint32 `protobuf:"varint,9,opt,name=multiple_of,json=multipleOf,proto3,oneof" json:"multiple_of,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schema_Filed_UInt32) Reset() {
	*x = Schema_Filed_UInt32{}
	mi := &file_schemapb_schema_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schema_Filed_UInt32) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema_Filed_UInt32) ProtoMessage() {}

func (x *Schema_Filed_UInt32) ProtoReflect() protoreflect.Message {
	mi := &file_schemapb_schema_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema_Filed_UInt32.ProtoReflect.Descriptor instead.
func (*Schema_Filed_UInt32) Descriptor() ([]byte, []int) {
	return file_schemapb_schema_proto_rawDescGZIP(), []int{0, 0, 4}
}

func (x *Schema_Filed_UInt32) GetDefault() uint32 {
	if x != nil && x.Default != nil {
		return *x.Default
	}
	return 0
}

func (x *Schema_Filed_UInt32) GetConst() uint32 {
	if x != nil && x.Const != nil {
		return *x.Const
	}
	return 0
}

func (x *Schema_Filed_UInt32) GetGt() uint32 {
	if x != nil && x.Gt != nil {
		return *x.Gt
	}
	return 0
}

func (x *Schema_Filed_UInt32) GetGte() uint32 {
	if x != nil && x.Gte != nil {
		return *x.Gte
	}
	return 0
}

func (x *Schema_Filed_UInt32) GetLt() uint32 {
	if x != nil && x.Lt != nil {
		return *x.Lt
	}
	return 0
}

func (x *Schema_Filed_UInt32) GetLte() uint32 {
	if x != nil && x.Lte != nil {
		return *x.Lte
	}
	return 0
}

func (x *Schema_Filed_UInt32) GetIn() []uint32 {
	if x != nil {
		return x.In
	}
	return nil
}

func (x *Schema_Filed_UInt32) GetNotIn() []uint32 {
	if x != nil {
		return x.NotIn
	}
	return nil
}

func (x *Schema_Filed_UInt32) GetMultipleOf() uint32 {
	if x != nil && x.MultipleOf != nil {
		return *x.MultipleOf
	}
	return 0
}

// UInt64 field kind and its single-field constraints.
type Schema_Filed_UInt64 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Default value used when the field is unset.
	Default *uint64 `protobuf:"varint,1,opt,name=default,proto3,oneof" json:"default,omitempty"`
	// Value must equal exactly this.
	Const *uint64 `protobuf:"varint,2,opt,name=const,proto3,oneof" json:"const,omitempty"`
	// Exclusive minimum: value > gt.
	Gt *uint64 `protobuf:"varint,3,opt,name=gt,proto3,oneof" json:"gt,omitempty"`
	// Inclusive minimum: value >= gte.
	Gte *uint64 `protobuf:"varint,4,opt,name=gte,proto3,oneof" json:"gte,omitempty"`
	// Exclusive maximum: value < lt.
	Lt *uint64 `protobuf:"varint,5,opt,name=lt,proto3,oneof" json:"lt,omitempty"`
	// Inclusive maximum: value <= lte.
	Lte *uint64 `protobuf:"varint,6,opt,name=lte,proto3,oneof" json:"lte,omitempty"`
	// Value must be one of these.
	In []uint64 `protobuf:"varint,7,rep,packed,name=in,proto3" json:"in,omitempty"`
	// Value must not be any of these.
	NotIn []uint64 `protobuf:"varint,8,rep,packed,name=not_in,json=notIn,proto3" json:"not_in,omitempty"`
	// Divisibility: value % multiple_of must be 0.
	MultipleOf    *uint64 `protobuf:"varint,9,opt,name=multiple_of,json=multipleOf,proto3,oneof" json:"multiple_of,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schema_Filed_UInt64) Reset() {
	*x = Schema_Filed_UInt64{}
	mi := &file_schemapb_schema_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schema_Filed_UInt64) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema_Filed_UInt64) ProtoMessage() {}

func (x *Schema_Filed_UInt64) ProtoReflect() protoreflect.Message {
	mi := &file_schemapb_schema_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema_Filed_UInt64.ProtoReflect.Descriptor instead.
func (*Schema_Filed_UInt64) Descriptor() ([]byte, []int) {
	return file_schemapb_schema_proto_rawDescGZIP(), []int{0, 0, 5}
}

func (x *Schema_Filed_UInt64) GetDefault() uint64 {
	if x != nil && x.Default != nil {
		return *x.Default
	}
	return 0
}

func (x *Schema_Filed_UInt64) GetConst() uint64 {
	if x != nil && x.Const != nil {
		return *x.Const
	}
	return 0
}

func (x *Schema_Filed_UInt64) GetGt() uint64 {
	if x != nil && x.Gt != nil {
		return *x.Gt
	}
	return 0
}

func (x *Schema_Filed_UInt64) GetGte() uint64 {
	if x != nil && x.Gte != nil {
		return *x.Gte
	}
	return 0
}

func (x *Schema_Filed_UInt64) GetLt() uint64 {
	if x != nil && x.Lt != nil {
		return *x.Lt
	}
	return 0
}

func (x *Schema_Filed_UInt64) GetLte() uint64 {
	if x != nil && x.Lte != nil {
		return *x.Lte
	}
	return 0
}

func (x *Schema_Filed_UInt64) GetIn() []uint64 {
	if x != nil {
		return x.In
	}
	return nil
}

func (x *Schema_Filed_UInt64) GetNotIn() []uint64 {
	if x != nil {
		return x.NotIn
	}
	return nil
}

func (x *Schema_Filed_UInt64) GetMultipleOf() uint64 {
	if x != nil && x.MultipleOf != nil {
		return *x.MultipleOf
	}
	return 0
}

// Bool field kind.
type Schema_Filed_Bool struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Default value used when the field is unset.
	Default *bool `protobuf:"varint,1,opt,name=default,proto3,oneof" json:"default,omitempty"`
	// Value must equal exactly this.
	Const         *bool `protobuf:"varint,2,opt,name=const,proto3,oneof" json:"const,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schema_Filed_Bool) Reset() {
	*x = Schema_Filed_Bool{}
	mi := &file_schemapb_schema_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schema_Filed_Bool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema_Filed_Bool) ProtoMessage() {}

func (x *Schema_Filed_Bool) ProtoReflect() protoreflect.Message {
	mi := &file_schemapb_schema_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema_Filed_Bool.ProtoReflect.Descriptor instead.
func (*Schema_Filed_Bool) Descriptor() ([]byte, []int) {
	return file_schemapb_schema_proto_rawDescGZIP(), []int{0, 0, 6}
}

func (x *Schema_Filed_Bool) GetDefault() bool {
	if x != nil && x.Default != nil {
		return *x.Default
	}
	return false
}

func (x *Schema_Filed_Bool) GetConst() bool {
	if x != nil && x.Const != nil {
		return *x.Const
	}
	return false
}

// String field kind and its single-field constraints.
type Schema_Filed_String struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Default value used when the field is unset.
	Default *string `protobuf:"bytes,1,opt,name=default,proto3,oneof" json:"default,omitempty"`
	// Value must equal exactly this.
	Const *string `protobuf:"bytes,2,opt,name=const,proto3,oneof" json:"const,omitempty"`
	// Exact character length required.
	Len *uint64 `protobuf:"varint,3,opt,name=len,proto3,oneof" json:"len,omitempty"`
	// Minimum character length.
	MinLen *uint64 `protobuf:"varint,4,opt,name=min_len,json=minLen,proto3,oneof" json:"min_len,omitempty"`
	// Maximum character length.
	MaxLen *uint64 `protobuf:"varint,5,opt,name=max_len,json=maxLen,proto3,oneof" json:"max_len,omitempty"`
	// RE2 regular expression the value must match.
	Pattern *string `protobuf:"bytes,6,opt,name=pattern,proto3,oneof" json:"pattern,omitempty"`
	// Value must be one of these.
	In []string `protobuf:"bytes,7,rep,name=in,proto3" json:"in,omitempty"`
	// Value must not be any of these.
	NotIn []string `protobuf:"bytes,8,rep,name=not_in,json=notIn,proto3" json:"not_in,omitempty"`
	// Semantic format the value must conform to.
	Format        *Schema_Filed_String_StringFormat `protobuf:"varint,9,opt,name=format,proto3,enum=schemapb.Schema_Filed_String_StringFormat,oneof" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schema_Filed_String) Reset() {
	*x = Schema_Filed_String{}
	mi := &file_schemapb_schema_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schema_Filed_String) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema_Filed_String) ProtoMessage() {}

func (x *Schema_Filed_String) ProtoReflect() protoreflect.Message {
	mi := &file_schemapb_schema_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema_Filed_String.ProtoReflect.Descriptor instead.
func (*Schema_Filed_String) Descriptor() ([]byte, []int) {
	return file_schemapb_schema_proto_rawDescGZIP(), []int{0, 0, 7}
}

func (x *Schema_Filed_String) GetDefault() string {
	if x != nil && x.Default != nil {
		return *x.Default
	}
	return ""
}

func (x *Schema_Filed_String) GetConst() string {
	if x != nil && x.Const != nil {
		return *x.Const
	}
	return ""
}

func (x *Schema_Filed_String) GetLen() uint64 {
	if x != nil && x.Len != nil {
		return *x.Len
	}
	return 0
}

func (x *Schema_Filed_String) GetMinLen() uint64 {
	if x != nil && x.MinLen != nil {
		return *x.MinLen
	}
	return 0
}

func (x *Schema_Filed_String) GetMaxLen() uint64 {
	if x != nil && x.MaxLen != nil {
		return *x.MaxLen
	}
	return 0
}

func (x *Schema_Filed_String) GetPattern() string {
	if x != nil && x.Pattern != nil {
		return *x.Pattern
	}
	return ""
}

func (x *Schema_Filed_String) GetIn() []string {
	if x != nil {
		return x.In
	}
	return nil
}

func (x *Schema_Filed_String) GetNotIn() []string {
	if x != nil {
		return x.NotIn
	}
	return nil
}

func (x *Schema_Filed_String) GetFormat() Schema_Filed_String_StringFormat {
	if x != nil && x.Format != nil {
		return *x.Format
	}
	return Schema_Filed_String_STRING_FORMAT_UNSPECIFIED
}

// Enum field kind: an integer value with human labels.
type Schema_Filed_Enum struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Default value used when the field is unset.
	Default *int32 `protobuf:"varint,1,opt,name=default,proto3,oneof" json:"default,omitempty"`
	// Allowed enum values: integer -> human label.
	Values map[int32]string `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// If true, value must be one of the keys in values.
	DefinedOnly bool `protobuf:"varint,3,opt,name=defined_only,json=definedOnly,proto3" json:"defined_only,omitempty"`
	// Value must be one of these.
	In []int32 `protobuf:"varint,4,rep,packed,name=in,proto3" json:"in,omitempty"`
	// Value must not be any of these.
	NotIn         []int32 `protobuf:"varint,5,rep,packed,name=not_in,json=notIn,proto3" json:"not_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schema_Filed_Enum) Reset() {
	*x = Schema_Filed_Enum{}
	mi := &file_schemapb_schema_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schema_Filed_Enum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema_Filed_Enum) ProtoMessage() {}

func (x *Schema_Filed_Enum) ProtoReflect() protoreflect.Message {
	mi := &file_schemapb_schema_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema_Filed_Enum.ProtoReflect.Descriptor instead.
func (*Schema_Filed_Enum) Descriptor() ([]byte, []int) {
	return file_schemapb_schema_proto_rawDescGZIP(), []int{0, 0, 8}
}

func (x *Schema_Filed_Enum) GetDefault() int32 {
	if x != nil && x.Default != nil {
		return *x.Default
	}
	return 0
}

func (x *Schema_Filed_Enum) GetValues() map[int32]string {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *Schema_Filed_Enum) GetDefinedOnly() bool {
	if x != nil {
		return x.DefinedOnly
	}
	return false
}

func (x *Schema_Filed_Enum) GetIn() []int32 {
	if x != nil {
		return x.In
	}
	return nil
}

func (x *Schema_Filed_Enum) GetNotIn() []int32 {
	if x != nil {
		return x.NotIn
	}
	return nil
}

// Duration field kind with optional range bounds.
type Schema_Filed_Duration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Default value used when the field is unset.
	Default *durationpb.Duration `protobuf:"bytes,1,opt,name=default,proto3,oneof" json:"default,omitempty"`
	// Exclusive minimum: value > gt.
	Gt *durationpb.Duration `protobuf:"bytes,2,opt,name=gt,proto3,oneof" json:"gt,omitempty"`
	// Inclusive minimum: value >= gte.
	Gte *durationpb.Duration `protobuf:"bytes,3,opt,name=gte,proto3,oneof" json:"gte,omitempty"`
	// Exclusive maximum: value < lt.
	Lt *durationpb.Duration `protobuf:"bytes,4,opt,name=lt,proto3,oneof" json:"lt,omitempty"`
	// Inclusive maximum: value <= lte.
	Lte           *durationpb.Duration `protobuf:"bytes,5,opt,name=lte,proto3,oneof" json:"lte,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schema_Filed_Duration) Reset() {
	*x = Schema_Filed_Duration{}
	mi := &file_schemapb_schema_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schema_Filed_Duration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema_Filed_Duration) ProtoMessage() {}

func (x *Schema_Filed_Duration) ProtoReflect() protoreflect.Message {
	mi := &file_schemapb_schema_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema_Filed_Duration.ProtoReflect.Descriptor instead.
func (*Schema_Filed_Duration) Descriptor() ([]byte, []int) {
	return file_schemapb_schema_proto_rawDescGZIP(), []int{0, 0, 9}
}

func (x *Schema_Filed_Duration) GetDefault() *durationpb.Duration {
	if x != nil {
		return x.Default
	}
	return nil
}

func (x *Schema_Filed_Duration) GetGt() *durationpb.Duration {
	if x != nil {
		return x.Gt
	}
	return nil
}

func (x *Schema_Filed_Duration) GetGte() *durationpb.Duration {
	if x != nil {
		return x.Gte
	}
	return nil
}

func (x *Schema_Filed_Duration) GetLt() *durationpb.Duration {
	if x != nil {
		return x.Lt
	}
	return nil
}

func (x *Schema_Filed_Duration) GetLte() *durationpb.Duration {
	if x != nil {
		return x.Lte
	}
	return nil
}

// Timestamp field kind with optional range bounds.
type Schema_Filed_Timestamp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Default value used when the field is unset.
	Default *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=default,proto3,oneof" json:"default,omitempty"`
	// Exclusive minimum: value > gt.
	Gt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=gt,proto3,oneof" json:"gt,omitempty"`
	// Inclusive minimum: value >= gte.
	Gte *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=gte,proto3,oneof" json:"gte,omitempty"`
	// Exclusive maximum: value < lt.
	Lt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=lt,proto3,oneof" json:"lt,omitempty"`
	// Inclusive maximum: value <= lte.
	Lte           *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=lte,proto3,oneof" json:"lte,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schema_Filed_Timestamp) Reset() {
	*x = Schema_Filed_Timestamp{}
	mi := &file_schemapb_schema_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schema_Filed_Timestamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema_Filed_Timestamp) ProtoMessage() {}

func (x *Schema_Filed_Timestamp) ProtoReflect() protoreflect.Message {
	mi := &file_schemapb_schema_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema_Filed_Timestamp.ProtoReflect.Descriptor instead.
func (*Schema_Filed_Timestamp) Descriptor() ([]byte, []int) {
	return file_schemapb_schema_proto_rawDescGZIP(), []int{0, 0, 10}
}

func (x *Schema_Filed_Timestamp) GetDefault() *timestamppb.Timestamp {
	if x != nil {
		return x.Default
	}
	return nil
}

func (x *Schema_Filed_Timestamp) GetGt() *timestamppb.Timestamp {
	if x != nil {
		return x.Gt
	}
	return nil
}

func (x *Schema_Filed_Timestamp) GetGte() *timestamppb.Timestamp {
	if x != nil {
		return x.Gte
	}
	return nil
}

func (x *Schema_Filed_Timestamp) GetLt() *timestamppb.Timestamp {
	if x != nil {
		return x.Lt
	}
	return nil
}

func (x *Schema_Filed_Timestamp) GetLte() *timestamppb.Timestamp {
	if x != nil {
		return x.Lte
	}
	return nil
}

// List field kind: a repeated value described by its element field(s).
type Schema_Filed_List struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Element field definition(s) describing list items.
	Items []*Schema_Filed `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	// Minimum number of items.
	MinItems *uint64 `protobuf:"varint,2,opt,name=min_items,json=minItems,proto3,oneof" json:"min_items,omitempty"`
	// Maximum number of items.
	MaxItems *uint64 `protobuf:"varint,3,opt,name=max_items,json=maxItems,proto3,oneof" json:"max_items,omitempty"`
	// If true, items must be unique.
	Unique        bool `protobuf:"varint,4,opt,name=unique,proto3" json:"unique,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schema_Filed_List) Reset() {
	*x = Schema_Filed_List{}
	mi := &file_schemapb_schema_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schema_Filed_List) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema_Filed_List) ProtoMessage() {}

func (x *Schema_Filed_List) ProtoReflect() protoreflect.Message {
	mi := &file_schemapb_schema_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema_Filed_List.ProtoReflect.Descriptor instead.
func (*Schema_Filed_List) Descriptor() ([]byte, []int) {
	return file_schemapb_schema_proto_rawDescGZIP(), []int{0, 0, 11}
}

func (x *Schema_Filed_List) GetItems() []*Schema_Filed {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Schema_Filed_List) GetMinItems() uint64 {
	if x != nil && x.MinItems != nil {
		return *x.MinItems
	}
	return 0
}

func (x *Schema_Filed_List) GetMaxItems() uint64 {
	if x != nil && x.MaxItems != nil {
		return *x.MaxItems
	}
	return 0
}

func (x *Schema_Filed_List) GetUnique() bool {
	if x != nil {
		return x.Unique
	}
	return false
}

// Object field kind: a nested sub-form described by its own Schema.
type Schema_Filed_Object struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Nested object schema.
	Schema        *Schema `protobuf:"bytes,1,opt,name=schema,proto3,oneof" json:"schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schema_Filed_Object) Reset() {
	*x = Schema_Filed_Object{}
	mi := &file_schemapb_schema_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schema_Filed_Object) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema_Filed_Object) ProtoMessage() {}

func (x *Schema_Filed_Object) ProtoReflect() protoreflect.Message {
	mi := &file_schemapb_schema_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema_Filed_Object.ProtoReflect.Descriptor instead.
func (*Schema_Filed_Object) Descriptor() ([]byte, []int) {
	return file_schemapb_schema_proto_rawDescGZIP(), []int{0, 0, 12}
}

func (x *Schema_Filed_Object) GetSchema() *Schema {
	if x != nil {
		return x.Schema
	}
	return nil
}

// Computed field kind: a value derived from other values, not entered by
// the user. The server (and the client, for live UX) evaluates `expr`
// and writes the result under this field's name, so other expressions
// and validation rules can read it via `root`.
//
// Evaluation is dependency-ordered: a Computed field may reference inputs
// and other Computed fields. Cycles are rejected at schema-validation
// time. Referencing a value that is absent at evaluation time is an
// error (surfaced as a FieldError on this field's path).
//
// `expr` must be a pure, deterministic expression (no now()/rand) so the
// server and client agree.
type Schema_Filed_Computed struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Expression producing the value. Reads `root` (inputs + already
	// computed values). Bound the same way as Rule expressions.
	Expr string `protobuf:"bytes,1,opt,name=expr,proto3" json:"expr,omitempty"`
	// Result type, used to marshal the value back into the form. The
	// field kind it names (Float/Int32/.../Duration) selects the wire
	// type; structured constraints on it are ignored for output but may
	// still be used to document/round the result. Optional: if unset the
	// server infers the type from the checked expression.
	Result        *Schema_Filed_ResultType `protobuf:"varint,2,opt,name=result,proto3,enum=schemapb.Schema_Filed_ResultType,oneof" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schema_Filed_Computed) Reset() {
	*x = Schema_Filed_Computed{}
	mi := &file_schemapb_schema_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schema_Filed_Computed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema_Filed_Computed) ProtoMessage() {}

func (x *Schema_Filed_Computed) ProtoReflect() protoreflect.Message {
	mi := &file_schemapb_schema_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema_Filed_Computed.ProtoReflect.Descriptor instead.
func (*Schema_Filed_Computed) Descriptor() ([]byte, []int) {
	return file_schemapb_schema_proto_rawDescGZIP(), []int{0, 0, 13}
}

func (x *Schema_Filed_Computed) GetExpr() string {
	if x != nil {
		return x.Expr
	}
	return ""
}

func (x *Schema_Filed_Computed) GetResult() Schema_Filed_ResultType {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return Schema_Filed_RESULT_TYPE_UNSPECIFIED
}

// Rule is a CEL validation expression for cross-field / conditional checks.
// Context: `this` = this field's value (field-level rules only);
//
//	`root` = whole form as map<string, dyn>, any field reachable.
//
// expr must evaluate to bool; true means VALID.
type Schema_Filed_Rule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// CEL boolean expression; true means the value is valid.
	Expr string `protobuf:"bytes,1,opt,name=expr,proto3" json:"expr,omitempty"`
	// Message shown to the user when expr is false.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Stable rule id, for mapping errors back to rules.
	Id *string `protobuf:"bytes,3,opt,name=id,proto3,oneof" json:"id,omitempty"`
	// Severity; defaults to ERROR.
	Severity      *Schema_Filed_Severity `protobuf:"varint,4,opt,name=severity,proto3,enum=schemapb.Schema_Filed_Severity,oneof" json:"severity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schema_Filed_Rule) Reset() {
	*x = Schema_Filed_Rule{}
	mi := &file_schemapb_schema_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schema_Filed_Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema_Filed_Rule) ProtoMessage() {}

func (x *Schema_Filed_Rule) ProtoReflect() protoreflect.Message {
	mi := &file_schemapb_schema_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema_Filed_Rule.ProtoReflect.Descriptor instead.
func (*Schema_Filed_Rule) Descriptor() ([]byte, []int) {
	return file_schemapb_schema_proto_rawDescGZIP(), []int{0, 0, 14}
}

func (x *Schema_Filed_Rule) GetExpr() string {
	if x != nil {
		return x.Expr
	}
	return ""
}

func (x *Schema_Filed_Rule) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Schema_Filed_Rule) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *Schema_Filed_Rule) GetSeverity() Schema_Filed_Severity {
	if x != nil && x.Severity != nil {
		return *x.Severity
	}
	return Schema_Filed_SEVERITY_UNSPECIFIED
}

var File_schemapb_schema_proto protoreflect.FileDescriptor

const file_schemapb_schema_proto_rawDesc = "" +
	"\n" +
	"\x15schemapb/schema.proto\x12\bschemapb\x1a\x1egoogle/protobuf/duration.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb6-\n" +
	"\x06Schema\x12(\n" +
	"\x02id\x18\x01 \x01(\v2\x18.schemapb.SchemaIdentityR\x02id\x12%\n" +
	"\vdescription\x18\x02 \x01(\tH\x00R\vdescription\x88\x01\x01\x12.\n" +
	"\x06fields\x18\x03 \x03(\v2\x16.schemapb.Schema.FiledR\x06fields\x121\n" +
	"\x05rules\x18\x04 \x03(\v2\x1b.schemapb.Schema.Filed.RuleR\x05rules\x12\x16\n" +
	"\x06strict\x18\x05 \x01(\bR\x06strict\x12*\n" +
	"\x0emin_properties\x18\x06 \x01(\x04H\x01R\rminProperties\x88\x01\x01\x12*\n" +
	"\x0emax_properties\x18\a \x01(\x04H\x02R\rmaxProperties\x88\x01\x01\x12\x16\n" +
	"\x06coerce\x18\b \x01(\bR\x06coerce\x1a\xb9*\n" +
	"\x05Filed\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x02 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\x1a\n" +
	"\bnullable\x18\x03 \x01(\bR\bnullable\x12\x1a\n" +
	"\brequired\x18\x04 \x01(\bR\brequired\x121\n" +
	"\x05rules\x18\x05 \x03(\v2\x1b.schemapb.Schema.Filed.RuleR\x05rules\x12\x1c\n" +
	"\timmutable\x18\x14 \x01(\bR\timmutable\x12\x19\n" +
	"\x05group\x18\x15 \x01(\tH\x02R\x05group\x88\x01\x01\x12\x17\n" +
	"\x04unit\x18\x16 \x01(\tH\x03R\x04unit\x88\x01\x01\x12\x19\n" +
	"\x05title\x18\x17 \x01(\tH\x04R\x05title\x88\x01\x01\x12\x1e\n" +
	"\n" +
	"deprecated\x18\x18 \x01(\bR\n" +
	"deprecated\x122\n" +
	"\bexamples\x18\x19 \x03(\v2\x16.google.protobuf.ValueR\bexamples\x12\x16\n" +
	"\x06secret\x18\x1a \x01(\bR\x06secret\x124\n" +
	"\x05float\x18\x06 \x01(\v2\x1c.schemapb.Schema.Filed.FloatH\x00R\x05float\x127\n" +
	"\x06double\x18\a \x01(\v2\x1d.schemapb.Schema.Filed.DoubleH\x00R\x06double\x124\n" +
	"\x05int32\x18\b \x01(\v2\x1c.schemapb.Schema.Filed.Int32H\x00R\x05int32\x124\n" +
	"\x05int64\x18\t \x01(\v2\x1c.schemapb.Schema.Filed.Int64H\x00R\x05int64\x127\n" +
	"\x06uint32\x18\n" +
	" \x01(\v2\x1d.schemapb.Schema.Filed.UInt32H\x00R\x06uint32\x127\n" +
	"\x06uint64\x18\v \x01(\v2\x1d.schemapb.Schema.Filed.UInt64H\x00R\x06uint64\x121\n" +
	"\x04bool\x18\f \x01(\v2\x1b.schemapb.Schema.Filed.BoolH\x00R\x04bool\x127\n" +
	"\x06string\x18\r \x01(\v2\x1d.schemapb.Schema.Filed.StringH\x00R\x06string\x121\n" +
	"\x04enum\x18\x0e \x01(\v2\x1b.schemapb.Schema.Filed.EnumH\x00R\x04enum\x12=\n" +
	"\bduration\x18\x0f \x01(\v2\x1f.schemapb.Schema.Filed.DurationH\x00R\bduration\x12@\n" +
	"\ttimestamp\x18\x10 \x01(\v2 .schemapb.Schema.Filed.TimestampH\x00R\ttimestamp\x121\n" +
	"\x04list\x18\x11 \x01(\v2\x1b.schemapb.Schema.Filed.ListH\x00R\x04list\x127\n" +
	"\x06object\x18\x12 \x01(\v2\x1d.schemapb.Schema.Filed.ObjectH\x00R\x06object\x12=\n" +
	"\bcomputed\x18\x13 \x01(\v2\x1f.schemapb.Schema.Filed.ComputedH\x00R\bcomputed\x1a\xaa\x02\n" +
	"\x05Float\x12\x1d\n" +
	"\adefault\x18\x01 \x01(\x02H\x00R\adefault\x88\x01\x01\x12\x19\n" +
	"\x05const\x18\x02 \x01(\x02H\x01R\x05const\x88\x01\x01\x12\x13\n" +
	"\x02gt\x18\x03 \x01(\x02H\x02R\x02gt\x88\x01\x01\x12\x15\n" +
	"\x03gte\x18\x04 \x01(\x02H\x03R\x03gte\x88\x01\x01\x12\x13\n" +
	"\x02lt\x18\x05 \x01(\x02H\x04R\x02lt\x88\x01\x01\x12\x15\n" +
	"\x03lte\x18\x06 \x01(\x02H\x05R\x03lte\x88\x01\x01\x12\x0e\n" +
	"\x02in\x18\a \x03(\x02R\x02in\x12\x15\n" +
	"\x06not_in\x18\b \x03(\x02R\x05notIn\x12$\n" +
	"\vmultiple_of\x18\t \x01(\x02H\x06R\n" +
	"multipleOf\x88\x01\x01B\n" +
	"\n" +
	"\b_defaultB\b\n" +
	"\x06_constB\x05\n" +
	"\x03_gtB\x06\n" +
	"\x04_gteB\x05\n" +
	"\x03_ltB\x06\n" +
	"\x04_lteB\x0e\n" +
	"\f_multiple_of\x1a\xab\x02\n" +
	"\x06Double\x12\x1d\n" +
	"\adefault\x18\x01 \x01(\x01H\x00R\adefault\x88\x01\x01\x12\x19\n" +
	"\x05const\x18\x02 \x01(\x01H\x01R\x05const\x88\x01\x01\x12\x13\n" +
	"\x02gt\x18\x03 \x01(\x01H\x02R\x02gt\x88\x01\x01\x12\x15\n" +
	"\x03gte\x18\x04 \x01(\x01H\x03R\x03gte\x88\x01\x01\x12\x13\n" +
	"\x02lt\x18\x05 \x01(\x01H\x04R\x02lt\x88\x01\x01\x12\x15\n" +
	"\x03lte\x18\x06 \x01(\x01H\x05R\x03lte\x88\x01\x01\x12\x0e\n" +
	"\x02in\x18\a \x03(\x01R\x02in\x12\x15\n" +
	"\x06not_in\x18\b \x03(\x01R\x05notIn\x12$\n" +
	"\vmultiple_of\x18\t \x01(\x01H\x06R\n" +
	"multipleOf\x88\x01\x01B\n" +
	"\n" +
	"\b_defaultB\b\n" +
	"\x06_constB\x05\n" +
	"\x03_gtB\x06\n" +
	"\x04_gteB\x05\n" +
	"\x03_ltB\x06\n" +
	"\x04_lteB\x0e\n" +
	"\f_multiple_of\x1a\xaa\x02\n" +
	"\x05Int32\x12\x1d\n" +
	"\adefault\x18\x01 \x01(\x05H\x00R\adefault\x88\x01\x01\x12\x19\n" +
	"\x05const\x18\x02 \x01(\x05H\x01R\x05const\x88\x01\x01\x12\x13\n" +
	"\x02gt\x18\x03 \x01(\x05H\x02R\x02gt\x88\x01\x01\x12\x15\n" +
	"\x03gte\x18\x04 \x01(\x05H\x03R\x03gte\x88\x01\x01\x12\x13\n" +
	"\x02lt\x18\x05 \x01(\x05H\x04R\x02lt\x88\x01\x01\x12\x15\n" +
	"\x03lte\x18\x06 \x01(\x05H\x05R\x03lte\x88\x01\x01\x12\x0e\n" +
	"\x02in\x18\a \x03(\x05R\x02in\x12\x15\n" +
	"\x06not_in\x18\b \x03(\x05R\x05notIn\x12$\n" +
	"\vmultiple_of\x18\t \x01(\x05H\x06R\n" +
	"multipleOf\x88\x01\x01B\n" +
	"\n" +
	"\b_defaultB\b\n" +
	"\x06_constB\x05\n" +
	"\x03_gtB\x06\n" +
	"\x04_gteB\x05\n" +
	"\x03_ltB\x06\n" +
	"\x04_lteB\x0e\n" +
	"\f_multiple_of\x1a\xaa\x02\n" +
	"\x05Int64\x12\x1d\n" +
	"\adefault\x18\x01 \x01(\x03H\x00R\adefault\x88\x01\x01\x12\x19\n" +
	"\x05const\x18\x02 \x01(\x03H\x01R\x05const\x88\x01\x01\x12\x13\n" +
	"\x02gt\x18\x03 \x01(\x03H\x02R\x02gt\x88\x01\x01\x12\x15\n" +
	"\x03gte\x18\x04 \x01(\x03H\x03R\x03gte\x88\x01\x01\x12\x13\n" +
	"\x02lt\x18\x05 \x01(\x03H\x04R\x02lt\x88\x01\x01\x12\x15\n" +
	"\x03lte\x18\x06 \x01(\x03H\x05R\x03lte\x88\x01\x01\x12\x0e\n" +
	"\x02in\x18\a \x03(\x03R\x02in\x12\x15\n" +
	"\x06not_in\x18\b \x03(\x03R\x05notIn\x12$\n" +
	"\vmultiple_of\x18\t \x01(\x03H\x06R\n" +
	"multipleOf\x88\x01\x01B\n" +
	"\n" +
	"\b_defaultB\b\n" +
	"\x06_constB\x05\n" +
	"\x03_gtB\x06\n" +
	"\x04_gteB\x05\n" +
	"\x03_ltB\x06\n" +
	"\x04_lteB\x0e\n" +
	"\f_multiple_of\x1a\xab\x02\n" +
	"\x06UInt32\x12\x1d\n" +
	"\adefault\x18\x01 \x01(\rH\x00R\adefault\x88\x01\x01\x12\x19\n" +
	"\x05const\x18\x02 \x01(\rH\x01R\x05const\x88\x01\x01\x12\x13\n" +
	"\x02gt\x18\x03 \x01(\rH\x02R\x02gt\x88\x01\x01\x12\x15\n" +
	"\x03gte\x18\x04 \x01(\rH\x03R\x03gte\x88\x01\x01\x12\x13\n" +
	"\x02lt\x18\x05 \x01(\rH\x04R\x02lt\x88\x01\x01\x12\x15\n" +
	"\x03lte\x18\x06 \x01(\rH\x05R\x03lte\x88\x01\x01\x12\x0e\n" +
	"\x02in\x18\a \x03(\rR\x02in\x12\x15\n" +
	"\x06not_in\x18\b \x03(\rR\x05notIn\x12$\n" +
	"\vmultiple_of\x18\t \x01(\rH\x06R\n" +
	"multipleOf\x88\x01\x01B\n" +
	"\n" +
	"\b_defaultB\b\n" +
	"\x06_constB\x05\n" +
	"\x03_gtB\x06\n" +
	"\x04_gteB\x05\n" +
	"\x03_ltB\x06\n" +
	"\x04_lteB\x0e\n" +
	"\f_multiple_of\x1a\xab\x02\n" +
	"\x06UInt64\x12\x1d\n" +
	"\adefault\x18\x01 \x01(\x04H\x00R\adefault\x88\x01\x01\x12\x19\n" +
	"\x05const\x18\x02 \x01(\x04H\x01R\x05const\x88\x01\x01\x12\x13\n" +
	"\x02gt\x18\x03 \x01(\x04H\x02R\x02gt\x88\x01\x01\x12\x15\n" +
	"\x03gte\x18\x04 \x01(\x04H\x03R\x03gte\x88\x01\x01\x12\x13\n" +
	"\x02lt\x18\x05 \x01(\x04H\x04R\x02lt\x88\x01\x01\x12\x15\n" +
	"\x03lte\x18\x06 \x01(\x04H\x05R\x03lte\x88\x01\x01\x12\x0e\n" +
	"\x02in\x18\a \x03(\x04R\x02in\x12\x15\n" +
	"\x06not_in\x18\b \x03(\x04R\x05notIn\x12$\n" +
	"\vmultiple_of\x18\t \x01(\x04H\x06R\n" +
	"multipleOf\x88\x01\x01B\n" +
	"\n" +
	"\b_defaultB\b\n" +
	"\x06_constB\x05\n" +
	"\x03_gtB\x06\n" +
	"\x04_gteB\x05\n" +
	"\x03_ltB\x06\n" +
	"\x04_lteB\x0e\n" +
	"\f_multiple_of\x1aV\n" +
	"\x04Bool\x12\x1d\n" +
	"\adefault\x18\x01 \x01(\bH\x00R\adefault\x88\x01\x01\x12\x19\n" +
	"\x05const\x18\x02 \x01(\bH\x01R\x05const\x88\x01\x01B\n" +
	"\n" +
	"\b_defaultB\b\n" +
	"\x06_const\x1a\x97\x05\n" +
	"\x06String\x12\x1d\n" +
	"\adefault\x18\x01 \x01(\tH\x00R\adefault\x88\x01\x01\x12\x19\n" +
	"\x05const\x18\x02 \x01(\tH\x01R\x05const\x88\x01\x01\x12\x15\n" +
	"\x03len\x18\x03 \x01(\x04H\x02R\x03len\x88\x01\x01\x12\x1c\n" +
	"\amin_len\x18\x04 \x01(\x04H\x03R\x06minLen\x88\x01\x01\x12\x1c\n" +
	"\amax_len\x18\x05 \x01(\x04H\x04R\x06maxLen\x88\x01\x01\x12\x1d\n" +
	"\apattern\x18\x06 \x01(\tH\x05R\apattern\x88\x01\x01\x12\x0e\n" +
	"\x02in\x18\a \x03(\tR\x02in\x12\x15\n" +
	"\x06not_in\x18\b \x03(\tR\x05notIn\x12G\n" +
	"\x06format\x18\t \x01(\x0e2*.schemapb.Schema.Filed.String.StringFormatH\x06R\x06format\x88\x01\x01\"\xa3\x02\n" +
	"\fStringFormat\x12\x1d\n" +
	"\x19STRING_FORMAT_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13STRING_FORMAT_EMAIL\x10\x01\x12\x15\n" +
	"\x11STRING_FORMAT_URL\x10\x02\x12\x16\n" +
	"\x12STRING_FORMAT_UUID\x10\x03\x12\x16\n" +
	"\x12STRING_FORMAT_IPV4\x10\x04\x12\x16\n" +
	"\x12STRING_FORMAT_IPV6\x10\x05\x12\x14\n" +
	"\x10STRING_FORMAT_IP\x10\x06\x12\x1a\n" +
	"\x16STRING_FORMAT_HOSTNAME\x10\a\x12\x16\n" +
	"\x12STRING_FORMAT_DATE\x10\b\x12\x16\n" +
	"\x12STRING_FORMAT_TIME\x10\t\x12\x1a\n" +
	"\x16STRING_FORMAT_DATETIME\x10\n" +
	"B\n" +
	"\n" +
	"\b_defaultB\b\n" +
	"\x06_constB\x06\n" +
	"\x04_lenB\n" +
	"\n" +
	"\b_min_lenB\n" +
	"\n" +
	"\b_max_lenB\n" +
	"\n" +
	"\b_patternB\t\n" +
	"\a_format\x1a\xf7\x01\n" +
	"\x04Enum\x12\x1d\n" +
	"\adefault\x18\x01 \x01(\x05H\x00R\adefault\x88\x01\x01\x12?\n" +
	"\x06values\x18\x02 \x03(\v2'.schemapb.Schema.Filed.Enum.ValuesEntryR\x06values\x12!\n" +
	"\fdefined_only\x18\x03 \x01(\bR\vdefinedOnly\x12\x0e\n" +
	"\x02in\x18\x04 \x03(\x05R\x02in\x12\x15\n" +
	"\x06not_in\x18\x05 \x03(\x05R\x05notIn\x1a9\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\n" +
	"\n" +
	"\b_default\x1a\xb2\x02\n" +
	"\bDuration\x128\n" +
	"\adefault\x18\x01 \x01(\v2\x19.google.protobuf.DurationH\x00R\adefault\x88\x01\x01\x12.\n" +
	"\x02gt\x18\x02 \x01(\v2\x19.google.protobuf.DurationH\x01R\x02gt\x88\x01\x01\x120\n" +
	"\x03gte\x18\x03 \x01(\v2\x19.google.protobuf.DurationH\x02R\x03gte\x88\x01\x01\x12.\n" +
	"\x02lt\x18\x04 \x01(\v2\x19.google.protobuf.DurationH\x03R\x02lt\x88\x01\x01\x120\n" +
	"\x03lte\x18\x05 \x01(\v2\x19.google.protobuf.DurationH\x04R\x03lte\x88\x01\x01B\n" +
	"\n" +
	"\b_defaultB\x05\n" +
	"\x03_gtB\x06\n" +
	"\x04_gteB\x05\n" +
	"\x03_ltB\x06\n" +
	"\x04_lte\x1a\xb8\x02\n" +
	"\tTimestamp\x129\n" +
	"\adefault\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\adefault\x88\x01\x01\x12/\n" +
	"\x02gt\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\x02gt\x88\x01\x01\x121\n" +
	"\x03gte\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x02R\x03gte\x88\x01\x01\x12/\n" +
	"\x02lt\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x03R\x02lt\x88\x01\x01\x121\n" +
	"\x03lte\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x04R\x03lte\x88\x01\x01B\n" +
	"\n" +
	"\b_defaultB\x05\n" +
	"\x03_gtB\x06\n" +
	"\x04_gteB\x05\n" +
	"\x03_ltB\x06\n" +
	"\x04_lte\x1a\xac\x01\n" +
	"\x04List\x12,\n" +
	"\x05items\x18\x01 \x03(\v2\x16.schemapb.Schema.FiledR\x05items\x12 \n" +
	"\tmin_items\x18\x02 \x01(\x04H\x00R\bminItems\x88\x01\x01\x12 \n" +
	"\tmax_items\x18\x03 \x01(\x04H\x01R\bmaxItems\x88\x01\x01\x12\x16\n" +
	"\x06unique\x18\x04 \x01(\bR\x06uniqueB\f\n" +
	"\n" +
	"_min_itemsB\f\n" +
	"\n" +
	"_max_items\x1aB\n" +
	"\x06Object\x12-\n" +
	"\x06schema\x18\x01 \x01(\v2\x10.schemapb.SchemaH\x00R\x06schema\x88\x01\x01B\t\n" +
	"\a_schema\x1ai\n" +
	"\bComputed\x12\x12\n" +
	"\x04expr\x18\x01 \x01(\tR\x04expr\x12>\n" +
	"\x06result\x18\x02 \x01(\x0e2!.schemapb.Schema.Filed.ResultTypeH\x00R\x06result\x88\x01\x01B\t\n" +
	"\a_result\x1a\x9f\x01\n" +
	"\x04Rule\x12\x12\n" +
	"\x04expr\x18\x01 \x01(\tR\x04expr\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x13\n" +
	"\x02id\x18\x03 \x01(\tH\x00R\x02id\x88\x01\x01\x12@\n" +
	"\bseverity\x18\x04 \x01(\x0e2\x1f.schemapb.Schema.Filed.SeverityH\x01R\bseverity\x88\x01\x01B\x05\n" +
	"\x03_idB\v\n" +
	"\t_severity\"\xb8\x01\n" +
	"\n" +
	"ResultType\x12\x1b\n" +
	"\x17RESULT_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12RESULT_TYPE_DOUBLE\x10\x01\x12\x15\n" +
	"\x11RESULT_TYPE_INT64\x10\x02\x12\x16\n" +
	"\x12RESULT_TYPE_UINT64\x10\x03\x12\x14\n" +
	"\x10RESULT_TYPE_BOOL\x10\x04\x12\x16\n" +
	"\x12RESULT_TYPE_STRING\x10\x05\x12\x18\n" +
	"\x14RESULT_TYPE_DURATION\x10\x06\"<\n" +
	"\bSeverity\x12\x18\n" +
	"\x14SEVERITY_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05ERROR\x10\x01\x12\v\n" +
	"\aWARNING\x10\x02B\x06\n" +
	"\x04kindB\x0e\n" +
	"\f_descriptionB\b\n" +
	"\x06_groupB\a\n" +
	"\x05_unitB\b\n" +
	"\x06_titleB\x0e\n" +
	"\f_descriptionB\x11\n" +
	"\x0f_min_propertiesB\x11\n" +
	"\x0f_max_properties\"\\\n" +
	"\x0eSchemaIdentity\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"\xac\x02\n" +
	"\n" +
	"FieldError\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\arule_id\x18\x03 \x01(\tH\x00R\x06ruleId\x88\x01\x01\x12;\n" +
	"\bseverity\x18\x04 \x01(\x0e2\x1f.schemapb.Schema.Filed.SeverityR\bseverity\x12\x12\n" +
	"\x04code\x18\x05 \x01(\tR\x04code\x128\n" +
	"\x06params\x18\x06 \x03(\v2 .schemapb.FieldError.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\n" +
	"\n" +
	"\b_rule_id\"m\n" +
	"\tSchemaRef\x12*\n" +
	"\x02id\x18\x01 \x01(\v2\x18.schemapb.SchemaIdentityH\x00R\x02id\x12*\n" +
	"\x06schema\x18\x02 \x01(\v2\x10.schemapb.SchemaH\x00R\x06schemaB\b\n" +
	"\x06source\"f\n" +
	"\x06Filled\x12+\n" +
	"\x06schema\x18\x01 \x01(\v2\x13.schemapb.SchemaRefR\x06schema\x12/\n" +
	"\x06values\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x06values\"b\n" +
	"\x05Baked\x12(\n" +
	"\x06schema\x18\x01 \x01(\v2\x10.schemapb.SchemaR\x06schema\x12/\n" +
	"\x06values\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x06valuesB)Z'github.com/stroppy-io/schemapb/schemapbb\x06proto3"

var (
	file_schemapb_schema_proto_rawDescOnce sync.Once
	file_schemapb_schema_proto_rawDescData []byte
)

func file_schemapb_schema_proto_rawDescGZIP() []byte {
	file_schemapb_schema_proto_rawDescOnce.Do(func() {
		file_schemapb_schema_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_schemapb_schema_proto_rawDesc), len(file_schemapb_schema_proto_rawDesc)))
	})
	return file_schemapb_schema_proto_rawDescData
}

var file_schemapb_schema_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_schemapb_schema_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_schemapb_schema_proto_goTypes = []any{
	(Schema_Filed_ResultType)(0),          // 0: schemapb.Schema.Filed.ResultType
	(Schema_Filed_Severity)(0),            // 1: schemapb.Schema.Filed.Severity
	(Schema_Filed_String_StringFormat)(0), // 2: schemapb.Schema.Filed.String.StringFormat
	(*Schema)(nil),                        // 3: schemapb.Schema
	(*SchemaIdentity)(nil),                // 4: schemapb.SchemaIdentity
	(*FieldError)(nil),                    // 5: schemapb.FieldError
	(*SchemaRef)(nil),                     // 6: schemapb.SchemaRef
	(*Filled)(nil),                        // 7: schemapb.Filled
	(*Baked)(nil),                         // 8: schemapb.Baked
	(*Schema_Filed)(nil),                  // 9: schemapb.Schema.Filed
	(*Schema_Filed_Float)(nil),            // 10: schemapb.Schema.Filed.Float
	(*Schema_Filed_Double)(nil),           // 11: schemapb.Schema.Filed.Double
	(*Schema_Filed_Int32)(nil),            // 12: schemapb.Schema.Filed.Int32
	(*Schema_Filed_Int64)(nil),            // 13: schemapb.Schema.Filed.Int64
	(*Schema_Filed_UInt32)(nil),           // 14: schemapb.Schema.Filed.UInt32
	(*Schema_Filed_UInt64)(nil),           // 15: schemapb.Schema.Filed.UInt64
	(*Schema_Filed_Bool)(nil),             // 16: schemapb.Schema.Filed.Bool
	(*Schema_Filed_String)(nil),           // 17: schemapb.Schema.Filed.String
	(*Schema_Filed_Enum)(nil),             // 18: schemapb.Schema.Filed.Enum
	(*Schema_Filed_Duration)(nil),         // 19: schemapb.Schema.Filed.Duration
	(*Schema_Filed_Timestamp)(nil),        // 20: schemapb.Schema.Filed.Timestamp
	(*Schema_Filed_List)(nil),             // 21: schemapb.Schema.Filed.List
	(*Schema_Filed_Object)(nil),           // 22: schemapb.Schema.Filed.Object
	(*Schema_Filed_Computed)(nil),         // 23: schemapb.Schema.Filed.Computed
	(*Schema_Filed_Rule)(nil),             // 24: schemapb.Schema.Filed.Rule
	nil,                                   // 25: schemapb.Schema.Filed.Enum.ValuesEntry
	nil,                                   // 26: schemapb.FieldError.ParamsEntry
	(*structpb.Struct)(nil),               // 27: google.protobuf.Struct
	(*structpb.Value)(nil),                // 28: google.protobuf.Value
	(*durationpb.Duration)(nil),           // 29: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil),         // 30: google.protobuf.Timestamp
}
var file_schemapb_schema_proto_depIdxs = []int32{
	4,  // 0: schemapb.Schema.id:type_name -> schemapb.SchemaIdentity
	9,  // 1: schemapb.Schema.fields:type_name -> schemapb.Schema.Filed
	24, // 2: schemapb.Schema.rules:type_name -> schemapb.Schema.Filed.Rule
	1,  // 3: schemapb.FieldError.severity:type_name -> schemapb.Schema.Filed.Severity
	26, // 4: schemapb.FieldError.params:type_name -> schemapb.FieldError.ParamsEntry
	4,  // 5: schemapb.SchemaRef.id:type_name -> schemapb.SchemaIdentity
	3,  // 6: schemapb.SchemaRef.schema:type_name -> schemapb.Schema
	6,  // 7: schemapb.Filled.schema:type_name -> schemapb.SchemaRef
	27, // 8: schemapb.Filled.values:type_name -> google.protobuf.Struct
	3,  // 9: schemapb.Baked.schema:type_name -> schemapb.Schema
	27, // 10: schemapb.Baked.values:type_name -> google.protobuf.Struct
	24, // 11: schemapb.Schema.Filed.rules:type_name -> schemapb.Schema.Filed.Rule
	28, // 12: schemapb.Schema.Filed.examples:type_name -> google.protobuf.Value
	10, // 13: schemapb.Schema.Filed.float:type_name -> schemapb.Schema.Filed.Float
	11, // 14: schemapb.Schema.Filed.double:type_name -> schemapb.Schema.Filed.Double
	12, // 15: schemapb.Schema.Filed.int32:type_name -> schemapb.Schema.Filed.Int32
	13, // 16: schemapb.Schema.Filed.int64:type_name -> schemapb.Schema.Filed.Int64
	14, // 17: schemapb.Schema.Filed.uint32:type_name -> schemapb.Schema.Filed.UInt32
	15, // 18: schemapb.Schema.Filed.uint64:type_name -> schemapb.Schema.Filed.UInt64
	16, // 19: schemapb.Schema.Filed.bool:type_name -> schemapb.Schema.Filed.Bool
	17, // 20: schemapb.Schema.Filed.string:type_name -> schemapb.Schema.Filed.String
	18, // 21: schemapb.Schema.Filed.enum:type_name -> schemapb.Schema.Filed.Enum
	19, // 22: schemapb.Schema.Filed.duration:type_name -> schemapb.Schema.Filed.Duration
	20, // 23: schemapb.Schema.Filed.timestamp:type_name -> schemapb.Schema.Filed.Timestamp
	21, // 24: schemapb.Schema.Filed.list:type_name -> schemapb.Schema.Filed.List
	22, // 25: schemapb.Schema.Filed.object:type_name -> schemapb.Schema.Filed.Object
	23, // 26: schemapb.Schema.Filed.computed:type_name -> schemapb.Schema.Filed.Computed
	2,  // 27: schemapb.Schema.Filed.String.format:type_name -> schemapb.Schema.Filed.String.StringFormat
	25, // 28: schemapb.Schema.Filed.Enum.values:type_name -> schemapb.Schema.Filed.Enum.ValuesEntry
	29, // 29: schemapb.Schema.Filed.Duration.default:type_name -> google.protobuf.Duration
	29, // 30: schemapb.Schema.Filed.Duration.gt:type_name -> google.protobuf.Duration
	29, // 31: schemapb.Schema.Filed.Duration.gte:type_name -> google.protobuf.Duration
	29, // 32: schemapb.Schema.Filed.Duration.lt:type_name -> google.protobuf.Duration
	29, // 33: schemapb.Schema.Filed.Duration.lte:type_name -> google.protobuf.Duration
	30, // 34: schemapb.Schema.Filed.Timestamp.default:type_name -> google.protobuf.Timestamp
	30, // 35: schemapb.Schema.Filed.Timestamp.gt:type_name -> google.protobuf.Timestamp
	30, // 36: schemapb.Schema.Filed.Timestamp.gte:type_name -> google.protobuf.Timestamp
	30, // 37: schemapb.Schema.Filed.Timestamp.lt:type_name -> google.protobuf.Timestamp
	30, // 38: schemapb.Schema.Filed.Timestamp.lte:type_name -> google.protobuf.Timestamp
	9,  // 39: schemapb.Schema.Filed.List.items:type_name -> schemapb.Schema.Filed
	3,  // 40: schemapb.Schema.Filed.Object.schema:type_name -> schemapb.Schema
	0,  // 41: schemapb.Schema.Filed.Computed.result:type_name -> schemapb.Schema.Filed.ResultType
	1,  // 42: schemapb.Schema.Filed.Rule.severity:type_name -> schemapb.Schema.Filed.Severity
	43, // [43:43] is the sub-list for method output_type
	43, // [43:43] is the sub-list for method input_type
	43, // [43:43] is the sub-list for extension type_name
	43, // [43:43] is the sub-list for extension extendee
	0,  // [0:43] is the sub-list for field type_name
}

func init() { file_schemapb_schema_proto_init() }
func file_schemapb_schema_proto_init() {
	if File_schemapb_schema_proto != nil {
		return
	}
	file_schemapb_schema_proto_msgTypes[0].OneofWrappers = []any{}
	file_schemapb_schema_proto_msgTypes[2].OneofWrappers = []any{}
	file_schemapb_schema_proto_msgTypes[3].OneofWrappers = []any{
		(*SchemaRef_Id)(nil),
		(*SchemaRef_Schema)(nil),
	}
	file_schemapb_schema_proto_msgTypes[6].OneofWrappers = []any{
		(*Schema_Filed_Float_)(nil),
		(*Schema_Filed_Double_)(nil),
		(*Schema_Filed_Int32_)(nil),
		(*Schema_Filed_Int64_)(nil),
		(*Schema_Filed_Uint32)(nil),
		(*Schema_Filed_Uint64)(nil),
		(*Schema_Filed_Bool_)(nil),
		(*Schema_Filed_String_)(nil),
		(*Schema_Filed_Enum_)(nil),
		(*Schema_Filed_Duration_)(nil),
		(*Schema_Filed_Timestamp_)(nil),
		(*Schema_Filed_List_)(nil),
		(*Schema_Filed_Object_)(nil),
		(*Schema_Filed_Computed_)(nil),
	}
	file_schemapb_schema_proto_msgTypes[7].OneofWrappers = []any{}
	file_schemapb_schema_proto_msgTypes[8].OneofWrappers = []any{}
	file_schemapb_schema_proto_msgTypes[9].OneofWrappers = []any{}
	file_schemapb_schema_proto_msgTypes[10].OneofWrappers = []any{}
	file_schemapb_schema_proto_msgTypes[11].OneofWrappers = []any{}
	file_schemapb_schema_proto_msgTypes[12].OneofWrappers = []any{}
	file_schemapb_schema_proto_msgTypes[13].OneofWrappers = []any{}
	file_schemapb_schema_proto_msgTypes[14].OneofWrappers = []any{}
	file_schemapb_schema_proto_msgTypes[15].OneofWrappers = []any{}
	file_schemapb_schema_proto_msgTypes[16].OneofWrappers = []any{}
	file_schemapb_schema_proto_msgTypes[17].OneofWrappers = []any{}
	file_schemapb_schema_proto_msgTypes[18].OneofWrappers = []any{}
	file_schemapb_schema_proto_msgTypes[19].OneofWrappers = []any{}
	file_schemapb_schema_proto_msgTypes[20].OneofWrappers = []any{}
	file_schemapb_schema_proto_msgTypes[21].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_schemapb_schema_proto_rawDesc), len(file_schemapb_schema_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_schemapb_schema_proto_goTypes,
		DependencyIndexes: file_schemapb_schema_proto_depIdxs,
		EnumInfos:         file_schemapb_schema_proto_enumTypes,
		MessageInfos:      file_schemapb_schema_proto_msgTypes,
	}.Build()
	File_schemapb_schema_proto = out.File
	file_schemapb_schema_proto_goTypes = nil
	file_schemapb_schema_proto_depIdxs = nil
}
