// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: schemapb/schema.proto

package schemapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Severity of a failed rule.
type Schema_Filed_Severity int32

const (
	// Unset: treated as ERROR.
	Schema_Filed_SEVERITY_UNSPECIFIED Schema_Filed_Severity = 0
	// Blocks submit.
	Schema_Filed_ERROR Schema_Filed_Severity = 1
	// Surfaced to the user but does not block submit.
	Schema_Filed_WARNING Schema_Filed_Severity = 2
)

// Enum value maps for Schema_Filed_Severity.
var (
	Schema_Filed_Severity_name = map[int32]string{
		0: "SEVERITY_UNSPECIFIED",
		1: "ERROR",
		2: "WARNING",
	}
	Schema_Filed_Severity_value = map[string]int32{
		"SEVERITY_UNSPECIFIED": 0,
		"ERROR":                1,
		"WARNING":              2,
	}
)

func (x Schema_Filed_Severity) Enum() *Schema_Filed_Severity {
	p := new(Schema_Filed_Severity)
	*p = x
	return p
}

func (x Schema_Filed_Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Schema_Filed_Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_schemapb_schema_proto_enumTypes[0].Descriptor()
}

func (Schema_Filed_Severity) Type() protoreflect.EnumType {
	return &file_schemapb_schema_proto_enumTypes[0]
}

func (x Schema_Filed_Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Schema_Filed_Severity.Descriptor instead.
func (Schema_Filed_Severity) EnumDescriptor() ([]byte, []int) {
	return file_schemapb_schema_proto_rawDescGZIP(), []int{0, 0, 0}
}

// Widget kinds the renderer can pick from.
type Schema_Filed_UI_Widget int32

const (
	// Unset: renderer picks a default widget by field kind.
	Schema_Filed_UI_WIDGET_UNSPECIFIED Schema_Filed_UI_Widget = 0
	// Single-line text or number input, per kind.
	Schema_Filed_UI_WIDGET_INPUT Schema_Filed_UI_Widget = 1
	// Slider for bounded numbers.
	Schema_Filed_UI_WIDGET_SLIDER Schema_Filed_UI_Widget = 2
	// Dropdown select, for enum.
	Schema_Filed_UI_WIDGET_SELECT Schema_Filed_UI_Widget = 3
	// Radio group.
	Schema_Filed_UI_WIDGET_RADIO Schema_Filed_UI_Widget = 4
	// Toggle switch, for bool.
	Schema_Filed_UI_WIDGET_SWITCH Schema_Filed_UI_Widget = 5
	// Multi-line text area.
	Schema_Filed_UI_WIDGET_TEXTAREA Schema_Filed_UI_Widget = 6
)

// Enum value maps for Schema_Filed_UI_Widget.
var (
	Schema_Filed_UI_Widget_name = map[int32]string{
		0: "WIDGET_UNSPECIFIED",
		1: "WIDGET_INPUT",
		2: "WIDGET_SLIDER",
		3: "WIDGET_SELECT",
		4: "WIDGET_RADIO",
		5: "WIDGET_SWITCH",
		6: "WIDGET_TEXTAREA",
	}
	Schema_Filed_UI_Widget_value = map[string]int32{
		"WIDGET_UNSPECIFIED": 0,
		"WIDGET_INPUT":       1,
		"WIDGET_SLIDER":      2,
		"WIDGET_SELECT":      3,
		"WIDGET_RADIO":       4,
		"WIDGET_SWITCH":      5,
		"WIDGET_TEXTAREA":    6,
	}
)

func (x Schema_Filed_UI_Widget) Enum() *Schema_Filed_UI_Widget {
	p := new(Schema_Filed_UI_Widget)
	*p = x
	return p
}

func (x Schema_Filed_UI_Widget) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Schema_Filed_UI_Widget) Descriptor() protoreflect.EnumDescriptor {
	return file_schemapb_schema_proto_enumTypes[1].Descriptor()
}

func (Schema_Filed_UI_Widget) Type() protoreflect.EnumType {
	return &file_schemapb_schema_proto_enumTypes[1]
}

func (x Schema_Filed_UI_Widget) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Schema_Filed_UI_Widget.Descriptor instead.
func (Schema_Filed_UI_Widget) EnumDescriptor() ([]byte, []int) {
	return file_schemapb_schema_proto_rawDescGZIP(), []int{0, 0, 13, 0}
}

// Schema is a runtime, dynamic form descriptor. The server builds a Schema and
// ships it to the frontend, which renders a form from it.
//
// Validation has two layers:
//   - per-kind structured rules (gt/gte/lt/lte/in/pattern/...) for the common,
//     single-field cases. Ergonomic to author and introspectable by the
//     renderer (e.g. slider bounds, step).
//   - Filed.rules: CEL expressions, for cross-field / conditional validation.
//
// Both layers run through one engine: structured rules are lowered to CEL at
// load time, then evaluated by cel-go (server, authoritative) and cel-es
// (client, live UX) from the same expression. Rendering is driven by Filed.UI.
//
// The PGV (validate.rules) options below validate the descriptor ITSELF (that a
// Schema is well-formed: names set, expressions non-empty, a kind chosen), not
// the runtime form values it describes.
type Schema struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional schema name.
	Name *string `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// The fields that make up the form.
	Fields []*Schema_Filed `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	// Form-wide invariant rules (`root` only, no `this`).
	Rules         []*Schema_Filed_Rule `protobuf:"bytes,3,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schema) Reset() {
	*x = Schema{}
	mi := &file_schemapb_schema_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema) ProtoMessage() {}

func (x *Schema) ProtoReflect() protoreflect.Message {
	mi := &file_schemapb_schema_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema.ProtoReflect.Descriptor instead.
func (*Schema) Descriptor() ([]byte, []int) {
	return file_schemapb_schema_proto_rawDescGZIP(), []int{0}
}

func (x *Schema) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Schema) GetFields() []*Schema_Filed {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *Schema) GetRules() []*Schema_Filed_Rule {
	if x != nil {
		return x.Rules
	}
	return nil
}

// FieldError is a single validation failure returned by the server-side
// validator (and reusable to render server errors on the client).
type FieldError struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Field name or dotted path that failed.
	Field string `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	// Human-readable failure message.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Id of the rule that failed, if any.
	RuleId *string `protobuf:"bytes,3,opt,name=rule_id,json=ruleId,proto3,oneof" json:"rule_id,omitempty"`
	// Severity of the failure.
	Severity      Schema_Filed_Severity `protobuf:"varint,4,opt,name=severity,proto3,enum=cloud.v1.common.Schema_Filed_Severity" json:"severity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldError) Reset() {
	*x = FieldError{}
	mi := &file_schemapb_schema_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldError) ProtoMessage() {}

func (x *FieldError) ProtoReflect() protoreflect.Message {
	mi := &file_schemapb_schema_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldError.ProtoReflect.Descriptor instead.
func (*FieldError) Descriptor() ([]byte, []int) {
	return file_schemapb_schema_proto_rawDescGZIP(), []int{1}
}

func (x *FieldError) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *FieldError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FieldError) GetRuleId() string {
	if x != nil && x.RuleId != nil {
		return *x.RuleId
	}
	return ""
}

func (x *FieldError) GetSeverity() Schema_Filed_Severity {
	if x != nil {
		return x.Severity
	}
	return Schema_Filed_SEVERITY_UNSPECIFIED
}

type Schema_Filed struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Field name; the key under which the value lives in the form.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Human description of the field.
	Description *string `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// If true, the value may be null/empty.
	Nullable bool `protobuf:"varint,3,opt,name=nullable,proto3" json:"nullable,omitempty"`
	// If true, the value must be present.
	Required bool `protobuf:"varint,4,opt,name=required,proto3" json:"required,omitempty"`
	// Render hints for this field.
	Ui *Schema_Filed_UI `protobuf:"bytes,5,opt,name=ui,proto3" json:"ui,omitempty"`
	// Cross-field CEL validation rules (`this` is bound to this field).
	Rules []*Schema_Filed_Rule `protobuf:"bytes,6,rep,name=rules,proto3" json:"rules,omitempty"`
	// The field kind; exactly one must be set.
	// Types that are valid to be assigned to Kind:
	//
	//	*Schema_Filed_Float_
	//	*Schema_Filed_Double_
	//	*Schema_Filed_Int32_
	//	*Schema_Filed_Int64_
	//	*Schema_Filed_Uint32
	//	*Schema_Filed_Uint64
	//	*Schema_Filed_Bool_
	//	*Schema_Filed_String_
	//	*Schema_Filed_Enum_
	//	*Schema_Filed_Duration_
	//	*Schema_Filed_Timestamp_
	//	*Schema_Filed_List_
	//	*Schema_Filed_Object_
	Kind          isSchema_Filed_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schema_Filed) Reset() {
	*x = Schema_Filed{}
	mi := &file_schemapb_schema_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schema_Filed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema_Filed) ProtoMessage() {}

func (x *Schema_Filed) ProtoReflect() protoreflect.Message {
	mi := &file_schemapb_schema_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema_Filed.ProtoReflect.Descriptor instead.
func (*Schema_Filed) Descriptor() ([]byte, []int) {
	return file_schemapb_schema_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Schema_Filed) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Schema_Filed) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Schema_Filed) GetNullable() bool {
	if x != nil {
		return x.Nullable
	}
	return false
}

func (x *Schema_Filed) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *Schema_Filed) GetUi() *Schema_Filed_UI {
	if x != nil {
		return x.Ui
	}
	return nil
}

func (x *Schema_Filed) GetRules() []*Schema_Filed_Rule {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *Schema_Filed) GetKind() isSchema_Filed_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Schema_Filed) GetFloat() *Schema_Filed_Float {
	if x != nil {
		if x, ok := x.Kind.(*Schema_Filed_Float_); ok {
			return x.Float
		}
	}
	return nil
}

func (x *Schema_Filed) GetDouble() *Schema_Filed_Double {
	if x != nil {
		if x, ok := x.Kind.(*Schema_Filed_Double_); ok {
			return x.Double
		}
	}
	return nil
}

func (x *Schema_Filed) GetInt32() *Schema_Filed_Int32 {
	if x != nil {
		if x, ok := x.Kind.(*Schema_Filed_Int32_); ok {
			return x.Int32
		}
	}
	return nil
}

func (x *Schema_Filed) GetInt64() *Schema_Filed_Int64 {
	if x != nil {
		if x, ok := x.Kind.(*Schema_Filed_Int64_); ok {
			return x.Int64
		}
	}
	return nil
}

func (x *Schema_Filed) GetUint32() *Schema_Filed_UInt32 {
	if x != nil {
		if x, ok := x.Kind.(*Schema_Filed_Uint32); ok {
			return x.Uint32
		}
	}
	return nil
}

func (x *Schema_Filed) GetUint64() *Schema_Filed_UInt64 {
	if x != nil {
		if x, ok := x.Kind.(*Schema_Filed_Uint64); ok {
			return x.Uint64
		}
	}
	return nil
}

func (x *Schema_Filed) GetBool() *Schema_Filed_Bool {
	if x != nil {
		if x, ok := x.Kind.(*Schema_Filed_Bool_); ok {
			return x.Bool
		}
	}
	return nil
}

func (x *Schema_Filed) GetString_() *Schema_Filed_String {
	if x != nil {
		if x, ok := x.Kind.(*Schema_Filed_String_); ok {
			return x.String_
		}
	}
	return nil
}

func (x *Schema_Filed) GetEnum() *Schema_Filed_Enum {
	if x != nil {
		if x, ok := x.Kind.(*Schema_Filed_Enum_); ok {
			return x.Enum
		}
	}
	return nil
}

func (x *Schema_Filed) GetDuration() *Schema_Filed_Duration {
	if x != nil {
		if x, ok := x.Kind.(*Schema_Filed_Duration_); ok {
			return x.Duration
		}
	}
	return nil
}

func (x *Schema_Filed) GetTimestamp() *Schema_Filed_Timestamp {
	if x != nil {
		if x, ok := x.Kind.(*Schema_Filed_Timestamp_); ok {
			return x.Timestamp
		}
	}
	return nil
}

func (x *Schema_Filed) GetList() *Schema_Filed_List {
	if x != nil {
		if x, ok := x.Kind.(*Schema_Filed_List_); ok {
			return x.List
		}
	}
	return nil
}

func (x *Schema_Filed) GetObject() *Schema_Filed_Object {
	if x != nil {
		if x, ok := x.Kind.(*Schema_Filed_Object_); ok {
			return x.Object
		}
	}
	return nil
}

type isSchema_Filed_Kind interface {
	isSchema_Filed_Kind()
}

type Schema_Filed_Float_ struct {
	// Float field.
	Float *Schema_Filed_Float `protobuf:"bytes,100,opt,name=float,proto3,oneof"`
}

type Schema_Filed_Double_ struct {
	// Double field.
	Double *Schema_Filed_Double `protobuf:"bytes,101,opt,name=double,proto3,oneof"`
}

type Schema_Filed_Int32_ struct {
	// Int32 field.
	Int32 *Schema_Filed_Int32 `protobuf:"bytes,102,opt,name=int32,proto3,oneof"`
}

type Schema_Filed_Int64_ struct {
	// Int64 field.
	Int64 *Schema_Filed_Int64 `protobuf:"bytes,103,opt,name=int64,proto3,oneof"`
}

type Schema_Filed_Uint32 struct {
	// UInt32 field.
	Uint32 *Schema_Filed_UInt32 `protobuf:"bytes,104,opt,name=uint32,proto3,oneof"`
}

type Schema_Filed_Uint64 struct {
	// UInt64 field.
	Uint64 *Schema_Filed_UInt64 `protobuf:"bytes,105,opt,name=uint64,proto3,oneof"`
}

type Schema_Filed_Bool_ struct {
	// Bool field.
	Bool *Schema_Filed_Bool `protobuf:"bytes,106,opt,name=bool,proto3,oneof"`
}

type Schema_Filed_String_ struct {
	// String field.
	String_ *Schema_Filed_String `protobuf:"bytes,107,opt,name=string,proto3,oneof"`
}

type Schema_Filed_Enum_ struct {
	// Enum field.
	Enum *Schema_Filed_Enum `protobuf:"bytes,108,opt,name=enum,proto3,oneof"`
}

type Schema_Filed_Duration_ struct {
	// Duration field.
	Duration *Schema_Filed_Duration `protobuf:"bytes,109,opt,name=duration,proto3,oneof"`
}

type Schema_Filed_Timestamp_ struct {
	// Timestamp field.
	Timestamp *Schema_Filed_Timestamp `protobuf:"bytes,110,opt,name=timestamp,proto3,oneof"`
}

type Schema_Filed_List_ struct {
	// List field.
	List *Schema_Filed_List `protobuf:"bytes,111,opt,name=list,proto3,oneof"`
}

type Schema_Filed_Object_ struct {
	// Nested object field.
	Object *Schema_Filed_Object `protobuf:"bytes,112,opt,name=object,proto3,oneof"`
}

func (*Schema_Filed_Float_) isSchema_Filed_Kind() {}

func (*Schema_Filed_Double_) isSchema_Filed_Kind() {}

func (*Schema_Filed_Int32_) isSchema_Filed_Kind() {}

func (*Schema_Filed_Int64_) isSchema_Filed_Kind() {}

func (*Schema_Filed_Uint32) isSchema_Filed_Kind() {}

func (*Schema_Filed_Uint64) isSchema_Filed_Kind() {}

func (*Schema_Filed_Bool_) isSchema_Filed_Kind() {}

func (*Schema_Filed_String_) isSchema_Filed_Kind() {}

func (*Schema_Filed_Enum_) isSchema_Filed_Kind() {}

func (*Schema_Filed_Duration_) isSchema_Filed_Kind() {}

func (*Schema_Filed_Timestamp_) isSchema_Filed_Kind() {}

func (*Schema_Filed_List_) isSchema_Filed_Kind() {}

func (*Schema_Filed_Object_) isSchema_Filed_Kind() {}

// Float field kind and its single-field constraints.
// gt = exclusive min (> 0), gte = inclusive min (>= 1).
// lt = exclusive max, lte = inclusive max.
type Schema_Filed_Float struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Default value used when the field is unset.
	Default *float32 `protobuf:"fixed32,1,opt,name=default,proto3,oneof" json:"default,omitempty"`
	// Value must equal exactly this.
	Const *float32 `protobuf:"fixed32,2,opt,name=const,proto3,oneof" json:"const,omitempty"`
	// Exclusive minimum: value > gt.
	Gt *float32 `protobuf:"fixed32,3,opt,name=gt,proto3,oneof" json:"gt,omitempty"`
	// Inclusive minimum: value >= gte.
	Gte *float32 `protobuf:"fixed32,4,opt,name=gte,proto3,oneof" json:"gte,omitempty"`
	// Exclusive maximum: value < lt.
	Lt *float32 `protobuf:"fixed32,5,opt,name=lt,proto3,oneof" json:"lt,omitempty"`
	// Inclusive maximum: value <= lte.
	Lte *float32 `protobuf:"fixed32,6,opt,name=lte,proto3,oneof" json:"lte,omitempty"`
	// Value must be one of these.
	In []float32 `protobuf:"fixed32,7,rep,packed,name=in,proto3" json:"in,omitempty"`
	// Value must not be any of these.
	NotIn []float32 `protobuf:"fixed32,8,rep,packed,name=not_in,json=notIn,proto3" json:"not_in,omitempty"`
	// Divisibility: quotient value/multiple_of must be whole.
	MultipleOf    *float32 `protobuf:"fixed32,9,opt,name=multiple_of,json=multipleOf,proto3,oneof" json:"multiple_of,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schema_Filed_Float) Reset() {
	*x = Schema_Filed_Float{}
	mi := &file_schemapb_schema_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schema_Filed_Float) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema_Filed_Float) ProtoMessage() {}

func (x *Schema_Filed_Float) ProtoReflect() protoreflect.Message {
	mi := &file_schemapb_schema_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema_Filed_Float.ProtoReflect.Descriptor instead.
func (*Schema_Filed_Float) Descriptor() ([]byte, []int) {
	return file_schemapb_schema_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *Schema_Filed_Float) GetDefault() float32 {
	if x != nil && x.Default != nil {
		return *x.Default
	}
	return 0
}

func (x *Schema_Filed_Float) GetConst() float32 {
	if x != nil && x.Const != nil {
		return *x.Const
	}
	return 0
}

func (x *Schema_Filed_Float) GetGt() float32 {
	if x != nil && x.Gt != nil {
		return *x.Gt
	}
	return 0
}

func (x *Schema_Filed_Float) GetGte() float32 {
	if x != nil && x.Gte != nil {
		return *x.Gte
	}
	return 0
}

func (x *Schema_Filed_Float) GetLt() float32 {
	if x != nil && x.Lt != nil {
		return *x.Lt
	}
	return 0
}

func (x *Schema_Filed_Float) GetLte() float32 {
	if x != nil && x.Lte != nil {
		return *x.Lte
	}
	return 0
}

func (x *Schema_Filed_Float) GetIn() []float32 {
	if x != nil {
		return x.In
	}
	return nil
}

func (x *Schema_Filed_Float) GetNotIn() []float32 {
	if x != nil {
		return x.NotIn
	}
	return nil
}

func (x *Schema_Filed_Float) GetMultipleOf() float32 {
	if x != nil && x.MultipleOf != nil {
		return *x.MultipleOf
	}
	return 0
}

// Double field kind and its single-field constraints.
type Schema_Filed_Double struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Default value used when the field is unset.
	Default *float64 `protobuf:"fixed64,1,opt,name=default,proto3,oneof" json:"default,omitempty"`
	// Value must equal exactly this.
	Const *float64 `protobuf:"fixed64,2,opt,name=const,proto3,oneof" json:"const,omitempty"`
	// Exclusive minimum: value > gt.
	Gt *float64 `protobuf:"fixed64,3,opt,name=gt,proto3,oneof" json:"gt,omitempty"`
	// Inclusive minimum: value >= gte.
	Gte *float64 `protobuf:"fixed64,4,opt,name=gte,proto3,oneof" json:"gte,omitempty"`
	// Exclusive maximum: value < lt.
	Lt *float64 `protobuf:"fixed64,5,opt,name=lt,proto3,oneof" json:"lt,omitempty"`
	// Inclusive maximum: value <= lte.
	Lte *float64 `protobuf:"fixed64,6,opt,name=lte,proto3,oneof" json:"lte,omitempty"`
	// Value must be one of these.
	In []float64 `protobuf:"fixed64,7,rep,packed,name=in,proto3" json:"in,omitempty"`
	// Value must not be any of these.
	NotIn []float64 `protobuf:"fixed64,8,rep,packed,name=not_in,json=notIn,proto3" json:"not_in,omitempty"`
	// Divisibility: quotient value/multiple_of must be whole.
	MultipleOf    *float64 `protobuf:"fixed64,9,opt,name=multiple_of,json=multipleOf,proto3,oneof" json:"multiple_of,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schema_Filed_Double) Reset() {
	*x = Schema_Filed_Double{}
	mi := &file_schemapb_schema_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schema_Filed_Double) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema_Filed_Double) ProtoMessage() {}

func (x *Schema_Filed_Double) ProtoReflect() protoreflect.Message {
	mi := &file_schemapb_schema_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema_Filed_Double.ProtoReflect.Descriptor instead.
func (*Schema_Filed_Double) Descriptor() ([]byte, []int) {
	return file_schemapb_schema_proto_rawDescGZIP(), []int{0, 0, 1}
}

func (x *Schema_Filed_Double) GetDefault() float64 {
	if x != nil && x.Default != nil {
		return *x.Default
	}
	return 0
}

func (x *Schema_Filed_Double) GetConst() float64 {
	if x != nil && x.Const != nil {
		return *x.Const
	}
	return 0
}

func (x *Schema_Filed_Double) GetGt() float64 {
	if x != nil && x.Gt != nil {
		return *x.Gt
	}
	return 0
}

func (x *Schema_Filed_Double) GetGte() float64 {
	if x != nil && x.Gte != nil {
		return *x.Gte
	}
	return 0
}

func (x *Schema_Filed_Double) GetLt() float64 {
	if x != nil && x.Lt != nil {
		return *x.Lt
	}
	return 0
}

func (x *Schema_Filed_Double) GetLte() float64 {
	if x != nil && x.Lte != nil {
		return *x.Lte
	}
	return 0
}

func (x *Schema_Filed_Double) GetIn() []float64 {
	if x != nil {
		return x.In
	}
	return nil
}

func (x *Schema_Filed_Double) GetNotIn() []float64 {
	if x != nil {
		return x.NotIn
	}
	return nil
}

func (x *Schema_Filed_Double) GetMultipleOf() float64 {
	if x != nil && x.MultipleOf != nil {
		return *x.MultipleOf
	}
	return 0
}

// Int32 field kind and its single-field constraints.
type Schema_Filed_Int32 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Default value used when the field is unset.
	Default *int32 `protobuf:"varint,1,opt,name=default,proto3,oneof" json:"default,omitempty"`
	// Value must equal exactly this.
	Const *int32 `protobuf:"varint,2,opt,name=const,proto3,oneof" json:"const,omitempty"`
	// Exclusive minimum: value > gt.
	Gt *int32 `protobuf:"varint,3,opt,name=gt,proto3,oneof" json:"gt,omitempty"`
	// Inclusive minimum: value >= gte.
	Gte *int32 `protobuf:"varint,4,opt,name=gte,proto3,oneof" json:"gte,omitempty"`
	// Exclusive maximum: value < lt.
	Lt *int32 `protobuf:"varint,5,opt,name=lt,proto3,oneof" json:"lt,omitempty"`
	// Inclusive maximum: value <= lte.
	Lte *int32 `protobuf:"varint,6,opt,name=lte,proto3,oneof" json:"lte,omitempty"`
	// Value must be one of these.
	In []int32 `protobuf:"varint,7,rep,packed,name=in,proto3" json:"in,omitempty"`
	// Value must not be any of these.
	NotIn []int32 `protobuf:"varint,8,rep,packed,name=not_in,json=notIn,proto3" json:"not_in,omitempty"`
	// Divisibility: value % multiple_of must be 0.
	MultipleOf    *int32 `protobuf:"varint,9,opt,name=multiple_of,json=multipleOf,proto3,oneof" json:"multiple_of,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schema_Filed_Int32) Reset() {
	*x = Schema_Filed_Int32{}
	mi := &file_schemapb_schema_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schema_Filed_Int32) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema_Filed_Int32) ProtoMessage() {}

func (x *Schema_Filed_Int32) ProtoReflect() protoreflect.Message {
	mi := &file_schemapb_schema_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema_Filed_Int32.ProtoReflect.Descriptor instead.
func (*Schema_Filed_Int32) Descriptor() ([]byte, []int) {
	return file_schemapb_schema_proto_rawDescGZIP(), []int{0, 0, 2}
}

func (x *Schema_Filed_Int32) GetDefault() int32 {
	if x != nil && x.Default != nil {
		return *x.Default
	}
	return 0
}

func (x *Schema_Filed_Int32) GetConst() int32 {
	if x != nil && x.Const != nil {
		return *x.Const
	}
	return 0
}

func (x *Schema_Filed_Int32) GetGt() int32 {
	if x != nil && x.Gt != nil {
		return *x.Gt
	}
	return 0
}

func (x *Schema_Filed_Int32) GetGte() int32 {
	if x != nil && x.Gte != nil {
		return *x.Gte
	}
	return 0
}

func (x *Schema_Filed_Int32) GetLt() int32 {
	if x != nil && x.Lt != nil {
		return *x.Lt
	}
	return 0
}

func (x *Schema_Filed_Int32) GetLte() int32 {
	if x != nil && x.Lte != nil {
		return *x.Lte
	}
	return 0
}

func (x *Schema_Filed_Int32) GetIn() []int32 {
	if x != nil {
		return x.In
	}
	return nil
}

func (x *Schema_Filed_Int32) GetNotIn() []int32 {
	if x != nil {
		return x.NotIn
	}
	return nil
}

func (x *Schema_Filed_Int32) GetMultipleOf() int32 {
	if x != nil && x.MultipleOf != nil {
		return *x.MultipleOf
	}
	return 0
}

// Int64 field kind and its single-field constraints.
type Schema_Filed_Int64 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Default value used when the field is unset.
	Default *int64 `protobuf:"varint,1,opt,name=default,proto3,oneof" json:"default,omitempty"`
	// Value must equal exactly this.
	Const *int64 `protobuf:"varint,2,opt,name=const,proto3,oneof" json:"const,omitempty"`
	// Exclusive minimum: value > gt.
	Gt *int64 `protobuf:"varint,3,opt,name=gt,proto3,oneof" json:"gt,omitempty"`
	// Inclusive minimum: value >= gte.
	Gte *int64 `protobuf:"varint,4,opt,name=gte,proto3,oneof" json:"gte,omitempty"`
	// Exclusive maximum: value < lt.
	Lt *int64 `protobuf:"varint,5,opt,name=lt,proto3,oneof" json:"lt,omitempty"`
	// Inclusive maximum: value <= lte.
	Lte *int64 `protobuf:"varint,6,opt,name=lte,proto3,oneof" json:"lte,omitempty"`
	// Value must be one of these.
	In []int64 `protobuf:"varint,7,rep,packed,name=in,proto3" json:"in,omitempty"`
	// Value must not be any of these.
	NotIn []int64 `protobuf:"varint,8,rep,packed,name=not_in,json=notIn,proto3" json:"not_in,omitempty"`
	// Divisibility: value % multiple_of must be 0.
	MultipleOf    *int64 `protobuf:"varint,9,opt,name=multiple_of,json=multipleOf,proto3,oneof" json:"multiple_of,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schema_Filed_Int64) Reset() {
	*x = Schema_Filed_Int64{}
	mi := &file_schemapb_schema_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schema_Filed_Int64) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema_Filed_Int64) ProtoMessage() {}

func (x *Schema_Filed_Int64) ProtoReflect() protoreflect.Message {
	mi := &file_schemapb_schema_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema_Filed_Int64.ProtoReflect.Descriptor instead.
func (*Schema_Filed_Int64) Descriptor() ([]byte, []int) {
	return file_schemapb_schema_proto_rawDescGZIP(), []int{0, 0, 3}
}

func (x *Schema_Filed_Int64) GetDefault() int64 {
	if x != nil && x.Default != nil {
		return *x.Default
	}
	return 0
}

func (x *Schema_Filed_Int64) GetConst() int64 {
	if x != nil && x.Const != nil {
		return *x.Const
	}
	return 0
}

func (x *Schema_Filed_Int64) GetGt() int64 {
	if x != nil && x.Gt != nil {
		return *x.Gt
	}
	return 0
}

func (x *Schema_Filed_Int64) GetGte() int64 {
	if x != nil && x.Gte != nil {
		return *x.Gte
	}
	return 0
}

func (x *Schema_Filed_Int64) GetLt() int64 {
	if x != nil && x.Lt != nil {
		return *x.Lt
	}
	return 0
}

func (x *Schema_Filed_Int64) GetLte() int64 {
	if x != nil && x.Lte != nil {
		return *x.Lte
	}
	return 0
}

func (x *Schema_Filed_Int64) GetIn() []int64 {
	if x != nil {
		return x.In
	}
	return nil
}

func (x *Schema_Filed_Int64) GetNotIn() []int64 {
	if x != nil {
		return x.NotIn
	}
	return nil
}

func (x *Schema_Filed_Int64) GetMultipleOf() int64 {
	if x != nil && x.MultipleOf != nil {
		return *x.MultipleOf
	}
	return 0
}

// UInt32 field kind and its single-field constraints.
type Schema_Filed_UInt32 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Default value used when the field is unset.
	Default *uint32 `protobuf:"varint,1,opt,name=default,proto3,oneof" json:"default,omitempty"`
	// Value must equal exactly this.
	Const *uint32 `protobuf:"varint,2,opt,name=const,proto3,oneof" json:"const,omitempty"`
	// Exclusive minimum: value > gt.
	Gt *uint32 `protobuf:"varint,3,opt,name=gt,proto3,oneof" json:"gt,omitempty"`
	// Inclusive minimum: value >= gte.
	Gte *uint32 `protobuf:"varint,4,opt,name=gte,proto3,oneof" json:"gte,omitempty"`
	// Exclusive maximum: value < lt.
	Lt *uint32 `protobuf:"varint,5,opt,name=lt,proto3,oneof" json:"lt,omitempty"`
	// Inclusive maximum: value <= lte.
	Lte *uint32 `protobuf:"varint,6,opt,name=lte,proto3,oneof" json:"lte,omitempty"`
	// Value must be one of these.
	In []uint32 `protobuf:"varint,7,rep,packed,name=in,proto3" json:"in,omitempty"`
	// Value must not be any of these.
	NotIn []uint32 `protobuf:"varint,8,rep,packed,name=not_in,json=notIn,proto3" json:"not_in,omitempty"`
	// Divisibility: value % multiple_of must be 0.
	MultipleOf    *uint32 `protobuf:"varint,9,opt,name=multiple_of,json=multipleOf,proto3,oneof" json:"multiple_of,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schema_Filed_UInt32) Reset() {
	*x = Schema_Filed_UInt32{}
	mi := &file_schemapb_schema_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schema_Filed_UInt32) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema_Filed_UInt32) ProtoMessage() {}

func (x *Schema_Filed_UInt32) ProtoReflect() protoreflect.Message {
	mi := &file_schemapb_schema_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema_Filed_UInt32.ProtoReflect.Descriptor instead.
func (*Schema_Filed_UInt32) Descriptor() ([]byte, []int) {
	return file_schemapb_schema_proto_rawDescGZIP(), []int{0, 0, 4}
}

func (x *Schema_Filed_UInt32) GetDefault() uint32 {
	if x != nil && x.Default != nil {
		return *x.Default
	}
	return 0
}

func (x *Schema_Filed_UInt32) GetConst() uint32 {
	if x != nil && x.Const != nil {
		return *x.Const
	}
	return 0
}

func (x *Schema_Filed_UInt32) GetGt() uint32 {
	if x != nil && x.Gt != nil {
		return *x.Gt
	}
	return 0
}

func (x *Schema_Filed_UInt32) GetGte() uint32 {
	if x != nil && x.Gte != nil {
		return *x.Gte
	}
	return 0
}

func (x *Schema_Filed_UInt32) GetLt() uint32 {
	if x != nil && x.Lt != nil {
		return *x.Lt
	}
	return 0
}

func (x *Schema_Filed_UInt32) GetLte() uint32 {
	if x != nil && x.Lte != nil {
		return *x.Lte
	}
	return 0
}

func (x *Schema_Filed_UInt32) GetIn() []uint32 {
	if x != nil {
		return x.In
	}
	return nil
}

func (x *Schema_Filed_UInt32) GetNotIn() []uint32 {
	if x != nil {
		return x.NotIn
	}
	return nil
}

func (x *Schema_Filed_UInt32) GetMultipleOf() uint32 {
	if x != nil && x.MultipleOf != nil {
		return *x.MultipleOf
	}
	return 0
}

// UInt64 field kind and its single-field constraints.
type Schema_Filed_UInt64 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Default value used when the field is unset.
	Default *uint64 `protobuf:"varint,1,opt,name=default,proto3,oneof" json:"default,omitempty"`
	// Value must equal exactly this.
	Const *uint64 `protobuf:"varint,2,opt,name=const,proto3,oneof" json:"const,omitempty"`
	// Exclusive minimum: value > gt.
	Gt *uint64 `protobuf:"varint,3,opt,name=gt,proto3,oneof" json:"gt,omitempty"`
	// Inclusive minimum: value >= gte.
	Gte *uint64 `protobuf:"varint,4,opt,name=gte,proto3,oneof" json:"gte,omitempty"`
	// Exclusive maximum: value < lt.
	Lt *uint64 `protobuf:"varint,5,opt,name=lt,proto3,oneof" json:"lt,omitempty"`
	// Inclusive maximum: value <= lte.
	Lte *uint64 `protobuf:"varint,6,opt,name=lte,proto3,oneof" json:"lte,omitempty"`
	// Value must be one of these.
	In []uint64 `protobuf:"varint,7,rep,packed,name=in,proto3" json:"in,omitempty"`
	// Value must not be any of these.
	NotIn []uint64 `protobuf:"varint,8,rep,packed,name=not_in,json=notIn,proto3" json:"not_in,omitempty"`
	// Divisibility: value % multiple_of must be 0.
	MultipleOf    *uint64 `protobuf:"varint,9,opt,name=multiple_of,json=multipleOf,proto3,oneof" json:"multiple_of,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schema_Filed_UInt64) Reset() {
	*x = Schema_Filed_UInt64{}
	mi := &file_schemapb_schema_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schema_Filed_UInt64) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema_Filed_UInt64) ProtoMessage() {}

func (x *Schema_Filed_UInt64) ProtoReflect() protoreflect.Message {
	mi := &file_schemapb_schema_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema_Filed_UInt64.ProtoReflect.Descriptor instead.
func (*Schema_Filed_UInt64) Descriptor() ([]byte, []int) {
	return file_schemapb_schema_proto_rawDescGZIP(), []int{0, 0, 5}
}

func (x *Schema_Filed_UInt64) GetDefault() uint64 {
	if x != nil && x.Default != nil {
		return *x.Default
	}
	return 0
}

func (x *Schema_Filed_UInt64) GetConst() uint64 {
	if x != nil && x.Const != nil {
		return *x.Const
	}
	return 0
}

func (x *Schema_Filed_UInt64) GetGt() uint64 {
	if x != nil && x.Gt != nil {
		return *x.Gt
	}
	return 0
}

func (x *Schema_Filed_UInt64) GetGte() uint64 {
	if x != nil && x.Gte != nil {
		return *x.Gte
	}
	return 0
}

func (x *Schema_Filed_UInt64) GetLt() uint64 {
	if x != nil && x.Lt != nil {
		return *x.Lt
	}
	return 0
}

func (x *Schema_Filed_UInt64) GetLte() uint64 {
	if x != nil && x.Lte != nil {
		return *x.Lte
	}
	return 0
}

func (x *Schema_Filed_UInt64) GetIn() []uint64 {
	if x != nil {
		return x.In
	}
	return nil
}

func (x *Schema_Filed_UInt64) GetNotIn() []uint64 {
	if x != nil {
		return x.NotIn
	}
	return nil
}

func (x *Schema_Filed_UInt64) GetMultipleOf() uint64 {
	if x != nil && x.MultipleOf != nil {
		return *x.MultipleOf
	}
	return 0
}

// Bool field kind.
type Schema_Filed_Bool struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Default value used when the field is unset.
	Default *bool `protobuf:"varint,1,opt,name=default,proto3,oneof" json:"default,omitempty"`
	// Value must equal exactly this.
	Const         *bool `protobuf:"varint,2,opt,name=const,proto3,oneof" json:"const,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schema_Filed_Bool) Reset() {
	*x = Schema_Filed_Bool{}
	mi := &file_schemapb_schema_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schema_Filed_Bool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema_Filed_Bool) ProtoMessage() {}

func (x *Schema_Filed_Bool) ProtoReflect() protoreflect.Message {
	mi := &file_schemapb_schema_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema_Filed_Bool.ProtoReflect.Descriptor instead.
func (*Schema_Filed_Bool) Descriptor() ([]byte, []int) {
	return file_schemapb_schema_proto_rawDescGZIP(), []int{0, 0, 6}
}

func (x *Schema_Filed_Bool) GetDefault() bool {
	if x != nil && x.Default != nil {
		return *x.Default
	}
	return false
}

func (x *Schema_Filed_Bool) GetConst() bool {
	if x != nil && x.Const != nil {
		return *x.Const
	}
	return false
}

// String field kind and its single-field constraints.
type Schema_Filed_String struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Default value used when the field is unset.
	Default *string `protobuf:"bytes,1,opt,name=default,proto3,oneof" json:"default,omitempty"`
	// Value must equal exactly this.
	Const *string `protobuf:"bytes,2,opt,name=const,proto3,oneof" json:"const,omitempty"`
	// Exact character length required.
	Len *uint64 `protobuf:"varint,3,opt,name=len,proto3,oneof" json:"len,omitempty"`
	// Minimum character length.
	MinLen *uint64 `protobuf:"varint,4,opt,name=min_len,json=minLen,proto3,oneof" json:"min_len,omitempty"`
	// Maximum character length.
	MaxLen *uint64 `protobuf:"varint,5,opt,name=max_len,json=maxLen,proto3,oneof" json:"max_len,omitempty"`
	// RE2 regular expression the value must match.
	Pattern *string `protobuf:"bytes,6,opt,name=pattern,proto3,oneof" json:"pattern,omitempty"`
	// Value must be one of these.
	In []string `protobuf:"bytes,7,rep,name=in,proto3" json:"in,omitempty"`
	// Value must not be any of these.
	NotIn         []string `protobuf:"bytes,8,rep,name=not_in,json=notIn,proto3" json:"not_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schema_Filed_String) Reset() {
	*x = Schema_Filed_String{}
	mi := &file_schemapb_schema_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schema_Filed_String) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema_Filed_String) ProtoMessage() {}

func (x *Schema_Filed_String) ProtoReflect() protoreflect.Message {
	mi := &file_schemapb_schema_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema_Filed_String.ProtoReflect.Descriptor instead.
func (*Schema_Filed_String) Descriptor() ([]byte, []int) {
	return file_schemapb_schema_proto_rawDescGZIP(), []int{0, 0, 7}
}

func (x *Schema_Filed_String) GetDefault() string {
	if x != nil && x.Default != nil {
		return *x.Default
	}
	return ""
}

func (x *Schema_Filed_String) GetConst() string {
	if x != nil && x.Const != nil {
		return *x.Const
	}
	return ""
}

func (x *Schema_Filed_String) GetLen() uint64 {
	if x != nil && x.Len != nil {
		return *x.Len
	}
	return 0
}

func (x *Schema_Filed_String) GetMinLen() uint64 {
	if x != nil && x.MinLen != nil {
		return *x.MinLen
	}
	return 0
}

func (x *Schema_Filed_String) GetMaxLen() uint64 {
	if x != nil && x.MaxLen != nil {
		return *x.MaxLen
	}
	return 0
}

func (x *Schema_Filed_String) GetPattern() string {
	if x != nil && x.Pattern != nil {
		return *x.Pattern
	}
	return ""
}

func (x *Schema_Filed_String) GetIn() []string {
	if x != nil {
		return x.In
	}
	return nil
}

func (x *Schema_Filed_String) GetNotIn() []string {
	if x != nil {
		return x.NotIn
	}
	return nil
}

// Enum field kind: an integer value with human labels.
type Schema_Filed_Enum struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Default value used when the field is unset.
	Default *int32 `protobuf:"varint,1,opt,name=default,proto3,oneof" json:"default,omitempty"`
	// Allowed enum values: integer -> human label.
	Values map[int32]string `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// If true, value must be one of the keys in values.
	DefinedOnly bool `protobuf:"varint,3,opt,name=defined_only,json=definedOnly,proto3" json:"defined_only,omitempty"`
	// Value must be one of these.
	In []int32 `protobuf:"varint,4,rep,packed,name=in,proto3" json:"in,omitempty"`
	// Value must not be any of these.
	NotIn         []int32 `protobuf:"varint,5,rep,packed,name=not_in,json=notIn,proto3" json:"not_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schema_Filed_Enum) Reset() {
	*x = Schema_Filed_Enum{}
	mi := &file_schemapb_schema_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schema_Filed_Enum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema_Filed_Enum) ProtoMessage() {}

func (x *Schema_Filed_Enum) ProtoReflect() protoreflect.Message {
	mi := &file_schemapb_schema_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema_Filed_Enum.ProtoReflect.Descriptor instead.
func (*Schema_Filed_Enum) Descriptor() ([]byte, []int) {
	return file_schemapb_schema_proto_rawDescGZIP(), []int{0, 0, 8}
}

func (x *Schema_Filed_Enum) GetDefault() int32 {
	if x != nil && x.Default != nil {
		return *x.Default
	}
	return 0
}

func (x *Schema_Filed_Enum) GetValues() map[int32]string {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *Schema_Filed_Enum) GetDefinedOnly() bool {
	if x != nil {
		return x.DefinedOnly
	}
	return false
}

func (x *Schema_Filed_Enum) GetIn() []int32 {
	if x != nil {
		return x.In
	}
	return nil
}

func (x *Schema_Filed_Enum) GetNotIn() []int32 {
	if x != nil {
		return x.NotIn
	}
	return nil
}

// Duration field kind with optional range bounds.
type Schema_Filed_Duration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Default value used when the field is unset.
	Default *durationpb.Duration `protobuf:"bytes,1,opt,name=default,proto3,oneof" json:"default,omitempty"`
	// Exclusive minimum: value > gt.
	Gt *durationpb.Duration `protobuf:"bytes,2,opt,name=gt,proto3,oneof" json:"gt,omitempty"`
	// Inclusive minimum: value >= gte.
	Gte *durationpb.Duration `protobuf:"bytes,3,opt,name=gte,proto3,oneof" json:"gte,omitempty"`
	// Exclusive maximum: value < lt.
	Lt *durationpb.Duration `protobuf:"bytes,4,opt,name=lt,proto3,oneof" json:"lt,omitempty"`
	// Inclusive maximum: value <= lte.
	Lte           *durationpb.Duration `protobuf:"bytes,5,opt,name=lte,proto3,oneof" json:"lte,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schema_Filed_Duration) Reset() {
	*x = Schema_Filed_Duration{}
	mi := &file_schemapb_schema_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schema_Filed_Duration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema_Filed_Duration) ProtoMessage() {}

func (x *Schema_Filed_Duration) ProtoReflect() protoreflect.Message {
	mi := &file_schemapb_schema_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema_Filed_Duration.ProtoReflect.Descriptor instead.
func (*Schema_Filed_Duration) Descriptor() ([]byte, []int) {
	return file_schemapb_schema_proto_rawDescGZIP(), []int{0, 0, 9}
}

func (x *Schema_Filed_Duration) GetDefault() *durationpb.Duration {
	if x != nil {
		return x.Default
	}
	return nil
}

func (x *Schema_Filed_Duration) GetGt() *durationpb.Duration {
	if x != nil {
		return x.Gt
	}
	return nil
}

func (x *Schema_Filed_Duration) GetGte() *durationpb.Duration {
	if x != nil {
		return x.Gte
	}
	return nil
}

func (x *Schema_Filed_Duration) GetLt() *durationpb.Duration {
	if x != nil {
		return x.Lt
	}
	return nil
}

func (x *Schema_Filed_Duration) GetLte() *durationpb.Duration {
	if x != nil {
		return x.Lte
	}
	return nil
}

// Timestamp field kind with optional range bounds.
type Schema_Filed_Timestamp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Default value used when the field is unset.
	Default *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=default,proto3,oneof" json:"default,omitempty"`
	// Exclusive minimum: value > gt.
	Gt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=gt,proto3,oneof" json:"gt,omitempty"`
	// Inclusive minimum: value >= gte.
	Gte *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=gte,proto3,oneof" json:"gte,omitempty"`
	// Exclusive maximum: value < lt.
	Lt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=lt,proto3,oneof" json:"lt,omitempty"`
	// Inclusive maximum: value <= lte.
	Lte           *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=lte,proto3,oneof" json:"lte,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schema_Filed_Timestamp) Reset() {
	*x = Schema_Filed_Timestamp{}
	mi := &file_schemapb_schema_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schema_Filed_Timestamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema_Filed_Timestamp) ProtoMessage() {}

func (x *Schema_Filed_Timestamp) ProtoReflect() protoreflect.Message {
	mi := &file_schemapb_schema_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema_Filed_Timestamp.ProtoReflect.Descriptor instead.
func (*Schema_Filed_Timestamp) Descriptor() ([]byte, []int) {
	return file_schemapb_schema_proto_rawDescGZIP(), []int{0, 0, 10}
}

func (x *Schema_Filed_Timestamp) GetDefault() *timestamppb.Timestamp {
	if x != nil {
		return x.Default
	}
	return nil
}

func (x *Schema_Filed_Timestamp) GetGt() *timestamppb.Timestamp {
	if x != nil {
		return x.Gt
	}
	return nil
}

func (x *Schema_Filed_Timestamp) GetGte() *timestamppb.Timestamp {
	if x != nil {
		return x.Gte
	}
	return nil
}

func (x *Schema_Filed_Timestamp) GetLt() *timestamppb.Timestamp {
	if x != nil {
		return x.Lt
	}
	return nil
}

func (x *Schema_Filed_Timestamp) GetLte() *timestamppb.Timestamp {
	if x != nil {
		return x.Lte
	}
	return nil
}

// List field kind: a repeated value described by its element field(s).
type Schema_Filed_List struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Element field definition(s) describing list items.
	Items []*Schema_Filed `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	// Minimum number of items.
	MinItems *uint64 `protobuf:"varint,2,opt,name=min_items,json=minItems,proto3,oneof" json:"min_items,omitempty"`
	// Maximum number of items.
	MaxItems *uint64 `protobuf:"varint,3,opt,name=max_items,json=maxItems,proto3,oneof" json:"max_items,omitempty"`
	// If true, items must be unique.
	Unique        bool `protobuf:"varint,4,opt,name=unique,proto3" json:"unique,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schema_Filed_List) Reset() {
	*x = Schema_Filed_List{}
	mi := &file_schemapb_schema_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schema_Filed_List) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema_Filed_List) ProtoMessage() {}

func (x *Schema_Filed_List) ProtoReflect() protoreflect.Message {
	mi := &file_schemapb_schema_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema_Filed_List.ProtoReflect.Descriptor instead.
func (*Schema_Filed_List) Descriptor() ([]byte, []int) {
	return file_schemapb_schema_proto_rawDescGZIP(), []int{0, 0, 11}
}

func (x *Schema_Filed_List) GetItems() []*Schema_Filed {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Schema_Filed_List) GetMinItems() uint64 {
	if x != nil && x.MinItems != nil {
		return *x.MinItems
	}
	return 0
}

func (x *Schema_Filed_List) GetMaxItems() uint64 {
	if x != nil && x.MaxItems != nil {
		return *x.MaxItems
	}
	return 0
}

func (x *Schema_Filed_List) GetUnique() bool {
	if x != nil {
		return x.Unique
	}
	return false
}

// Object field kind: a nested sub-form described by its own Schema.
type Schema_Filed_Object struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Nested object schema.
	Schema        *Schema `protobuf:"bytes,1,opt,name=schema,proto3,oneof" json:"schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schema_Filed_Object) Reset() {
	*x = Schema_Filed_Object{}
	mi := &file_schemapb_schema_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schema_Filed_Object) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema_Filed_Object) ProtoMessage() {}

func (x *Schema_Filed_Object) ProtoReflect() protoreflect.Message {
	mi := &file_schemapb_schema_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema_Filed_Object.ProtoReflect.Descriptor instead.
func (*Schema_Filed_Object) Descriptor() ([]byte, []int) {
	return file_schemapb_schema_proto_rawDescGZIP(), []int{0, 0, 12}
}

func (x *Schema_Filed_Object) GetSchema() *Schema {
	if x != nil {
		return x.Schema
	}
	return nil
}

// UI carries render hints: how to draw the field. Numeric bounds and step
// are introspected from the per-kind structured rules (gte/lte/multiple_of).
type Schema_Filed_UI struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Human label; falls back to Filed.name.
	Label *string `protobuf:"bytes,1,opt,name=label,proto3,oneof" json:"label,omitempty"`
	// Help text; falls back to Filed.description.
	Help *string `protobuf:"bytes,2,opt,name=help,proto3,oneof" json:"help,omitempty"`
	// Placeholder text for empty inputs.
	Placeholder *string `protobuf:"bytes,3,opt,name=placeholder,proto3,oneof" json:"placeholder,omitempty"`
	// Explicit widget; if unset the renderer defaults by field kind.
	Widget *Schema_Filed_UI_Widget `protobuf:"varint,4,opt,name=widget,proto3,enum=cloud.v1.common.Schema_Filed_UI_Widget,oneof" json:"widget,omitempty"`
	// Display suffix; the value is stored in this unit.
	Unit *string `protobuf:"bytes,5,opt,name=unit,proto3,oneof" json:"unit,omitempty"`
	// Input increment; if unset it is derived from multiple_of.
	Step *float64 `protobuf:"fixed64,6,opt,name=step,proto3,oneof" json:"step,omitempty"`
	// Section key used to group fields in the form.
	Group *string `protobuf:"bytes,7,opt,name=group,proto3,oneof" json:"group,omitempty"`
	// Sort order of the field within the form.
	Order *int32 `protobuf:"varint,8,opt,name=order,proto3,oneof" json:"order,omitempty"`
	// If true, hide the field behind an "advanced" toggle.
	Advanced *bool `protobuf:"varint,9,opt,name=advanced,proto3,oneof" json:"advanced,omitempty"`
	// CEL bool; the field is rendered only when this is true.
	VisibleIf *string `protobuf:"bytes,10,opt,name=visible_if,json=visibleIf,proto3,oneof" json:"visible_if,omitempty"`
	// CEL bool; the field is enabled only when this is true.
	EnabledIf     *string `protobuf:"bytes,11,opt,name=enabled_if,json=enabledIf,proto3,oneof" json:"enabled_if,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schema_Filed_UI) Reset() {
	*x = Schema_Filed_UI{}
	mi := &file_schemapb_schema_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schema_Filed_UI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema_Filed_UI) ProtoMessage() {}

func (x *Schema_Filed_UI) ProtoReflect() protoreflect.Message {
	mi := &file_schemapb_schema_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema_Filed_UI.ProtoReflect.Descriptor instead.
func (*Schema_Filed_UI) Descriptor() ([]byte, []int) {
	return file_schemapb_schema_proto_rawDescGZIP(), []int{0, 0, 13}
}

func (x *Schema_Filed_UI) GetLabel() string {
	if x != nil && x.Label != nil {
		return *x.Label
	}
	return ""
}

func (x *Schema_Filed_UI) GetHelp() string {
	if x != nil && x.Help != nil {
		return *x.Help
	}
	return ""
}

func (x *Schema_Filed_UI) GetPlaceholder() string {
	if x != nil && x.Placeholder != nil {
		return *x.Placeholder
	}
	return ""
}

func (x *Schema_Filed_UI) GetWidget() Schema_Filed_UI_Widget {
	if x != nil && x.Widget != nil {
		return *x.Widget
	}
	return Schema_Filed_UI_WIDGET_UNSPECIFIED
}

func (x *Schema_Filed_UI) GetUnit() string {
	if x != nil && x.Unit != nil {
		return *x.Unit
	}
	return ""
}

func (x *Schema_Filed_UI) GetStep() float64 {
	if x != nil && x.Step != nil {
		return *x.Step
	}
	return 0
}

func (x *Schema_Filed_UI) GetGroup() string {
	if x != nil && x.Group != nil {
		return *x.Group
	}
	return ""
}

func (x *Schema_Filed_UI) GetOrder() int32 {
	if x != nil && x.Order != nil {
		return *x.Order
	}
	return 0
}

func (x *Schema_Filed_UI) GetAdvanced() bool {
	if x != nil && x.Advanced != nil {
		return *x.Advanced
	}
	return false
}

func (x *Schema_Filed_UI) GetVisibleIf() string {
	if x != nil && x.VisibleIf != nil {
		return *x.VisibleIf
	}
	return ""
}

func (x *Schema_Filed_UI) GetEnabledIf() string {
	if x != nil && x.EnabledIf != nil {
		return *x.EnabledIf
	}
	return ""
}

// Rule is a CEL validation expression for cross-field / conditional checks.
// Context: `this` = this field's value (field-level rules only);
//
//	`root` = whole form as map<string, dyn>, any field reachable.
//
// expr must evaluate to bool; true means VALID.
type Schema_Filed_Rule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// CEL boolean expression; true means the value is valid.
	Expr string `protobuf:"bytes,1,opt,name=expr,proto3" json:"expr,omitempty"`
	// Message shown to the user when expr is false.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Stable rule id, for mapping errors back to rules.
	Id *string `protobuf:"bytes,3,opt,name=id,proto3,oneof" json:"id,omitempty"`
	// Severity; defaults to ERROR.
	Severity      *Schema_Filed_Severity `protobuf:"varint,4,opt,name=severity,proto3,enum=cloud.v1.common.Schema_Filed_Severity,oneof" json:"severity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schema_Filed_Rule) Reset() {
	*x = Schema_Filed_Rule{}
	mi := &file_schemapb_schema_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schema_Filed_Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema_Filed_Rule) ProtoMessage() {}

func (x *Schema_Filed_Rule) ProtoReflect() protoreflect.Message {
	mi := &file_schemapb_schema_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema_Filed_Rule.ProtoReflect.Descriptor instead.
func (*Schema_Filed_Rule) Descriptor() ([]byte, []int) {
	return file_schemapb_schema_proto_rawDescGZIP(), []int{0, 0, 14}
}

func (x *Schema_Filed_Rule) GetExpr() string {
	if x != nil {
		return x.Expr
	}
	return ""
}

func (x *Schema_Filed_Rule) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Schema_Filed_Rule) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *Schema_Filed_Rule) GetSeverity() Schema_Filed_Severity {
	if x != nil && x.Severity != nil {
		return *x.Severity
	}
	return Schema_Filed_SEVERITY_UNSPECIFIED
}

var File_schemapb_schema_proto protoreflect.FileDescriptor

const file_schemapb_schema_proto_rawDesc = "" +
	"\n" +
	"\x15schemapb/schema.proto\x12\x0fcloud.v1.common\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbf*\n" +
	"\x06Schema\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01\x125\n" +
	"\x06fields\x18\x02 \x03(\v2\x1d.cloud.v1.common.Schema.FiledR\x06fields\x128\n" +
	"\x05rules\x18\x03 \x03(\v2\".cloud.v1.common.Schema.Filed.RuleR\x05rules\x1a\xa1)\n" +
	"\x05Filed\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x02 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\x1a\n" +
	"\bnullable\x18\x03 \x01(\bR\bnullable\x12\x1a\n" +
	"\brequired\x18\x04 \x01(\bR\brequired\x120\n" +
	"\x02ui\x18\x05 \x01(\v2 .cloud.v1.common.Schema.Filed.UIR\x02ui\x128\n" +
	"\x05rules\x18\x06 \x03(\v2\".cloud.v1.common.Schema.Filed.RuleR\x05rules\x12;\n" +
	"\x05float\x18d \x01(\v2#.cloud.v1.common.Schema.Filed.FloatH\x00R\x05float\x12>\n" +
	"\x06double\x18e \x01(\v2$.cloud.v1.common.Schema.Filed.DoubleH\x00R\x06double\x12;\n" +
	"\x05int32\x18f \x01(\v2#.cloud.v1.common.Schema.Filed.Int32H\x00R\x05int32\x12;\n" +
	"\x05int64\x18g \x01(\v2#.cloud.v1.common.Schema.Filed.Int64H\x00R\x05int64\x12>\n" +
	"\x06uint32\x18h \x01(\v2$.cloud.v1.common.Schema.Filed.UInt32H\x00R\x06uint32\x12>\n" +
	"\x06uint64\x18i \x01(\v2$.cloud.v1.common.Schema.Filed.UInt64H\x00R\x06uint64\x128\n" +
	"\x04bool\x18j \x01(\v2\".cloud.v1.common.Schema.Filed.BoolH\x00R\x04bool\x12>\n" +
	"\x06string\x18k \x01(\v2$.cloud.v1.common.Schema.Filed.StringH\x00R\x06string\x128\n" +
	"\x04enum\x18l \x01(\v2\".cloud.v1.common.Schema.Filed.EnumH\x00R\x04enum\x12D\n" +
	"\bduration\x18m \x01(\v2&.cloud.v1.common.Schema.Filed.DurationH\x00R\bduration\x12G\n" +
	"\ttimestamp\x18n \x01(\v2'.cloud.v1.common.Schema.Filed.TimestampH\x00R\ttimestamp\x128\n" +
	"\x04list\x18o \x01(\v2\".cloud.v1.common.Schema.Filed.ListH\x00R\x04list\x12>\n" +
	"\x06object\x18p \x01(\v2$.cloud.v1.common.Schema.Filed.ObjectH\x00R\x06object\x1a\xaa\x02\n" +
	"\x05Float\x12\x1d\n" +
	"\adefault\x18\x01 \x01(\x02H\x00R\adefault\x88\x01\x01\x12\x19\n" +
	"\x05const\x18\x02 \x01(\x02H\x01R\x05const\x88\x01\x01\x12\x13\n" +
	"\x02gt\x18\x03 \x01(\x02H\x02R\x02gt\x88\x01\x01\x12\x15\n" +
	"\x03gte\x18\x04 \x01(\x02H\x03R\x03gte\x88\x01\x01\x12\x13\n" +
	"\x02lt\x18\x05 \x01(\x02H\x04R\x02lt\x88\x01\x01\x12\x15\n" +
	"\x03lte\x18\x06 \x01(\x02H\x05R\x03lte\x88\x01\x01\x12\x0e\n" +
	"\x02in\x18\a \x03(\x02R\x02in\x12\x15\n" +
	"\x06not_in\x18\b \x03(\x02R\x05notIn\x12$\n" +
	"\vmultiple_of\x18\t \x01(\x02H\x06R\n" +
	"multipleOf\x88\x01\x01B\n" +
	"\n" +
	"\b_defaultB\b\n" +
	"\x06_constB\x05\n" +
	"\x03_gtB\x06\n" +
	"\x04_gteB\x05\n" +
	"\x03_ltB\x06\n" +
	"\x04_lteB\x0e\n" +
	"\f_multiple_of\x1a\xab\x02\n" +
	"\x06Double\x12\x1d\n" +
	"\adefault\x18\x01 \x01(\x01H\x00R\adefault\x88\x01\x01\x12\x19\n" +
	"\x05const\x18\x02 \x01(\x01H\x01R\x05const\x88\x01\x01\x12\x13\n" +
	"\x02gt\x18\x03 \x01(\x01H\x02R\x02gt\x88\x01\x01\x12\x15\n" +
	"\x03gte\x18\x04 \x01(\x01H\x03R\x03gte\x88\x01\x01\x12\x13\n" +
	"\x02lt\x18\x05 \x01(\x01H\x04R\x02lt\x88\x01\x01\x12\x15\n" +
	"\x03lte\x18\x06 \x01(\x01H\x05R\x03lte\x88\x01\x01\x12\x0e\n" +
	"\x02in\x18\a \x03(\x01R\x02in\x12\x15\n" +
	"\x06not_in\x18\b \x03(\x01R\x05notIn\x12$\n" +
	"\vmultiple_of\x18\t \x01(\x01H\x06R\n" +
	"multipleOf\x88\x01\x01B\n" +
	"\n" +
	"\b_defaultB\b\n" +
	"\x06_constB\x05\n" +
	"\x03_gtB\x06\n" +
	"\x04_gteB\x05\n" +
	"\x03_ltB\x06\n" +
	"\x04_lteB\x0e\n" +
	"\f_multiple_of\x1a\xaa\x02\n" +
	"\x05Int32\x12\x1d\n" +
	"\adefault\x18\x01 \x01(\x05H\x00R\adefault\x88\x01\x01\x12\x19\n" +
	"\x05const\x18\x02 \x01(\x05H\x01R\x05const\x88\x01\x01\x12\x13\n" +
	"\x02gt\x18\x03 \x01(\x05H\x02R\x02gt\x88\x01\x01\x12\x15\n" +
	"\x03gte\x18\x04 \x01(\x05H\x03R\x03gte\x88\x01\x01\x12\x13\n" +
	"\x02lt\x18\x05 \x01(\x05H\x04R\x02lt\x88\x01\x01\x12\x15\n" +
	"\x03lte\x18\x06 \x01(\x05H\x05R\x03lte\x88\x01\x01\x12\x0e\n" +
	"\x02in\x18\a \x03(\x05R\x02in\x12\x15\n" +
	"\x06not_in\x18\b \x03(\x05R\x05notIn\x12$\n" +
	"\vmultiple_of\x18\t \x01(\x05H\x06R\n" +
	"multipleOf\x88\x01\x01B\n" +
	"\n" +
	"\b_defaultB\b\n" +
	"\x06_constB\x05\n" +
	"\x03_gtB\x06\n" +
	"\x04_gteB\x05\n" +
	"\x03_ltB\x06\n" +
	"\x04_lteB\x0e\n" +
	"\f_multiple_of\x1a\xaa\x02\n" +
	"\x05Int64\x12\x1d\n" +
	"\adefault\x18\x01 \x01(\x03H\x00R\adefault\x88\x01\x01\x12\x19\n" +
	"\x05const\x18\x02 \x01(\x03H\x01R\x05const\x88\x01\x01\x12\x13\n" +
	"\x02gt\x18\x03 \x01(\x03H\x02R\x02gt\x88\x01\x01\x12\x15\n" +
	"\x03gte\x18\x04 \x01(\x03H\x03R\x03gte\x88\x01\x01\x12\x13\n" +
	"\x02lt\x18\x05 \x01(\x03H\x04R\x02lt\x88\x01\x01\x12\x15\n" +
	"\x03lte\x18\x06 \x01(\x03H\x05R\x03lte\x88\x01\x01\x12\x0e\n" +
	"\x02in\x18\a \x03(\x03R\x02in\x12\x15\n" +
	"\x06not_in\x18\b \x03(\x03R\x05notIn\x12$\n" +
	"\vmultiple_of\x18\t \x01(\x03H\x06R\n" +
	"multipleOf\x88\x01\x01B\n" +
	"\n" +
	"\b_defaultB\b\n" +
	"\x06_constB\x05\n" +
	"\x03_gtB\x06\n" +
	"\x04_gteB\x05\n" +
	"\x03_ltB\x06\n" +
	"\x04_lteB\x0e\n" +
	"\f_multiple_of\x1a\xab\x02\n" +
	"\x06UInt32\x12\x1d\n" +
	"\adefault\x18\x01 \x01(\rH\x00R\adefault\x88\x01\x01\x12\x19\n" +
	"\x05const\x18\x02 \x01(\rH\x01R\x05const\x88\x01\x01\x12\x13\n" +
	"\x02gt\x18\x03 \x01(\rH\x02R\x02gt\x88\x01\x01\x12\x15\n" +
	"\x03gte\x18\x04 \x01(\rH\x03R\x03gte\x88\x01\x01\x12\x13\n" +
	"\x02lt\x18\x05 \x01(\rH\x04R\x02lt\x88\x01\x01\x12\x15\n" +
	"\x03lte\x18\x06 \x01(\rH\x05R\x03lte\x88\x01\x01\x12\x0e\n" +
	"\x02in\x18\a \x03(\rR\x02in\x12\x15\n" +
	"\x06not_in\x18\b \x03(\rR\x05notIn\x12$\n" +
	"\vmultiple_of\x18\t \x01(\rH\x06R\n" +
	"multipleOf\x88\x01\x01B\n" +
	"\n" +
	"\b_defaultB\b\n" +
	"\x06_constB\x05\n" +
	"\x03_gtB\x06\n" +
	"\x04_gteB\x05\n" +
	"\x03_ltB\x06\n" +
	"\x04_lteB\x0e\n" +
	"\f_multiple_of\x1a\xab\x02\n" +
	"\x06UInt64\x12\x1d\n" +
	"\adefault\x18\x01 \x01(\x04H\x00R\adefault\x88\x01\x01\x12\x19\n" +
	"\x05const\x18\x02 \x01(\x04H\x01R\x05const\x88\x01\x01\x12\x13\n" +
	"\x02gt\x18\x03 \x01(\x04H\x02R\x02gt\x88\x01\x01\x12\x15\n" +
	"\x03gte\x18\x04 \x01(\x04H\x03R\x03gte\x88\x01\x01\x12\x13\n" +
	"\x02lt\x18\x05 \x01(\x04H\x04R\x02lt\x88\x01\x01\x12\x15\n" +
	"\x03lte\x18\x06 \x01(\x04H\x05R\x03lte\x88\x01\x01\x12\x0e\n" +
	"\x02in\x18\a \x03(\x04R\x02in\x12\x15\n" +
	"\x06not_in\x18\b \x03(\x04R\x05notIn\x12$\n" +
	"\vmultiple_of\x18\t \x01(\x04H\x06R\n" +
	"multipleOf\x88\x01\x01B\n" +
	"\n" +
	"\b_defaultB\b\n" +
	"\x06_constB\x05\n" +
	"\x03_gtB\x06\n" +
	"\x04_gteB\x05\n" +
	"\x03_ltB\x06\n" +
	"\x04_lteB\x0e\n" +
	"\f_multiple_of\x1aV\n" +
	"\x04Bool\x12\x1d\n" +
	"\adefault\x18\x01 \x01(\bH\x00R\adefault\x88\x01\x01\x12\x19\n" +
	"\x05const\x18\x02 \x01(\bH\x01R\x05const\x88\x01\x01B\n" +
	"\n" +
	"\b_defaultB\b\n" +
	"\x06_const\x1a\x9d\x02\n" +
	"\x06String\x12\x1d\n" +
	"\adefault\x18\x01 \x01(\tH\x00R\adefault\x88\x01\x01\x12\x19\n" +
	"\x05const\x18\x02 \x01(\tH\x01R\x05const\x88\x01\x01\x12\x15\n" +
	"\x03len\x18\x03 \x01(\x04H\x02R\x03len\x88\x01\x01\x12\x1c\n" +
	"\amin_len\x18\x04 \x01(\x04H\x03R\x06minLen\x88\x01\x01\x12\x1c\n" +
	"\amax_len\x18\x05 \x01(\x04H\x04R\x06maxLen\x88\x01\x01\x12\x1d\n" +
	"\apattern\x18\x06 \x01(\tH\x05R\apattern\x88\x01\x01\x12\x0e\n" +
	"\x02in\x18\a \x03(\tR\x02in\x12\x15\n" +
	"\x06not_in\x18\b \x03(\tR\x05notInB\n" +
	"\n" +
	"\b_defaultB\b\n" +
	"\x06_constB\x06\n" +
	"\x04_lenB\n" +
	"\n" +
	"\b_min_lenB\n" +
	"\n" +
	"\b_max_lenB\n" +
	"\n" +
	"\b_pattern\x1a\xfe\x01\n" +
	"\x04Enum\x12\x1d\n" +
	"\adefault\x18\x01 \x01(\x05H\x00R\adefault\x88\x01\x01\x12F\n" +
	"\x06values\x18\x02 \x03(\v2..cloud.v1.common.Schema.Filed.Enum.ValuesEntryR\x06values\x12!\n" +
	"\fdefined_only\x18\x03 \x01(\bR\vdefinedOnly\x12\x0e\n" +
	"\x02in\x18\x04 \x03(\x05R\x02in\x12\x15\n" +
	"\x06not_in\x18\x05 \x03(\x05R\x05notIn\x1a9\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\n" +
	"\n" +
	"\b_default\x1a\xb2\x02\n" +
	"\bDuration\x128\n" +
	"\adefault\x18\x01 \x01(\v2\x19.google.protobuf.DurationH\x00R\adefault\x88\x01\x01\x12.\n" +
	"\x02gt\x18\x02 \x01(\v2\x19.google.protobuf.DurationH\x01R\x02gt\x88\x01\x01\x120\n" +
	"\x03gte\x18\x03 \x01(\v2\x19.google.protobuf.DurationH\x02R\x03gte\x88\x01\x01\x12.\n" +
	"\x02lt\x18\x04 \x01(\v2\x19.google.protobuf.DurationH\x03R\x02lt\x88\x01\x01\x120\n" +
	"\x03lte\x18\x05 \x01(\v2\x19.google.protobuf.DurationH\x04R\x03lte\x88\x01\x01B\n" +
	"\n" +
	"\b_defaultB\x05\n" +
	"\x03_gtB\x06\n" +
	"\x04_gteB\x05\n" +
	"\x03_ltB\x06\n" +
	"\x04_lte\x1a\xb8\x02\n" +
	"\tTimestamp\x129\n" +
	"\adefault\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\adefault\x88\x01\x01\x12/\n" +
	"\x02gt\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\x02gt\x88\x01\x01\x121\n" +
	"\x03gte\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x02R\x03gte\x88\x01\x01\x12/\n" +
	"\x02lt\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x03R\x02lt\x88\x01\x01\x121\n" +
	"\x03lte\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x04R\x03lte\x88\x01\x01B\n" +
	"\n" +
	"\b_defaultB\x05\n" +
	"\x03_gtB\x06\n" +
	"\x04_gteB\x05\n" +
	"\x03_ltB\x06\n" +
	"\x04_lte\x1a\xb3\x01\n" +
	"\x04List\x123\n" +
	"\x05items\x18\x01 \x03(\v2\x1d.cloud.v1.common.Schema.FiledR\x05items\x12 \n" +
	"\tmin_items\x18\x02 \x01(\x04H\x00R\bminItems\x88\x01\x01\x12 \n" +
	"\tmax_items\x18\x03 \x01(\x04H\x01R\bmaxItems\x88\x01\x01\x12\x16\n" +
	"\x06unique\x18\x04 \x01(\bR\x06uniqueB\f\n" +
	"\n" +
	"_min_itemsB\f\n" +
	"\n" +
	"_max_items\x1aI\n" +
	"\x06Object\x124\n" +
	"\x06schema\x18\x01 \x01(\v2\x17.cloud.v1.common.SchemaH\x00R\x06schema\x88\x01\x01B\t\n" +
	"\a_schema\x1a\x8a\x05\n" +
	"\x02UI\x12\x19\n" +
	"\x05label\x18\x01 \x01(\tH\x00R\x05label\x88\x01\x01\x12\x17\n" +
	"\x04help\x18\x02 \x01(\tH\x01R\x04help\x88\x01\x01\x12%\n" +
	"\vplaceholder\x18\x03 \x01(\tH\x02R\vplaceholder\x88\x01\x01\x12D\n" +
	"\x06widget\x18\x04 \x01(\x0e2'.cloud.v1.common.Schema.Filed.UI.WidgetH\x03R\x06widget\x88\x01\x01\x12\x17\n" +
	"\x04unit\x18\x05 \x01(\tH\x04R\x04unit\x88\x01\x01\x12\x17\n" +
	"\x04step\x18\x06 \x01(\x01H\x05R\x04step\x88\x01\x01\x12\x19\n" +
	"\x05group\x18\a \x01(\tH\x06R\x05group\x88\x01\x01\x12\x19\n" +
	"\x05order\x18\b \x01(\x05H\aR\x05order\x88\x01\x01\x12\x1f\n" +
	"\badvanced\x18\t \x01(\bH\bR\badvanced\x88\x01\x01\x12\"\n" +
	"\n" +
	"visible_if\x18\n" +
	" \x01(\tH\tR\tvisibleIf\x88\x01\x01\x12\"\n" +
	"\n" +
	"enabled_if\x18\v \x01(\tH\n" +
	"R\tenabledIf\x88\x01\x01\"\x92\x01\n" +
	"\x06Widget\x12\x16\n" +
	"\x12WIDGET_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fWIDGET_INPUT\x10\x01\x12\x11\n" +
	"\rWIDGET_SLIDER\x10\x02\x12\x11\n" +
	"\rWIDGET_SELECT\x10\x03\x12\x10\n" +
	"\fWIDGET_RADIO\x10\x04\x12\x11\n" +
	"\rWIDGET_SWITCH\x10\x05\x12\x13\n" +
	"\x0fWIDGET_TEXTAREA\x10\x06B\b\n" +
	"\x06_labelB\a\n" +
	"\x05_helpB\x0e\n" +
	"\f_placeholderB\t\n" +
	"\a_widgetB\a\n" +
	"\x05_unitB\a\n" +
	"\x05_stepB\b\n" +
	"\x06_groupB\b\n" +
	"\x06_orderB\v\n" +
	"\t_advancedB\r\n" +
	"\v_visible_ifB\r\n" +
	"\v_enabled_if\x1a\xa6\x01\n" +
	"\x04Rule\x12\x12\n" +
	"\x04expr\x18\x01 \x01(\tR\x04expr\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x13\n" +
	"\x02id\x18\x03 \x01(\tH\x00R\x02id\x88\x01\x01\x12G\n" +
	"\bseverity\x18\x04 \x01(\x0e2&.cloud.v1.common.Schema.Filed.SeverityH\x01R\bseverity\x88\x01\x01B\x05\n" +
	"\x03_idB\v\n" +
	"\t_severity\"<\n" +
	"\bSeverity\x12\x18\n" +
	"\x14SEVERITY_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05ERROR\x10\x01\x12\v\n" +
	"\aWARNING\x10\x02B\x06\n" +
	"\x04kindB\x0e\n" +
	"\f_descriptionB\a\n" +
	"\x05_name\"\xaa\x01\n" +
	"\n" +
	"FieldError\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\arule_id\x18\x03 \x01(\tH\x00R\x06ruleId\x88\x01\x01\x12B\n" +
	"\bseverity\x18\x04 \x01(\x0e2&.cloud.v1.common.Schema.Filed.SeverityR\bseverityB\n" +
	"\n" +
	"\b_rule_idB)Z'github.com/stroppy-io/schemapb/schemapbb\x06proto3"

var (
	file_schemapb_schema_proto_rawDescOnce sync.Once
	file_schemapb_schema_proto_rawDescData []byte
)

func file_schemapb_schema_proto_rawDescGZIP() []byte {
	file_schemapb_schema_proto_rawDescOnce.Do(func() {
		file_schemapb_schema_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_schemapb_schema_proto_rawDesc), len(file_schemapb_schema_proto_rawDesc)))
	})
	return file_schemapb_schema_proto_rawDescData
}

var file_schemapb_schema_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_schemapb_schema_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_schemapb_schema_proto_goTypes = []any{
	(Schema_Filed_Severity)(0),     // 0: cloud.v1.common.Schema.Filed.Severity
	(Schema_Filed_UI_Widget)(0),    // 1: cloud.v1.common.Schema.Filed.UI.Widget
	(*Schema)(nil),                 // 2: cloud.v1.common.Schema
	(*FieldError)(nil),             // 3: cloud.v1.common.FieldError
	(*Schema_Filed)(nil),           // 4: cloud.v1.common.Schema.Filed
	(*Schema_Filed_Float)(nil),     // 5: cloud.v1.common.Schema.Filed.Float
	(*Schema_Filed_Double)(nil),    // 6: cloud.v1.common.Schema.Filed.Double
	(*Schema_Filed_Int32)(nil),     // 7: cloud.v1.common.Schema.Filed.Int32
	(*Schema_Filed_Int64)(nil),     // 8: cloud.v1.common.Schema.Filed.Int64
	(*Schema_Filed_UInt32)(nil),    // 9: cloud.v1.common.Schema.Filed.UInt32
	(*Schema_Filed_UInt64)(nil),    // 10: cloud.v1.common.Schema.Filed.UInt64
	(*Schema_Filed_Bool)(nil),      // 11: cloud.v1.common.Schema.Filed.Bool
	(*Schema_Filed_String)(nil),    // 12: cloud.v1.common.Schema.Filed.String
	(*Schema_Filed_Enum)(nil),      // 13: cloud.v1.common.Schema.Filed.Enum
	(*Schema_Filed_Duration)(nil),  // 14: cloud.v1.common.Schema.Filed.Duration
	(*Schema_Filed_Timestamp)(nil), // 15: cloud.v1.common.Schema.Filed.Timestamp
	(*Schema_Filed_List)(nil),      // 16: cloud.v1.common.Schema.Filed.List
	(*Schema_Filed_Object)(nil),    // 17: cloud.v1.common.Schema.Filed.Object
	(*Schema_Filed_UI)(nil),        // 18: cloud.v1.common.Schema.Filed.UI
	(*Schema_Filed_Rule)(nil),      // 19: cloud.v1.common.Schema.Filed.Rule
	nil,                            // 20: cloud.v1.common.Schema.Filed.Enum.ValuesEntry
	(*durationpb.Duration)(nil),    // 21: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil),  // 22: google.protobuf.Timestamp
}
var file_schemapb_schema_proto_depIdxs = []int32{
	4,  // 0: cloud.v1.common.Schema.fields:type_name -> cloud.v1.common.Schema.Filed
	19, // 1: cloud.v1.common.Schema.rules:type_name -> cloud.v1.common.Schema.Filed.Rule
	0,  // 2: cloud.v1.common.FieldError.severity:type_name -> cloud.v1.common.Schema.Filed.Severity
	18, // 3: cloud.v1.common.Schema.Filed.ui:type_name -> cloud.v1.common.Schema.Filed.UI
	19, // 4: cloud.v1.common.Schema.Filed.rules:type_name -> cloud.v1.common.Schema.Filed.Rule
	5,  // 5: cloud.v1.common.Schema.Filed.float:type_name -> cloud.v1.common.Schema.Filed.Float
	6,  // 6: cloud.v1.common.Schema.Filed.double:type_name -> cloud.v1.common.Schema.Filed.Double
	7,  // 7: cloud.v1.common.Schema.Filed.int32:type_name -> cloud.v1.common.Schema.Filed.Int32
	8,  // 8: cloud.v1.common.Schema.Filed.int64:type_name -> cloud.v1.common.Schema.Filed.Int64
	9,  // 9: cloud.v1.common.Schema.Filed.uint32:type_name -> cloud.v1.common.Schema.Filed.UInt32
	10, // 10: cloud.v1.common.Schema.Filed.uint64:type_name -> cloud.v1.common.Schema.Filed.UInt64
	11, // 11: cloud.v1.common.Schema.Filed.bool:type_name -> cloud.v1.common.Schema.Filed.Bool
	12, // 12: cloud.v1.common.Schema.Filed.string:type_name -> cloud.v1.common.Schema.Filed.String
	13, // 13: cloud.v1.common.Schema.Filed.enum:type_name -> cloud.v1.common.Schema.Filed.Enum
	14, // 14: cloud.v1.common.Schema.Filed.duration:type_name -> cloud.v1.common.Schema.Filed.Duration
	15, // 15: cloud.v1.common.Schema.Filed.timestamp:type_name -> cloud.v1.common.Schema.Filed.Timestamp
	16, // 16: cloud.v1.common.Schema.Filed.list:type_name -> cloud.v1.common.Schema.Filed.List
	17, // 17: cloud.v1.common.Schema.Filed.object:type_name -> cloud.v1.common.Schema.Filed.Object
	20, // 18: cloud.v1.common.Schema.Filed.Enum.values:type_name -> cloud.v1.common.Schema.Filed.Enum.ValuesEntry
	21, // 19: cloud.v1.common.Schema.Filed.Duration.default:type_name -> google.protobuf.Duration
	21, // 20: cloud.v1.common.Schema.Filed.Duration.gt:type_name -> google.protobuf.Duration
	21, // 21: cloud.v1.common.Schema.Filed.Duration.gte:type_name -> google.protobuf.Duration
	21, // 22: cloud.v1.common.Schema.Filed.Duration.lt:type_name -> google.protobuf.Duration
	21, // 23: cloud.v1.common.Schema.Filed.Duration.lte:type_name -> google.protobuf.Duration
	22, // 24: cloud.v1.common.Schema.Filed.Timestamp.default:type_name -> google.protobuf.Timestamp
	22, // 25: cloud.v1.common.Schema.Filed.Timestamp.gt:type_name -> google.protobuf.Timestamp
	22, // 26: cloud.v1.common.Schema.Filed.Timestamp.gte:type_name -> google.protobuf.Timestamp
	22, // 27: cloud.v1.common.Schema.Filed.Timestamp.lt:type_name -> google.protobuf.Timestamp
	22, // 28: cloud.v1.common.Schema.Filed.Timestamp.lte:type_name -> google.protobuf.Timestamp
	4,  // 29: cloud.v1.common.Schema.Filed.List.items:type_name -> cloud.v1.common.Schema.Filed
	2,  // 30: cloud.v1.common.Schema.Filed.Object.schema:type_name -> cloud.v1.common.Schema
	1,  // 31: cloud.v1.common.Schema.Filed.UI.widget:type_name -> cloud.v1.common.Schema.Filed.UI.Widget
	0,  // 32: cloud.v1.common.Schema.Filed.Rule.severity:type_name -> cloud.v1.common.Schema.Filed.Severity
	33, // [33:33] is the sub-list for method output_type
	33, // [33:33] is the sub-list for method input_type
	33, // [33:33] is the sub-list for extension type_name
	33, // [33:33] is the sub-list for extension extendee
	0,  // [0:33] is the sub-list for field type_name
}

func init() { file_schemapb_schema_proto_init() }
func file_schemapb_schema_proto_init() {
	if File_schemapb_schema_proto != nil {
		return
	}
	file_schemapb_schema_proto_msgTypes[0].OneofWrappers = []any{}
	file_schemapb_schema_proto_msgTypes[1].OneofWrappers = []any{}
	file_schemapb_schema_proto_msgTypes[2].OneofWrappers = []any{
		(*Schema_Filed_Float_)(nil),
		(*Schema_Filed_Double_)(nil),
		(*Schema_Filed_Int32_)(nil),
		(*Schema_Filed_Int64_)(nil),
		(*Schema_Filed_Uint32)(nil),
		(*Schema_Filed_Uint64)(nil),
		(*Schema_Filed_Bool_)(nil),
		(*Schema_Filed_String_)(nil),
		(*Schema_Filed_Enum_)(nil),
		(*Schema_Filed_Duration_)(nil),
		(*Schema_Filed_Timestamp_)(nil),
		(*Schema_Filed_List_)(nil),
		(*Schema_Filed_Object_)(nil),
	}
	file_schemapb_schema_proto_msgTypes[3].OneofWrappers = []any{}
	file_schemapb_schema_proto_msgTypes[4].OneofWrappers = []any{}
	file_schemapb_schema_proto_msgTypes[5].OneofWrappers = []any{}
	file_schemapb_schema_proto_msgTypes[6].OneofWrappers = []any{}
	file_schemapb_schema_proto_msgTypes[7].OneofWrappers = []any{}
	file_schemapb_schema_proto_msgTypes[8].OneofWrappers = []any{}
	file_schemapb_schema_proto_msgTypes[9].OneofWrappers = []any{}
	file_schemapb_schema_proto_msgTypes[10].OneofWrappers = []any{}
	file_schemapb_schema_proto_msgTypes[11].OneofWrappers = []any{}
	file_schemapb_schema_proto_msgTypes[12].OneofWrappers = []any{}
	file_schemapb_schema_proto_msgTypes[13].OneofWrappers = []any{}
	file_schemapb_schema_proto_msgTypes[14].OneofWrappers = []any{}
	file_schemapb_schema_proto_msgTypes[15].OneofWrappers = []any{}
	file_schemapb_schema_proto_msgTypes[16].OneofWrappers = []any{}
	file_schemapb_schema_proto_msgTypes[17].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_schemapb_schema_proto_rawDesc), len(file_schemapb_schema_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_schemapb_schema_proto_goTypes,
		DependencyIndexes: file_schemapb_schema_proto_depIdxs,
		EnumInfos:         file_schemapb_schema_proto_enumTypes,
		MessageInfos:      file_schemapb_schema_proto_msgTypes,
	}.Build()
	File_schemapb_schema_proto = out.File
	file_schemapb_schema_proto_goTypes = nil
	file_schemapb_schema_proto_depIdxs = nil
}
