// Code generated by protoc-gen-go-hashpb. DO NOT EDIT.
// protoc-gen-go-hashpb v0.5.0
// Source: schemapb/schema.proto

package schemapb

import (
	hash "hash"
)

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *Schema) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	if m != nil {
		b := hashpb_bufPool.Get().(*[10]byte)
		schemapb_Schema_hashpb_sum(m, hasher, ignore, b)
		hashpb_bufPool.Put(b)
	}
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *Schema_Filed) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	if m != nil {
		b := hashpb_bufPool.Get().(*[10]byte)
		schemapb_Schema_Filed_hashpb_sum(m, hasher, ignore, b)
		hashpb_bufPool.Put(b)
	}
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *Schema_Filed_Float) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	if m != nil {
		b := hashpb_bufPool.Get().(*[10]byte)
		schemapb_Schema_Filed_Float_hashpb_sum(m, hasher, ignore, b)
		hashpb_bufPool.Put(b)
	}
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *Schema_Filed_Double) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	if m != nil {
		b := hashpb_bufPool.Get().(*[10]byte)
		schemapb_Schema_Filed_Double_hashpb_sum(m, hasher, ignore, b)
		hashpb_bufPool.Put(b)
	}
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *Schema_Filed_Int32) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	if m != nil {
		b := hashpb_bufPool.Get().(*[10]byte)
		schemapb_Schema_Filed_Int32_hashpb_sum(m, hasher, ignore, b)
		hashpb_bufPool.Put(b)
	}
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *Schema_Filed_Int64) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	if m != nil {
		b := hashpb_bufPool.Get().(*[10]byte)
		schemapb_Schema_Filed_Int64_hashpb_sum(m, hasher, ignore, b)
		hashpb_bufPool.Put(b)
	}
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *Schema_Filed_UInt32) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	if m != nil {
		b := hashpb_bufPool.Get().(*[10]byte)
		schemapb_Schema_Filed_UInt32_hashpb_sum(m, hasher, ignore, b)
		hashpb_bufPool.Put(b)
	}
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *Schema_Filed_UInt64) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	if m != nil {
		b := hashpb_bufPool.Get().(*[10]byte)
		schemapb_Schema_Filed_UInt64_hashpb_sum(m, hasher, ignore, b)
		hashpb_bufPool.Put(b)
	}
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *Schema_Filed_Bool) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	if m != nil {
		b := hashpb_bufPool.Get().(*[10]byte)
		schemapb_Schema_Filed_Bool_hashpb_sum(m, hasher, ignore, b)
		hashpb_bufPool.Put(b)
	}
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *Schema_Filed_String) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	if m != nil {
		b := hashpb_bufPool.Get().(*[10]byte)
		schemapb_Schema_Filed_String_hashpb_sum(m, hasher, ignore, b)
		hashpb_bufPool.Put(b)
	}
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *Schema_Filed_Enum) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	if m != nil {
		b := hashpb_bufPool.Get().(*[10]byte)
		schemapb_Schema_Filed_Enum_hashpb_sum(m, hasher, ignore, b)
		hashpb_bufPool.Put(b)
	}
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *Schema_Filed_Duration) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	if m != nil {
		b := hashpb_bufPool.Get().(*[10]byte)
		schemapb_Schema_Filed_Duration_hashpb_sum(m, hasher, ignore, b)
		hashpb_bufPool.Put(b)
	}
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *Schema_Filed_Timestamp) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	if m != nil {
		b := hashpb_bufPool.Get().(*[10]byte)
		schemapb_Schema_Filed_Timestamp_hashpb_sum(m, hasher, ignore, b)
		hashpb_bufPool.Put(b)
	}
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *Schema_Filed_List) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	if m != nil {
		b := hashpb_bufPool.Get().(*[10]byte)
		schemapb_Schema_Filed_List_hashpb_sum(m, hasher, ignore, b)
		hashpb_bufPool.Put(b)
	}
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *Schema_Filed_Object) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	if m != nil {
		b := hashpb_bufPool.Get().(*[10]byte)
		schemapb_Schema_Filed_Object_hashpb_sum(m, hasher, ignore, b)
		hashpb_bufPool.Put(b)
	}
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *Schema_Filed_Computed) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	if m != nil {
		b := hashpb_bufPool.Get().(*[10]byte)
		schemapb_Schema_Filed_Computed_hashpb_sum(m, hasher, ignore, b)
		hashpb_bufPool.Put(b)
	}
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *Schema_Filed_Rule) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	if m != nil {
		b := hashpb_bufPool.Get().(*[10]byte)
		schemapb_Schema_Filed_Rule_hashpb_sum(m, hasher, ignore, b)
		hashpb_bufPool.Put(b)
	}
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *Schema_Filed_OneOf) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	if m != nil {
		b := hashpb_bufPool.Get().(*[10]byte)
		schemapb_Schema_Filed_OneOf_hashpb_sum(m, hasher, ignore, b)
		hashpb_bufPool.Put(b)
	}
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *SchemaIdentity) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	if m != nil {
		b := hashpb_bufPool.Get().(*[10]byte)
		schemapb_SchemaIdentity_hashpb_sum(m, hasher, ignore, b)
		hashpb_bufPool.Put(b)
	}
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *FieldError) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	if m != nil {
		b := hashpb_bufPool.Get().(*[10]byte)
		schemapb_FieldError_hashpb_sum(m, hasher, ignore, b)
		hashpb_bufPool.Put(b)
	}
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *SchemaRef) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	if m != nil {
		b := hashpb_bufPool.Get().(*[10]byte)
		schemapb_SchemaRef_hashpb_sum(m, hasher, ignore, b)
		hashpb_bufPool.Put(b)
	}
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *Filled) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	if m != nil {
		b := hashpb_bufPool.Get().(*[10]byte)
		schemapb_Filled_hashpb_sum(m, hasher, ignore, b)
		hashpb_bufPool.Put(b)
	}
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *Baked) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	if m != nil {
		b := hashpb_bufPool.Get().(*[10]byte)
		schemapb_Baked_hashpb_sum(m, hasher, ignore, b)
		hashpb_bufPool.Put(b)
	}
}
