// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: schemapb/service.proto

package schemapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SchemaRef selects the schema an operation runs against: either inline, or by
// identity (resolved from the server registry).
type SchemaRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Source:
	//
	//	*SchemaRef_Id
	//	*SchemaRef_Schema
	Source        isSchemaRef_Source `protobuf_oneof:"source"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemaRef) Reset() {
	*x = SchemaRef{}
	mi := &file_schemapb_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaRef) ProtoMessage() {}

func (x *SchemaRef) ProtoReflect() protoreflect.Message {
	mi := &file_schemapb_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaRef.ProtoReflect.Descriptor instead.
func (*SchemaRef) Descriptor() ([]byte, []int) {
	return file_schemapb_service_proto_rawDescGZIP(), []int{0}
}

func (x *SchemaRef) GetSource() isSchemaRef_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *SchemaRef) GetId() *SchemaIdentity {
	if x != nil {
		if x, ok := x.Source.(*SchemaRef_Id); ok {
			return x.Id
		}
	}
	return nil
}

func (x *SchemaRef) GetSchema() *Schema {
	if x != nil {
		if x, ok := x.Source.(*SchemaRef_Schema); ok {
			return x.Schema
		}
	}
	return nil
}

type isSchemaRef_Source interface {
	isSchemaRef_Source()
}

type SchemaRef_Id struct {
	// Resolve a registered schema by identity.
	Id *SchemaIdentity `protobuf:"bytes,1,opt,name=id,proto3,oneof"`
}

type SchemaRef_Schema struct {
	// Use this schema directly, without registering it.
	Schema *Schema `protobuf:"bytes,2,opt,name=schema,proto3,oneof"`
}

func (*SchemaRef_Id) isSchemaRef_Source() {}

func (*SchemaRef_Schema) isSchemaRef_Source() {}

// Filter narrows ListSchemas. Unset fields are not constrained; all set fields
// must match (AND). An empty Filter lists everything.
type Filter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Exact namespace match.
	Namespace *string `protobuf:"bytes,1,opt,name=namespace,proto3,oneof" json:"namespace,omitempty"`
	// Exact name match.
	Name *string `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// Exact version match.
	Version *string `protobuf:"bytes,3,opt,name=version,proto3,oneof" json:"version,omitempty"`
	// Case-insensitive substring match against the name.
	NameContains  *string `protobuf:"bytes,4,opt,name=name_contains,json=nameContains,proto3,oneof" json:"name_contains,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_schemapb_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_schemapb_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_schemapb_service_proto_rawDescGZIP(), []int{1}
}

func (x *Filter) GetNamespace() string {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return ""
}

func (x *Filter) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Filter) GetVersion() string {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return ""
}

func (x *Filter) GetNameContains() string {
	if x != nil && x.NameContains != nil {
		return *x.NameContains
	}
	return ""
}

// SchemaSummary is the lightweight listing entry; fetch the full Schema with GetSchema.
type SchemaSummary struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Schema identity.
	Id *SchemaIdentity `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Schema description, if any.
	Description   *string `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemaSummary) Reset() {
	*x = SchemaSummary{}
	mi := &file_schemapb_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaSummary) ProtoMessage() {}

func (x *SchemaSummary) ProtoReflect() protoreflect.Message {
	mi := &file_schemapb_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaSummary.ProtoReflect.Descriptor instead.
func (*SchemaSummary) Descriptor() ([]byte, []int) {
	return file_schemapb_service_proto_rawDescGZIP(), []int{2}
}

func (x *SchemaSummary) GetId() *SchemaIdentity {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *SchemaSummary) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type RegisterSchemaResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identity the schema is stored under (its own id).
	Id *SchemaIdentity `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// True if the schema is well-formed and was stored.
	Valid bool `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	// Descriptor problems; non-empty means the schema was rejected.
	Errors        []*FieldError `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterSchemaResponse) Reset() {
	*x = RegisterSchemaResponse{}
	mi := &file_schemapb_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterSchemaResponse) ProtoMessage() {}

func (x *RegisterSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schemapb_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterSchemaResponse.ProtoReflect.Descriptor instead.
func (*RegisterSchemaResponse) Descriptor() ([]byte, []int) {
	return file_schemapb_service_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterSchemaResponse) GetId() *SchemaIdentity {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *RegisterSchemaResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *RegisterSchemaResponse) GetErrors() []*FieldError {
	if x != nil {
		return x.Errors
	}
	return nil
}

type ListSchemasResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Matching schemas (summaries).
	Schemas       []*SchemaSummary `protobuf:"bytes,1,rep,name=schemas,proto3" json:"schemas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSchemasResponse) Reset() {
	*x = ListSchemasResponse{}
	mi := &file_schemapb_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSchemasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSchemasResponse) ProtoMessage() {}

func (x *ListSchemasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schemapb_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSchemasResponse.ProtoReflect.Descriptor instead.
func (*ListSchemasResponse) Descriptor() ([]byte, []int) {
	return file_schemapb_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListSchemasResponse) GetSchemas() []*SchemaSummary {
	if x != nil {
		return x.Schemas
	}
	return nil
}

type ValidateSchemaResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True if the descriptor is well-formed.
	Valid bool `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	// Descriptor problems.
	Errors        []*FieldError `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateSchemaResponse) Reset() {
	*x = ValidateSchemaResponse{}
	mi := &file_schemapb_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateSchemaResponse) ProtoMessage() {}

func (x *ValidateSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schemapb_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateSchemaResponse.ProtoReflect.Descriptor instead.
func (*ValidateSchemaResponse) Descriptor() ([]byte, []int) {
	return file_schemapb_service_proto_rawDescGZIP(), []int{5}
}

func (x *ValidateSchemaResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateSchemaResponse) GetErrors() []*FieldError {
	if x != nil {
		return x.Errors
	}
	return nil
}

type ValidateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Schema to validate against.
	Schema *SchemaRef `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	// Form values to validate.
	Values        *structpb.Struct `protobuf:"bytes,2,opt,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateRequest) Reset() {
	*x = ValidateRequest{}
	mi := &file_schemapb_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRequest) ProtoMessage() {}

func (x *ValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schemapb_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRequest.ProtoReflect.Descriptor instead.
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return file_schemapb_service_proto_rawDescGZIP(), []int{6}
}

func (x *ValidateRequest) GetSchema() *SchemaRef {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *ValidateRequest) GetValues() *structpb.Struct {
	if x != nil {
		return x.Values
	}
	return nil
}

type ValidateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True if there are no ERROR-severity failures.
	Valid bool `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	// Validation failures (errors and warnings).
	Errors        []*FieldError `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateResponse) Reset() {
	*x = ValidateResponse{}
	mi := &file_schemapb_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateResponse) ProtoMessage() {}

func (x *ValidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schemapb_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateResponse.ProtoReflect.Descriptor instead.
func (*ValidateResponse) Descriptor() ([]byte, []int) {
	return file_schemapb_service_proto_rawDescGZIP(), []int{7}
}

func (x *ValidateResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateResponse) GetErrors() []*FieldError {
	if x != nil {
		return x.Errors
	}
	return nil
}

type ComputeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Schema whose Computed fields to evaluate.
	Schema *SchemaRef `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	// Input values the expressions read.
	Values        *structpb.Struct `protobuf:"bytes,2,opt,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComputeRequest) Reset() {
	*x = ComputeRequest{}
	mi := &file_schemapb_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeRequest) ProtoMessage() {}

func (x *ComputeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schemapb_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputeRequest.ProtoReflect.Descriptor instead.
func (*ComputeRequest) Descriptor() ([]byte, []int) {
	return file_schemapb_service_proto_rawDescGZIP(), []int{8}
}

func (x *ComputeRequest) GetSchema() *SchemaRef {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *ComputeRequest) GetValues() *structpb.Struct {
	if x != nil {
		return x.Values
	}
	return nil
}

type ComputeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The fully resolved form: the provided inputs, plus values filled from the
	// schema's defaults, plus the evaluated Computed (derived) fields.
	Values *structpb.Struct `protobuf:"bytes,1,opt,name=values,proto3" json:"values,omitempty"`
	// Errors raised while evaluating expressions.
	Errors        []*FieldError `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComputeResponse) Reset() {
	*x = ComputeResponse{}
	mi := &file_schemapb_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeResponse) ProtoMessage() {}

func (x *ComputeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schemapb_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputeResponse.ProtoReflect.Descriptor instead.
func (*ComputeResponse) Descriptor() ([]byte, []int) {
	return file_schemapb_service_proto_rawDescGZIP(), []int{9}
}

func (x *ComputeResponse) GetValues() *structpb.Struct {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *ComputeResponse) GetErrors() []*FieldError {
	if x != nil {
		return x.Errors
	}
	return nil
}

var File_schemapb_service_proto protoreflect.FileDescriptor

const file_schemapb_service_proto_rawDesc = "" +
	"\n" +
	"\x16schemapb/service.proto\x12\bschemapb\x1a\x1cgoogle/protobuf/struct.proto\x1a\x15schemapb/schema.proto\"m\n" +
	"\tSchemaRef\x12*\n" +
	"\x02id\x18\x01 \x01(\v2\x18.schemapb.SchemaIdentityH\x00R\x02id\x12*\n" +
	"\x06schema\x18\x02 \x01(\v2\x10.schemapb.SchemaH\x00R\x06schemaB\b\n" +
	"\x06source\"\xc2\x01\n" +
	"\x06Filter\x12!\n" +
	"\tnamespace\x18\x01 \x01(\tH\x00R\tnamespace\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x01R\x04name\x88\x01\x01\x12\x1d\n" +
	"\aversion\x18\x03 \x01(\tH\x02R\aversion\x88\x01\x01\x12(\n" +
	"\rname_contains\x18\x04 \x01(\tH\x03R\fnameContains\x88\x01\x01B\f\n" +
	"\n" +
	"_namespaceB\a\n" +
	"\x05_nameB\n" +
	"\n" +
	"\b_versionB\x10\n" +
	"\x0e_name_contains\"p\n" +
	"\rSchemaSummary\x12(\n" +
	"\x02id\x18\x01 \x01(\v2\x18.schemapb.SchemaIdentityR\x02id\x12%\n" +
	"\vdescription\x18\x02 \x01(\tH\x00R\vdescription\x88\x01\x01B\x0e\n" +
	"\f_description\"\x86\x01\n" +
	"\x16RegisterSchemaResponse\x12(\n" +
	"\x02id\x18\x01 \x01(\v2\x18.schemapb.SchemaIdentityR\x02id\x12\x14\n" +
	"\x05valid\x18\x02 \x01(\bR\x05valid\x12,\n" +
	"\x06errors\x18\x03 \x03(\v2\x14.schemapb.FieldErrorR\x06errors\"H\n" +
	"\x13ListSchemasResponse\x121\n" +
	"\aschemas\x18\x01 \x03(\v2\x17.schemapb.SchemaSummaryR\aschemas\"\\\n" +
	"\x16ValidateSchemaResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12,\n" +
	"\x06errors\x18\x02 \x03(\v2\x14.schemapb.FieldErrorR\x06errors\"o\n" +
	"\x0fValidateRequest\x12+\n" +
	"\x06schema\x18\x01 \x01(\v2\x13.schemapb.SchemaRefR\x06schema\x12/\n" +
	"\x06values\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x06values\"V\n" +
	"\x10ValidateResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12,\n" +
	"\x06errors\x18\x02 \x03(\v2\x14.schemapb.FieldErrorR\x06errors\"n\n" +
	"\x0eComputeRequest\x12+\n" +
	"\x06schema\x18\x01 \x01(\v2\x13.schemapb.SchemaRefR\x06schema\x12/\n" +
	"\x06values\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x06values\"p\n" +
	"\x0fComputeResponse\x12/\n" +
	"\x06values\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x06values\x12,\n" +
	"\x06errors\x18\x02 \x03(\v2\x14.schemapb.FieldErrorR\x06errors2\x97\x03\n" +
	"\rSchemaService\x12D\n" +
	"\x0eRegisterSchema\x12\x10.schemapb.Schema\x1a .schemapb.RegisterSchemaResponse\x127\n" +
	"\tGetSchema\x12\x18.schemapb.SchemaIdentity\x1a\x10.schemapb.Schema\x12>\n" +
	"\vListSchemas\x12\x10.schemapb.Filter\x1a\x1d.schemapb.ListSchemasResponse\x12D\n" +
	"\x0eValidateSchema\x12\x10.schemapb.Schema\x1a .schemapb.ValidateSchemaResponse\x12A\n" +
	"\bValidate\x12\x19.schemapb.ValidateRequest\x1a\x1a.schemapb.ValidateResponse\x12>\n" +
	"\aCompute\x12\x18.schemapb.ComputeRequest\x1a\x19.schemapb.ComputeResponseB)Z'github.com/stroppy-io/schemapb/schemapbb\x06proto3"

var (
	file_schemapb_service_proto_rawDescOnce sync.Once
	file_schemapb_service_proto_rawDescData []byte
)

func file_schemapb_service_proto_rawDescGZIP() []byte {
	file_schemapb_service_proto_rawDescOnce.Do(func() {
		file_schemapb_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_schemapb_service_proto_rawDesc), len(file_schemapb_service_proto_rawDesc)))
	})
	return file_schemapb_service_proto_rawDescData
}

var file_schemapb_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_schemapb_service_proto_goTypes = []any{
	(*SchemaRef)(nil),              // 0: schemapb.SchemaRef
	(*Filter)(nil),                 // 1: schemapb.Filter
	(*SchemaSummary)(nil),          // 2: schemapb.SchemaSummary
	(*RegisterSchemaResponse)(nil), // 3: schemapb.RegisterSchemaResponse
	(*ListSchemasResponse)(nil),    // 4: schemapb.ListSchemasResponse
	(*ValidateSchemaResponse)(nil), // 5: schemapb.ValidateSchemaResponse
	(*ValidateRequest)(nil),        // 6: schemapb.ValidateRequest
	(*ValidateResponse)(nil),       // 7: schemapb.ValidateResponse
	(*ComputeRequest)(nil),         // 8: schemapb.ComputeRequest
	(*ComputeResponse)(nil),        // 9: schemapb.ComputeResponse
	(*SchemaIdentity)(nil),         // 10: schemapb.SchemaIdentity
	(*Schema)(nil),                 // 11: schemapb.Schema
	(*FieldError)(nil),             // 12: schemapb.FieldError
	(*structpb.Struct)(nil),        // 13: google.protobuf.Struct
}
var file_schemapb_service_proto_depIdxs = []int32{
	10, // 0: schemapb.SchemaRef.id:type_name -> schemapb.SchemaIdentity
	11, // 1: schemapb.SchemaRef.schema:type_name -> schemapb.Schema
	10, // 2: schemapb.SchemaSummary.id:type_name -> schemapb.SchemaIdentity
	10, // 3: schemapb.RegisterSchemaResponse.id:type_name -> schemapb.SchemaIdentity
	12, // 4: schemapb.RegisterSchemaResponse.errors:type_name -> schemapb.FieldError
	2,  // 5: schemapb.ListSchemasResponse.schemas:type_name -> schemapb.SchemaSummary
	12, // 6: schemapb.ValidateSchemaResponse.errors:type_name -> schemapb.FieldError
	0,  // 7: schemapb.ValidateRequest.schema:type_name -> schemapb.SchemaRef
	13, // 8: schemapb.ValidateRequest.values:type_name -> google.protobuf.Struct
	12, // 9: schemapb.ValidateResponse.errors:type_name -> schemapb.FieldError
	0,  // 10: schemapb.ComputeRequest.schema:type_name -> schemapb.SchemaRef
	13, // 11: schemapb.ComputeRequest.values:type_name -> google.protobuf.Struct
	13, // 12: schemapb.ComputeResponse.values:type_name -> google.protobuf.Struct
	12, // 13: schemapb.ComputeResponse.errors:type_name -> schemapb.FieldError
	11, // 14: schemapb.SchemaService.RegisterSchema:input_type -> schemapb.Schema
	10, // 15: schemapb.SchemaService.GetSchema:input_type -> schemapb.SchemaIdentity
	1,  // 16: schemapb.SchemaService.ListSchemas:input_type -> schemapb.Filter
	11, // 17: schemapb.SchemaService.ValidateSchema:input_type -> schemapb.Schema
	6,  // 18: schemapb.SchemaService.Validate:input_type -> schemapb.ValidateRequest
	8,  // 19: schemapb.SchemaService.Compute:input_type -> schemapb.ComputeRequest
	3,  // 20: schemapb.SchemaService.RegisterSchema:output_type -> schemapb.RegisterSchemaResponse
	11, // 21: schemapb.SchemaService.GetSchema:output_type -> schemapb.Schema
	4,  // 22: schemapb.SchemaService.ListSchemas:output_type -> schemapb.ListSchemasResponse
	5,  // 23: schemapb.SchemaService.ValidateSchema:output_type -> schemapb.ValidateSchemaResponse
	7,  // 24: schemapb.SchemaService.Validate:output_type -> schemapb.ValidateResponse
	9,  // 25: schemapb.SchemaService.Compute:output_type -> schemapb.ComputeResponse
	20, // [20:26] is the sub-list for method output_type
	14, // [14:20] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_schemapb_service_proto_init() }
func file_schemapb_service_proto_init() {
	if File_schemapb_service_proto != nil {
		return
	}
	file_schemapb_schema_proto_init()
	file_schemapb_service_proto_msgTypes[0].OneofWrappers = []any{
		(*SchemaRef_Id)(nil),
		(*SchemaRef_Schema)(nil),
	}
	file_schemapb_service_proto_msgTypes[1].OneofWrappers = []any{}
	file_schemapb_service_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_schemapb_service_proto_rawDesc), len(file_schemapb_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_schemapb_service_proto_goTypes,
		DependencyIndexes: file_schemapb_service_proto_depIdxs,
		MessageInfos:      file_schemapb_service_proto_msgTypes,
	}.Build()
	File_schemapb_service_proto = out.File
	file_schemapb_service_proto_goTypes = nil
	file_schemapb_service_proto_depIdxs = nil
}
