// Code generated by protoc-gen-go-hashpb. DO NOT EDIT.
// protoc-gen-go-hashpb v0.5.0
// Source: schemapb/service.proto

package schemapb

import (
	hash "hash"
)

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *Filter) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	if m != nil {
		b := hashpb_bufPool.Get().(*[10]byte)
		schemapb_Filter_hashpb_sum(m, hasher, ignore, b)
		hashpb_bufPool.Put(b)
	}
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *SchemaSummary) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	if m != nil {
		b := hashpb_bufPool.Get().(*[10]byte)
		schemapb_SchemaSummary_hashpb_sum(m, hasher, ignore, b)
		hashpb_bufPool.Put(b)
	}
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *RegisterSchemaResponse) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	if m != nil {
		b := hashpb_bufPool.Get().(*[10]byte)
		schemapb_RegisterSchemaResponse_hashpb_sum(m, hasher, ignore, b)
		hashpb_bufPool.Put(b)
	}
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *ListSchemasResponse) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	if m != nil {
		b := hashpb_bufPool.Get().(*[10]byte)
		schemapb_ListSchemasResponse_hashpb_sum(m, hasher, ignore, b)
		hashpb_bufPool.Put(b)
	}
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *ValidateSchemaResponse) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	if m != nil {
		b := hashpb_bufPool.Get().(*[10]byte)
		schemapb_ValidateSchemaResponse_hashpb_sum(m, hasher, ignore, b)
		hashpb_bufPool.Put(b)
	}
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *ValidateResponse) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	if m != nil {
		b := hashpb_bufPool.Get().(*[10]byte)
		schemapb_ValidateResponse_hashpb_sum(m, hasher, ignore, b)
		hashpb_bufPool.Put(b)
	}
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *MergeRequest) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	if m != nil {
		b := hashpb_bufPool.Get().(*[10]byte)
		schemapb_MergeRequest_hashpb_sum(m, hasher, ignore, b)
		hashpb_bufPool.Put(b)
	}
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *BakeResponse) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	if m != nil {
		b := hashpb_bufPool.Get().(*[10]byte)
		schemapb_BakeResponse_hashpb_sum(m, hasher, ignore, b)
		hashpb_bufPool.Put(b)
	}
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *ComputeResponse) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	if m != nil {
		b := hashpb_bufPool.Get().(*[10]byte)
		schemapb_ComputeResponse_hashpb_sum(m, hasher, ignore, b)
		hashpb_bufPool.Put(b)
	}
}
