// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: schemapb/errors.proto

package schemapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ErrorCode is the stable, machine-readable reason a validation failed. The
// code (plus path and the typed fields on ValidationError) IS the
// cross-implementation contract; human-readable text is rendered from a
// shared, spec-owned template set and is not part of the contract.
type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_UNSPECIFIED ErrorCode = 0
	// Value/type shape.
	ErrorCode_ERROR_CODE_TYPE_MISMATCH      ErrorCode = 1
	ErrorCode_ERROR_CODE_REQUIRED_MISSING   ErrorCode = 2
	ErrorCode_ERROR_CODE_NOT_NULLABLE       ErrorCode = 3
	ErrorCode_ERROR_CODE_UNKNOWN_FIELD      ErrorCode = 4
	ErrorCode_ERROR_CODE_IMMUTABLE_MODIFIED ErrorCode = 5
	// Scalar constraints.
	ErrorCode_ERROR_CODE_CONST_MISMATCH       ErrorCode = 10
	ErrorCode_ERROR_CODE_GT_VIOLATED          ErrorCode = 11
	ErrorCode_ERROR_CODE_GTE_VIOLATED         ErrorCode = 12
	ErrorCode_ERROR_CODE_LT_VIOLATED          ErrorCode = 13
	ErrorCode_ERROR_CODE_LTE_VIOLATED         ErrorCode = 14
	ErrorCode_ERROR_CODE_NOT_IN_ALLOWED_SET   ErrorCode = 15
	ErrorCode_ERROR_CODE_IN_FORBIDDEN_SET     ErrorCode = 16
	ErrorCode_ERROR_CODE_MULTIPLE_OF_VIOLATED ErrorCode = 17
	// String constraints.
	ErrorCode_ERROR_CODE_LEN_MISMATCH     ErrorCode = 20
	ErrorCode_ERROR_CODE_MIN_LEN_VIOLATED ErrorCode = 21
	ErrorCode_ERROR_CODE_MAX_LEN_VIOLATED ErrorCode = 22
	ErrorCode_ERROR_CODE_PATTERN_MISMATCH ErrorCode = 23
	ErrorCode_ERROR_CODE_FORMAT_MISMATCH  ErrorCode = 24
	// String/bytes affix constraints.
	ErrorCode_ERROR_CODE_PREFIX_MISMATCH ErrorCode = 25
	ErrorCode_ERROR_CODE_SUFFIX_MISMATCH ErrorCode = 26
	// The schema names a format this implementation does not support. Failing
	// loudly is mandatory: a format may never be silently skipped.
	ErrorCode_ERROR_CODE_UNSUPPORTED_FORMAT ErrorCode = 27
	// Choice constraints.
	ErrorCode_ERROR_CODE_CHOICE_NOT_ALLOWED ErrorCode = 30
	// List constraints.
	ErrorCode_ERROR_CODE_MIN_ITEMS_VIOLATED  ErrorCode = 40
	ErrorCode_ERROR_CODE_MAX_ITEMS_VIOLATED  ErrorCode = 41
	ErrorCode_ERROR_CODE_NOT_UNIQUE          ErrorCode = 42
	ErrorCode_ERROR_CODE_LIST_COUNT_MISMATCH ErrorCode = 43
	// Map constraints.
	ErrorCode_ERROR_CODE_MIN_ENTRIES_VIOLATED ErrorCode = 50
	ErrorCode_ERROR_CODE_MAX_ENTRIES_VIOLATED ErrorCode = 51
	// Form-level constraints.
	ErrorCode_ERROR_CODE_MIN_PROPERTIES_VIOLATED ErrorCode = 60
	ErrorCode_ERROR_CODE_MAX_PROPERTIES_VIOLATED ErrorCode = 61
	// Composition.
	ErrorCode_ERROR_CODE_DISCRIMINATOR_MISSING ErrorCode = 70
	ErrorCode_ERROR_CODE_UNKNOWN_VARIANT       ErrorCode = 71
	ErrorCode_ERROR_CODE_UNKNOWN_REF           ErrorCode = 72
	// CEL layer.
	ErrorCode_ERROR_CODE_RULE_VIOLATED ErrorCode = 80
	ErrorCode_ERROR_CODE_EXPR_ERROR    ErrorCode = 81
	// Schema descriptor itself is malformed (bad identity, no kind chosen,
	// computed-field cycle, invalid CEL/Mustache/pattern source, ...).
	ErrorCode_ERROR_CODE_INVALID_SCHEMA ErrorCode = 90
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:  "ERROR_CODE_UNSPECIFIED",
		1:  "ERROR_CODE_TYPE_MISMATCH",
		2:  "ERROR_CODE_REQUIRED_MISSING",
		3:  "ERROR_CODE_NOT_NULLABLE",
		4:  "ERROR_CODE_UNKNOWN_FIELD",
		5:  "ERROR_CODE_IMMUTABLE_MODIFIED",
		10: "ERROR_CODE_CONST_MISMATCH",
		11: "ERROR_CODE_GT_VIOLATED",
		12: "ERROR_CODE_GTE_VIOLATED",
		13: "ERROR_CODE_LT_VIOLATED",
		14: "ERROR_CODE_LTE_VIOLATED",
		15: "ERROR_CODE_NOT_IN_ALLOWED_SET",
		16: "ERROR_CODE_IN_FORBIDDEN_SET",
		17: "ERROR_CODE_MULTIPLE_OF_VIOLATED",
		20: "ERROR_CODE_LEN_MISMATCH",
		21: "ERROR_CODE_MIN_LEN_VIOLATED",
		22: "ERROR_CODE_MAX_LEN_VIOLATED",
		23: "ERROR_CODE_PATTERN_MISMATCH",
		24: "ERROR_CODE_FORMAT_MISMATCH",
		25: "ERROR_CODE_PREFIX_MISMATCH",
		26: "ERROR_CODE_SUFFIX_MISMATCH",
		27: "ERROR_CODE_UNSUPPORTED_FORMAT",
		30: "ERROR_CODE_CHOICE_NOT_ALLOWED",
		40: "ERROR_CODE_MIN_ITEMS_VIOLATED",
		41: "ERROR_CODE_MAX_ITEMS_VIOLATED",
		42: "ERROR_CODE_NOT_UNIQUE",
		43: "ERROR_CODE_LIST_COUNT_MISMATCH",
		50: "ERROR_CODE_MIN_ENTRIES_VIOLATED",
		51: "ERROR_CODE_MAX_ENTRIES_VIOLATED",
		60: "ERROR_CODE_MIN_PROPERTIES_VIOLATED",
		61: "ERROR_CODE_MAX_PROPERTIES_VIOLATED",
		70: "ERROR_CODE_DISCRIMINATOR_MISSING",
		71: "ERROR_CODE_UNKNOWN_VARIANT",
		72: "ERROR_CODE_UNKNOWN_REF",
		80: "ERROR_CODE_RULE_VIOLATED",
		81: "ERROR_CODE_EXPR_ERROR",
		90: "ERROR_CODE_INVALID_SCHEMA",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED":             0,
		"ERROR_CODE_TYPE_MISMATCH":           1,
		"ERROR_CODE_REQUIRED_MISSING":        2,
		"ERROR_CODE_NOT_NULLABLE":            3,
		"ERROR_CODE_UNKNOWN_FIELD":           4,
		"ERROR_CODE_IMMUTABLE_MODIFIED":      5,
		"ERROR_CODE_CONST_MISMATCH":          10,
		"ERROR_CODE_GT_VIOLATED":             11,
		"ERROR_CODE_GTE_VIOLATED":            12,
		"ERROR_CODE_LT_VIOLATED":             13,
		"ERROR_CODE_LTE_VIOLATED":            14,
		"ERROR_CODE_NOT_IN_ALLOWED_SET":      15,
		"ERROR_CODE_IN_FORBIDDEN_SET":        16,
		"ERROR_CODE_MULTIPLE_OF_VIOLATED":    17,
		"ERROR_CODE_LEN_MISMATCH":            20,
		"ERROR_CODE_MIN_LEN_VIOLATED":        21,
		"ERROR_CODE_MAX_LEN_VIOLATED":        22,
		"ERROR_CODE_PATTERN_MISMATCH":        23,
		"ERROR_CODE_FORMAT_MISMATCH":         24,
		"ERROR_CODE_PREFIX_MISMATCH":         25,
		"ERROR_CODE_SUFFIX_MISMATCH":         26,
		"ERROR_CODE_UNSUPPORTED_FORMAT":      27,
		"ERROR_CODE_CHOICE_NOT_ALLOWED":      30,
		"ERROR_CODE_MIN_ITEMS_VIOLATED":      40,
		"ERROR_CODE_MAX_ITEMS_VIOLATED":      41,
		"ERROR_CODE_NOT_UNIQUE":              42,
		"ERROR_CODE_LIST_COUNT_MISMATCH":     43,
		"ERROR_CODE_MIN_ENTRIES_VIOLATED":    50,
		"ERROR_CODE_MAX_ENTRIES_VIOLATED":    51,
		"ERROR_CODE_MIN_PROPERTIES_VIOLATED": 60,
		"ERROR_CODE_MAX_PROPERTIES_VIOLATED": 61,
		"ERROR_CODE_DISCRIMINATOR_MISSING":   70,
		"ERROR_CODE_UNKNOWN_VARIANT":         71,
		"ERROR_CODE_UNKNOWN_REF":             72,
		"ERROR_CODE_RULE_VIOLATED":           80,
		"ERROR_CODE_EXPR_ERROR":              81,
		"ERROR_CODE_INVALID_SCHEMA":          90,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_schemapb_errors_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_schemapb_errors_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_schemapb_errors_proto_rawDescGZIP(), []int{0}
}

// ValidationError is a single validation failure. The contract fields are
// path, code and the typed expected/actual values; ordering of errors in a
// ValidationResult is deterministic (schema field order, then constraint
// order) as defined by the spec, so conformance can compare results across
// implementations byte-for-byte.
type ValidationError struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Path to the failed field, e.g. "max_connections",
	// "subnets.my-subnet-a.cidr", "replicas[3].name". Empty for form-level
	// failures.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Stable machine code identifying the kind of failure.
	Code ErrorCode `protobuf:"varint,2,opt,name=code,proto3,enum=schemapb.ErrorCode" json:"code,omitempty"`
	// The constraint boundary that was violated (min/max/const/pattern/allowed
	// set/...), as a canonical Value. Absent when not applicable.
	Expected *Value `protobuf:"bytes,3,opt,name=expected,proto3,oneof" json:"expected,omitempty"`
	// The offending value, canonical form. Absent when not applicable; MASKED
	// (absent) for fields marked secret.
	Actual *Value `protobuf:"bytes,4,opt,name=actual,proto3,oneof" json:"actual,omitempty"`
	// Name of the structured constraint that failed ("gte", "pattern",
	// "min_items", ...). Empty for CEL-rule and schema-level failures.
	Constraint string `protobuf:"bytes,5,opt,name=constraint,proto3" json:"constraint,omitempty"`
	// For CEL failures: the source expression that was violated or errored.
	Expr string `protobuf:"bytes,6,opt,name=expr,proto3" json:"expr,omitempty"`
	// Id of the authored rule that failed, if it declared one.
	RuleId *string `protobuf:"bytes,7,opt,name=rule_id,json=ruleId,proto3,oneof" json:"rule_id,omitempty"`
	// Severity; defaults to ERROR. WARNING errors do not block submit.
	Severity Schema_Field_Severity `protobuf:"varint,8,opt,name=severity,proto3,enum=schemapb.Schema_Field_Severity" json:"severity,omitempty"`
	// Human-readable message rendered from the spec's shared template set.
	// Informative only — NOT part of the conformance contract.
	Message       string `protobuf:"bytes,9,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationError) Reset() {
	*x = ValidationError{}
	mi := &file_schemapb_errors_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationError) ProtoMessage() {}

func (x *ValidationError) ProtoReflect() protoreflect.Message {
	mi := &file_schemapb_errors_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationError.ProtoReflect.Descriptor instead.
func (*ValidationError) Descriptor() ([]byte, []int) {
	return file_schemapb_errors_proto_rawDescGZIP(), []int{0}
}

func (x *ValidationError) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ValidationError) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

func (x *ValidationError) GetExpected() *Value {
	if x != nil {
		return x.Expected
	}
	return nil
}

func (x *ValidationError) GetActual() *Value {
	if x != nil {
		return x.Actual
	}
	return nil
}

func (x *ValidationError) GetConstraint() string {
	if x != nil {
		return x.Constraint
	}
	return ""
}

func (x *ValidationError) GetExpr() string {
	if x != nil {
		return x.Expr
	}
	return ""
}

func (x *ValidationError) GetRuleId() string {
	if x != nil && x.RuleId != nil {
		return *x.RuleId
	}
	return ""
}

func (x *ValidationError) GetSeverity() Schema_Field_Severity {
	if x != nil {
		return x.Severity
	}
	return Schema_Field_SEVERITY_UNSPECIFIED
}

func (x *ValidationError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ValidationResult is the complete outcome of validating a form.
type ValidationResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// All failures, in the spec's deterministic order. Empty means valid.
	Errors        []*ValidationError `protobuf:"bytes,1,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationResult) Reset() {
	*x = ValidationResult{}
	mi := &file_schemapb_errors_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationResult) ProtoMessage() {}

func (x *ValidationResult) ProtoReflect() protoreflect.Message {
	mi := &file_schemapb_errors_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationResult.ProtoReflect.Descriptor instead.
func (*ValidationResult) Descriptor() ([]byte, []int) {
	return file_schemapb_errors_proto_rawDescGZIP(), []int{1}
}

func (x *ValidationResult) GetErrors() []*ValidationError {
	if x != nil {
		return x.Errors
	}
	return nil
}

var File_schemapb_errors_proto protoreflect.FileDescriptor

const file_schemapb_errors_proto_rawDesc = "" +
	"\n" +
	"\x15schemapb/errors.proto\x12\bschemapb\x1a\x15schemapb/schema.proto\x1a\x14schemapb/value.proto\"\xfb\x02\n" +
	"\x0fValidationError\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12'\n" +
	"\x04code\x18\x02 \x01(\x0e2\x13.schemapb.ErrorCodeR\x04code\x120\n" +
	"\bexpected\x18\x03 \x01(\v2\x0f.schemapb.ValueH\x00R\bexpected\x88\x01\x01\x12,\n" +
	"\x06actual\x18\x04 \x01(\v2\x0f.schemapb.ValueH\x01R\x06actual\x88\x01\x01\x12\x1e\n" +
	"\n" +
	"constraint\x18\x05 \x01(\tR\n" +
	"constraint\x12\x12\n" +
	"\x04expr\x18\x06 \x01(\tR\x04expr\x12\x1c\n" +
	"\arule_id\x18\a \x01(\tH\x02R\x06ruleId\x88\x01\x01\x12;\n" +
	"\bseverity\x18\b \x01(\x0e2\x1f.schemapb.Schema.Field.SeverityR\bseverity\x12\x18\n" +
	"\amessage\x18\t \x01(\tR\amessageB\v\n" +
	"\t_expectedB\t\n" +
	"\a_actualB\n" +
	"\n" +
	"\b_rule_id\"E\n" +
	"\x10ValidationResult\x121\n" +
	"\x06errors\x18\x01 \x03(\v2\x19.schemapb.ValidationErrorR\x06errors*\xbd\t\n" +
	"\tErrorCode\x12\x1a\n" +
	"\x16ERROR_CODE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18ERROR_CODE_TYPE_MISMATCH\x10\x01\x12\x1f\n" +
	"\x1bERROR_CODE_REQUIRED_MISSING\x10\x02\x12\x1b\n" +
	"\x17ERROR_CODE_NOT_NULLABLE\x10\x03\x12\x1c\n" +
	"\x18ERROR_CODE_UNKNOWN_FIELD\x10\x04\x12!\n" +
	"\x1dERROR_CODE_IMMUTABLE_MODIFIED\x10\x05\x12\x1d\n" +
	"\x19ERROR_CODE_CONST_MISMATCH\x10\n" +
	"\x12\x1a\n" +
	"\x16ERROR_CODE_GT_VIOLATED\x10\v\x12\x1b\n" +
	"\x17ERROR_CODE_GTE_VIOLATED\x10\f\x12\x1a\n" +
	"\x16ERROR_CODE_LT_VIOLATED\x10\r\x12\x1b\n" +
	"\x17ERROR_CODE_LTE_VIOLATED\x10\x0e\x12!\n" +
	"\x1dERROR_CODE_NOT_IN_ALLOWED_SET\x10\x0f\x12\x1f\n" +
	"\x1bERROR_CODE_IN_FORBIDDEN_SET\x10\x10\x12#\n" +
	"\x1fERROR_CODE_MULTIPLE_OF_VIOLATED\x10\x11\x12\x1b\n" +
	"\x17ERROR_CODE_LEN_MISMATCH\x10\x14\x12\x1f\n" +
	"\x1bERROR_CODE_MIN_LEN_VIOLATED\x10\x15\x12\x1f\n" +
	"\x1bERROR_CODE_MAX_LEN_VIOLATED\x10\x16\x12\x1f\n" +
	"\x1bERROR_CODE_PATTERN_MISMATCH\x10\x17\x12\x1e\n" +
	"\x1aERROR_CODE_FORMAT_MISMATCH\x10\x18\x12\x1e\n" +
	"\x1aERROR_CODE_PREFIX_MISMATCH\x10\x19\x12\x1e\n" +
	"\x1aERROR_CODE_SUFFIX_MISMATCH\x10\x1a\x12!\n" +
	"\x1dERROR_CODE_UNSUPPORTED_FORMAT\x10\x1b\x12!\n" +
	"\x1dERROR_CODE_CHOICE_NOT_ALLOWED\x10\x1e\x12!\n" +
	"\x1dERROR_CODE_MIN_ITEMS_VIOLATED\x10(\x12!\n" +
	"\x1dERROR_CODE_MAX_ITEMS_VIOLATED\x10)\x12\x19\n" +
	"\x15ERROR_CODE_NOT_UNIQUE\x10*\x12\"\n" +
	"\x1eERROR_CODE_LIST_COUNT_MISMATCH\x10+\x12#\n" +
	"\x1fERROR_CODE_MIN_ENTRIES_VIOLATED\x102\x12#\n" +
	"\x1fERROR_CODE_MAX_ENTRIES_VIOLATED\x103\x12&\n" +
	"\"ERROR_CODE_MIN_PROPERTIES_VIOLATED\x10<\x12&\n" +
	"\"ERROR_CODE_MAX_PROPERTIES_VIOLATED\x10=\x12$\n" +
	" ERROR_CODE_DISCRIMINATOR_MISSING\x10F\x12\x1e\n" +
	"\x1aERROR_CODE_UNKNOWN_VARIANT\x10G\x12\x1a\n" +
	"\x16ERROR_CODE_UNKNOWN_REF\x10H\x12\x1c\n" +
	"\x18ERROR_CODE_RULE_VIOLATED\x10P\x12\x19\n" +
	"\x15ERROR_CODE_EXPR_ERROR\x10Q\x12\x1d\n" +
	"\x19ERROR_CODE_INVALID_SCHEMA\x10ZB*Z(github.com/gopherex/schemapb/go/schemapbb\x06proto3"

var (
	file_schemapb_errors_proto_rawDescOnce sync.Once
	file_schemapb_errors_proto_rawDescData []byte
)

func file_schemapb_errors_proto_rawDescGZIP() []byte {
	file_schemapb_errors_proto_rawDescOnce.Do(func() {
		file_schemapb_errors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_schemapb_errors_proto_rawDesc), len(file_schemapb_errors_proto_rawDesc)))
	})
	return file_schemapb_errors_proto_rawDescData
}

var file_schemapb_errors_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_schemapb_errors_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_schemapb_errors_proto_goTypes = []any{
	(ErrorCode)(0),             // 0: schemapb.ErrorCode
	(*ValidationError)(nil),    // 1: schemapb.ValidationError
	(*ValidationResult)(nil),   // 2: schemapb.ValidationResult
	(*Value)(nil),              // 3: schemapb.Value
	(Schema_Field_Severity)(0), // 4: schemapb.Schema.Field.Severity
}
var file_schemapb_errors_proto_depIdxs = []int32{
	0, // 0: schemapb.ValidationError.code:type_name -> schemapb.ErrorCode
	3, // 1: schemapb.ValidationError.expected:type_name -> schemapb.Value
	3, // 2: schemapb.ValidationError.actual:type_name -> schemapb.Value
	4, // 3: schemapb.ValidationError.severity:type_name -> schemapb.Schema.Field.Severity
	1, // 4: schemapb.ValidationResult.errors:type_name -> schemapb.ValidationError
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_schemapb_errors_proto_init() }
func file_schemapb_errors_proto_init() {
	if File_schemapb_errors_proto != nil {
		return
	}
	file_schemapb_schema_proto_init()
	file_schemapb_value_proto_init()
	file_schemapb_errors_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_schemapb_errors_proto_rawDesc), len(file_schemapb_errors_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_schemapb_errors_proto_goTypes,
		DependencyIndexes: file_schemapb_errors_proto_depIdxs,
		EnumInfos:         file_schemapb_errors_proto_enumTypes,
		MessageInfos:      file_schemapb_errors_proto_msgTypes,
	}.Build()
	File_schemapb_errors_proto = out.File
	file_schemapb_errors_proto_goTypes = nil
	file_schemapb_errors_proto_depIdxs = nil
}
