// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: schemapb/runtime.proto

package schemapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Operations performed while resolving a form. No values or expressions.
type ResolveOperation int32

const (
	ResolveOperation_RESOLVE_OPERATION_UNSPECIFIED     ResolveOperation = 0
	ResolveOperation_RESOLVE_OPERATION_DEFAULT_APPLIED ResolveOperation = 1
	ResolveOperation_RESOLVE_OPERATION_COERCED         ResolveOperation = 2
	ResolveOperation_RESOLVE_OPERATION_NORMALIZED      ResolveOperation = 3
	ResolveOperation_RESOLVE_OPERATION_COMPUTED        ResolveOperation = 4
	ResolveOperation_RESOLVE_OPERATION_INACTIVE        ResolveOperation = 5
)

// Enum value maps for ResolveOperation.
var (
	ResolveOperation_name = map[int32]string{
		0: "RESOLVE_OPERATION_UNSPECIFIED",
		1: "RESOLVE_OPERATION_DEFAULT_APPLIED",
		2: "RESOLVE_OPERATION_COERCED",
		3: "RESOLVE_OPERATION_NORMALIZED",
		4: "RESOLVE_OPERATION_COMPUTED",
		5: "RESOLVE_OPERATION_INACTIVE",
	}
	ResolveOperation_value = map[string]int32{
		"RESOLVE_OPERATION_UNSPECIFIED":     0,
		"RESOLVE_OPERATION_DEFAULT_APPLIED": 1,
		"RESOLVE_OPERATION_COERCED":         2,
		"RESOLVE_OPERATION_NORMALIZED":      3,
		"RESOLVE_OPERATION_COMPUTED":        4,
		"RESOLVE_OPERATION_INACTIVE":        5,
	}
)

func (x ResolveOperation) Enum() *ResolveOperation {
	p := new(ResolveOperation)
	*p = x
	return p
}

func (x ResolveOperation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResolveOperation) Descriptor() protoreflect.EnumDescriptor {
	return file_schemapb_runtime_proto_enumTypes[0].Descriptor()
}

func (ResolveOperation) Type() protoreflect.EnumType {
	return &file_schemapb_runtime_proto_enumTypes[0]
}

func (x ResolveOperation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResolveOperation.Descriptor instead.
func (ResolveOperation) EnumDescriptor() ([]byte, []int) {
	return file_schemapb_runtime_proto_rawDescGZIP(), []int{0}
}

// SchemaRef selects a schema: either inline, or by identity (resolved from a
// registry).
type SchemaRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Source:
	//
	//	*SchemaRef_Id
	//	*SchemaRef_Schema
	Source        isSchemaRef_Source `protobuf_oneof:"source"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemaRef) Reset() {
	*x = SchemaRef{}
	mi := &file_schemapb_runtime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaRef) ProtoMessage() {}

func (x *SchemaRef) ProtoReflect() protoreflect.Message {
	mi := &file_schemapb_runtime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaRef.ProtoReflect.Descriptor instead.
func (*SchemaRef) Descriptor() ([]byte, []int) {
	return file_schemapb_runtime_proto_rawDescGZIP(), []int{0}
}

func (x *SchemaRef) GetSource() isSchemaRef_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *SchemaRef) GetId() *SchemaIdentity {
	if x != nil {
		if x, ok := x.Source.(*SchemaRef_Id); ok {
			return x.Id
		}
	}
	return nil
}

func (x *SchemaRef) GetSchema() *Schema {
	if x != nil {
		if x, ok := x.Source.(*SchemaRef_Schema); ok {
			return x.Schema
		}
	}
	return nil
}

type isSchemaRef_Source interface {
	isSchemaRef_Source()
}

type SchemaRef_Id struct {
	// Resolve a registered schema by identity.
	Id *SchemaIdentity `protobuf:"bytes,1,opt,name=id,proto3,oneof"`
}

type SchemaRef_Schema struct {
	// Use this schema directly, without registering it.
	Schema *Schema `protobuf:"bytes,2,opt,name=schema,proto3,oneof"`
}

func (*SchemaRef_Id) isSchemaRef_Source() {}

func (*SchemaRef_Schema) isSchemaRef_Source() {}

// Filled is a runtime form: a reference to the schema plus the values entered
// for it. The schema says what is allowed/derived; the values are what to
// check/resolve. It is mutable input (the thing being edited/validated).
type Filled struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Schema this form is filled against (by-id or inline).
	Schema *SchemaRef `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	// Form values the expressions read and the validator checks.
	Values        *StructValue `protobuf:"bytes,2,opt,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filled) Reset() {
	*x = Filled{}
	mi := &file_schemapb_runtime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filled) ProtoMessage() {}

func (x *Filled) ProtoReflect() protoreflect.Message {
	mi := &file_schemapb_runtime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filled.ProtoReflect.Descriptor instead.
func (*Filled) Descriptor() ([]byte, []int) {
	return file_schemapb_runtime_proto_rawDescGZIP(), []int{1}
}

func (x *Filled) GetSchema() *SchemaRef {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *Filled) GetValues() *StructValue {
	if x != nil {
		return x.Values
	}
	return nil
}

// Baked is a sealed result: the final values together with the schema they
// were validated and resolved against. It is a self-contained, immutable
// snapshot — "these exact values for this exact schema, not to be changed".
// Unlike Filled (which only references a schema and is mutable), Baked embeds
// the full schema and the frozen values, so it is portable and verifiable on
// its own. Whether a Baked still matches a given schema is checked by deep
// message equality of the embedded schema.
type Baked struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The schema these values were baked against (embedded, self-contained).
	Schema *Schema `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	// The final, resolved values — frozen.
	Values        *StructValue `protobuf:"bytes,2,opt,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Baked) Reset() {
	*x = Baked{}
	mi := &file_schemapb_runtime_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Baked) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Baked) ProtoMessage() {}

func (x *Baked) ProtoReflect() protoreflect.Message {
	mi := &file_schemapb_runtime_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Baked.ProtoReflect.Descriptor instead.
func (*Baked) Descriptor() ([]byte, []int) {
	return file_schemapb_runtime_proto_rawDescGZIP(), []int{2}
}

func (x *Baked) GetSchema() *Schema {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *Baked) GetValues() *StructValue {
	if x != nil {
		return x.Values
	}
	return nil
}

type ResolveEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	PathSegments  []*PathSegment         `protobuf:"bytes,2,rep,name=path_segments,json=pathSegments,proto3" json:"path_segments,omitempty"`
	Operation     ResolveOperation       `protobuf:"varint,3,opt,name=operation,proto3,enum=schemapb.ResolveOperation" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveEvent) Reset() {
	*x = ResolveEvent{}
	mi := &file_schemapb_runtime_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveEvent) ProtoMessage() {}

func (x *ResolveEvent) ProtoReflect() protoreflect.Message {
	mi := &file_schemapb_runtime_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveEvent.ProtoReflect.Descriptor instead.
func (*ResolveEvent) Descriptor() ([]byte, []int) {
	return file_schemapb_runtime_proto_rawDescGZIP(), []int{3}
}

func (x *ResolveEvent) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ResolveEvent) GetPathSegments() []*PathSegment {
	if x != nil {
		return x.PathSegments
	}
	return nil
}

func (x *ResolveEvent) GetOperation() ResolveOperation {
	if x != nil {
		return x.Operation
	}
	return ResolveOperation_RESOLVE_OPERATION_UNSPECIFIED
}

// Execution order: seed, normalize, dependency-ordered computed. Fields use
// declaration order, lists index order, maps UTF-8 key order. Available even
// after failure; events describe completed operations, not a valid snapshot.
type ResolveReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*ResolveEvent        `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveReport) Reset() {
	*x = ResolveReport{}
	mi := &file_schemapb_runtime_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveReport) ProtoMessage() {}

func (x *ResolveReport) ProtoReflect() protoreflect.Message {
	mi := &file_schemapb_runtime_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveReport.ProtoReflect.Descriptor instead.
func (*ResolveReport) Descriptor() ([]byte, []int) {
	return file_schemapb_runtime_proto_rawDescGZIP(), []int{4}
}

func (x *ResolveReport) GetEvents() []*ResolveEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_schemapb_runtime_proto protoreflect.FileDescriptor

const file_schemapb_runtime_proto_rawDesc = "" +
	"\n" +
	"\x16schemapb/runtime.proto\x12\bschemapb\x1a\x15schemapb/schema.proto\x1a\x14schemapb/value.proto\"m\n" +
	"\tSchemaRef\x12*\n" +
	"\x02id\x18\x01 \x01(\v2\x18.schemapb.SchemaIdentityH\x00R\x02id\x12*\n" +
	"\x06schema\x18\x02 \x01(\v2\x10.schemapb.SchemaH\x00R\x06schemaB\b\n" +
	"\x06source\"d\n" +
	"\x06Filled\x12+\n" +
	"\x06schema\x18\x01 \x01(\v2\x13.schemapb.SchemaRefR\x06schema\x12-\n" +
	"\x06values\x18\x02 \x01(\v2\x15.schemapb.StructValueR\x06values\"`\n" +
	"\x05Baked\x12(\n" +
	"\x06schema\x18\x01 \x01(\v2\x10.schemapb.SchemaR\x06schema\x12-\n" +
	"\x06values\x18\x02 \x01(\v2\x15.schemapb.StructValueR\x06values\"\x98\x01\n" +
	"\fResolveEvent\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12:\n" +
	"\rpath_segments\x18\x02 \x03(\v2\x15.schemapb.PathSegmentR\fpathSegments\x128\n" +
	"\toperation\x18\x03 \x01(\x0e2\x1a.schemapb.ResolveOperationR\toperation\"?\n" +
	"\rResolveReport\x12.\n" +
	"\x06events\x18\x01 \x03(\v2\x16.schemapb.ResolveEventR\x06events*\xdd\x01\n" +
	"\x10ResolveOperation\x12!\n" +
	"\x1dRESOLVE_OPERATION_UNSPECIFIED\x10\x00\x12%\n" +
	"!RESOLVE_OPERATION_DEFAULT_APPLIED\x10\x01\x12\x1d\n" +
	"\x19RESOLVE_OPERATION_COERCED\x10\x02\x12 \n" +
	"\x1cRESOLVE_OPERATION_NORMALIZED\x10\x03\x12\x1e\n" +
	"\x1aRESOLVE_OPERATION_COMPUTED\x10\x04\x12\x1e\n" +
	"\x1aRESOLVE_OPERATION_INACTIVE\x10\x05B*Z(github.com/gopherex/schemapb/go/schemapbb\x06proto3"

var (
	file_schemapb_runtime_proto_rawDescOnce sync.Once
	file_schemapb_runtime_proto_rawDescData []byte
)

func file_schemapb_runtime_proto_rawDescGZIP() []byte {
	file_schemapb_runtime_proto_rawDescOnce.Do(func() {
		file_schemapb_runtime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_schemapb_runtime_proto_rawDesc), len(file_schemapb_runtime_proto_rawDesc)))
	})
	return file_schemapb_runtime_proto_rawDescData
}

var file_schemapb_runtime_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_schemapb_runtime_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_schemapb_runtime_proto_goTypes = []any{
	(ResolveOperation)(0),  // 0: schemapb.ResolveOperation
	(*SchemaRef)(nil),      // 1: schemapb.SchemaRef
	(*Filled)(nil),         // 2: schemapb.Filled
	(*Baked)(nil),          // 3: schemapb.Baked
	(*ResolveEvent)(nil),   // 4: schemapb.ResolveEvent
	(*ResolveReport)(nil),  // 5: schemapb.ResolveReport
	(*SchemaIdentity)(nil), // 6: schemapb.SchemaIdentity
	(*Schema)(nil),         // 7: schemapb.Schema
	(*StructValue)(nil),    // 8: schemapb.StructValue
	(*PathSegment)(nil),    // 9: schemapb.PathSegment
}
var file_schemapb_runtime_proto_depIdxs = []int32{
	6, // 0: schemapb.SchemaRef.id:type_name -> schemapb.SchemaIdentity
	7, // 1: schemapb.SchemaRef.schema:type_name -> schemapb.Schema
	1, // 2: schemapb.Filled.schema:type_name -> schemapb.SchemaRef
	8, // 3: schemapb.Filled.values:type_name -> schemapb.StructValue
	7, // 4: schemapb.Baked.schema:type_name -> schemapb.Schema
	8, // 5: schemapb.Baked.values:type_name -> schemapb.StructValue
	9, // 6: schemapb.ResolveEvent.path_segments:type_name -> schemapb.PathSegment
	0, // 7: schemapb.ResolveEvent.operation:type_name -> schemapb.ResolveOperation
	4, // 8: schemapb.ResolveReport.events:type_name -> schemapb.ResolveEvent
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_schemapb_runtime_proto_init() }
func file_schemapb_runtime_proto_init() {
	if File_schemapb_runtime_proto != nil {
		return
	}
	file_schemapb_schema_proto_init()
	file_schemapb_value_proto_init()
	file_schemapb_runtime_proto_msgTypes[0].OneofWrappers = []any{
		(*SchemaRef_Id)(nil),
		(*SchemaRef_Schema)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_schemapb_runtime_proto_rawDesc), len(file_schemapb_runtime_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_schemapb_runtime_proto_goTypes,
		DependencyIndexes: file_schemapb_runtime_proto_depIdxs,
		EnumInfos:         file_schemapb_runtime_proto_enumTypes,
		MessageInfos:      file_schemapb_runtime_proto_msgTypes,
	}.Build()
	File_schemapb_runtime_proto = out.File
	file_schemapb_runtime_proto_goTypes = nil
	file_schemapb_runtime_proto_depIdxs = nil
}
