// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: schemapb/runtime.proto

package schemapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SchemaRef selects a schema: either inline, or by identity (resolved from a
// registry).
type SchemaRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Source:
	//
	//	*SchemaRef_Id
	//	*SchemaRef_Schema
	Source        isSchemaRef_Source `protobuf_oneof:"source"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemaRef) Reset() {
	*x = SchemaRef{}
	mi := &file_schemapb_runtime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaRef) ProtoMessage() {}

func (x *SchemaRef) ProtoReflect() protoreflect.Message {
	mi := &file_schemapb_runtime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaRef.ProtoReflect.Descriptor instead.
func (*SchemaRef) Descriptor() ([]byte, []int) {
	return file_schemapb_runtime_proto_rawDescGZIP(), []int{0}
}

func (x *SchemaRef) GetSource() isSchemaRef_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *SchemaRef) GetId() *SchemaIdentity {
	if x != nil {
		if x, ok := x.Source.(*SchemaRef_Id); ok {
			return x.Id
		}
	}
	return nil
}

func (x *SchemaRef) GetSchema() *Schema {
	if x != nil {
		if x, ok := x.Source.(*SchemaRef_Schema); ok {
			return x.Schema
		}
	}
	return nil
}

type isSchemaRef_Source interface {
	isSchemaRef_Source()
}

type SchemaRef_Id struct {
	// Resolve a registered schema by identity.
	Id *SchemaIdentity `protobuf:"bytes,1,opt,name=id,proto3,oneof"`
}

type SchemaRef_Schema struct {
	// Use this schema directly, without registering it.
	Schema *Schema `protobuf:"bytes,2,opt,name=schema,proto3,oneof"`
}

func (*SchemaRef_Id) isSchemaRef_Source() {}

func (*SchemaRef_Schema) isSchemaRef_Source() {}

// Filled is a runtime form: a reference to the schema plus the values entered
// for it. The schema says what is allowed/derived; the values are what to
// check/resolve. It is mutable input (the thing being edited/validated).
type Filled struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Schema this form is filled against (by-id or inline).
	Schema *SchemaRef `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	// Form values the expressions read and the validator checks.
	Values        *StructValue `protobuf:"bytes,2,opt,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filled) Reset() {
	*x = Filled{}
	mi := &file_schemapb_runtime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filled) ProtoMessage() {}

func (x *Filled) ProtoReflect() protoreflect.Message {
	mi := &file_schemapb_runtime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filled.ProtoReflect.Descriptor instead.
func (*Filled) Descriptor() ([]byte, []int) {
	return file_schemapb_runtime_proto_rawDescGZIP(), []int{1}
}

func (x *Filled) GetSchema() *SchemaRef {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *Filled) GetValues() *StructValue {
	if x != nil {
		return x.Values
	}
	return nil
}

// Baked is a sealed result: the final values together with the schema they
// were validated and resolved against. It is a self-contained, immutable
// snapshot — "these exact values for this exact schema, not to be changed".
// Unlike Filled (which only references a schema and is mutable), Baked embeds
// the full schema and the frozen values, so it is portable and verifiable on
// its own. Whether a Baked still matches a given schema is checked by deep
// message equality of the embedded schema.
type Baked struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The schema these values were baked against (embedded, self-contained).
	Schema *Schema `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	// The final, resolved values — frozen.
	Values        *StructValue `protobuf:"bytes,2,opt,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Baked) Reset() {
	*x = Baked{}
	mi := &file_schemapb_runtime_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Baked) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Baked) ProtoMessage() {}

func (x *Baked) ProtoReflect() protoreflect.Message {
	mi := &file_schemapb_runtime_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Baked.ProtoReflect.Descriptor instead.
func (*Baked) Descriptor() ([]byte, []int) {
	return file_schemapb_runtime_proto_rawDescGZIP(), []int{2}
}

func (x *Baked) GetSchema() *Schema {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *Baked) GetValues() *StructValue {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_schemapb_runtime_proto protoreflect.FileDescriptor

const file_schemapb_runtime_proto_rawDesc = "" +
	"\n" +
	"\x16schemapb/runtime.proto\x12\bschemapb\x1a\x15schemapb/schema.proto\x1a\x14schemapb/value.proto\"m\n" +
	"\tSchemaRef\x12*\n" +
	"\x02id\x18\x01 \x01(\v2\x18.schemapb.SchemaIdentityH\x00R\x02id\x12*\n" +
	"\x06schema\x18\x02 \x01(\v2\x10.schemapb.SchemaH\x00R\x06schemaB\b\n" +
	"\x06source\"d\n" +
	"\x06Filled\x12+\n" +
	"\x06schema\x18\x01 \x01(\v2\x13.schemapb.SchemaRefR\x06schema\x12-\n" +
	"\x06values\x18\x02 \x01(\v2\x15.schemapb.StructValueR\x06values\"`\n" +
	"\x05Baked\x12(\n" +
	"\x06schema\x18\x01 \x01(\v2\x10.schemapb.SchemaR\x06schema\x12-\n" +
	"\x06values\x18\x02 \x01(\v2\x15.schemapb.StructValueR\x06valuesB*Z(github.com/gopherex/schemapb/go/schemapbb\x06proto3"

var (
	file_schemapb_runtime_proto_rawDescOnce sync.Once
	file_schemapb_runtime_proto_rawDescData []byte
)

func file_schemapb_runtime_proto_rawDescGZIP() []byte {
	file_schemapb_runtime_proto_rawDescOnce.Do(func() {
		file_schemapb_runtime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_schemapb_runtime_proto_rawDesc), len(file_schemapb_runtime_proto_rawDesc)))
	})
	return file_schemapb_runtime_proto_rawDescData
}

var file_schemapb_runtime_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_schemapb_runtime_proto_goTypes = []any{
	(*SchemaRef)(nil),      // 0: schemapb.SchemaRef
	(*Filled)(nil),         // 1: schemapb.Filled
	(*Baked)(nil),          // 2: schemapb.Baked
	(*SchemaIdentity)(nil), // 3: schemapb.SchemaIdentity
	(*Schema)(nil),         // 4: schemapb.Schema
	(*StructValue)(nil),    // 5: schemapb.StructValue
}
var file_schemapb_runtime_proto_depIdxs = []int32{
	3, // 0: schemapb.SchemaRef.id:type_name -> schemapb.SchemaIdentity
	4, // 1: schemapb.SchemaRef.schema:type_name -> schemapb.Schema
	0, // 2: schemapb.Filled.schema:type_name -> schemapb.SchemaRef
	5, // 3: schemapb.Filled.values:type_name -> schemapb.StructValue
	4, // 4: schemapb.Baked.schema:type_name -> schemapb.Schema
	5, // 5: schemapb.Baked.values:type_name -> schemapb.StructValue
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_schemapb_runtime_proto_init() }
func file_schemapb_runtime_proto_init() {
	if File_schemapb_runtime_proto != nil {
		return
	}
	file_schemapb_schema_proto_init()
	file_schemapb_value_proto_init()
	file_schemapb_runtime_proto_msgTypes[0].OneofWrappers = []any{
		(*SchemaRef_Id)(nil),
		(*SchemaRef_Schema)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_schemapb_runtime_proto_rawDesc), len(file_schemapb_runtime_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_schemapb_runtime_proto_goTypes,
		DependencyIndexes: file_schemapb_runtime_proto_depIdxs,
		MessageInfos:      file_schemapb_runtime_proto_msgTypes,
	}.Build()
	File_schemapb_runtime_proto = out.File
	file_schemapb_runtime_proto_goTypes = nil
	file_schemapb_runtime_proto_depIdxs = nil
}
