// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: schemapb/value.proto

package schemapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NullValue is the singleton null.
type NullValue int32

const (
	NullValue_NULL_VALUE NullValue = 0
)

// Enum value maps for NullValue.
var (
	NullValue_name = map[int32]string{
		0: "NULL_VALUE",
	}
	NullValue_value = map[string]int32{
		"NULL_VALUE": 0,
	}
)

func (x NullValue) Enum() *NullValue {
	p := new(NullValue)
	*p = x
	return p
}

func (x NullValue) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NullValue) Descriptor() protoreflect.EnumDescriptor {
	return file_schemapb_value_proto_enumTypes[0].Descriptor()
}

func (NullValue) Type() protoreflect.EnumType {
	return &file_schemapb_value_proto_enumTypes[0]
}

func (x NullValue) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NullValue.Descriptor instead.
func (NullValue) EnumDescriptor() ([]byte, []int) {
	return file_schemapb_value_proto_rawDescGZIP(), []int{0}
}

// Value is the typed value container for schemapb. It replaces
// google.protobuf.Value (a JSON model where every number is a double) so that
// integer kinds keep full 64-bit precision across languages.
//
// Mapping to CEL types is 1:1 and defined by the spec:
//
//	int32/int64   -> int        uint32/uint64 -> uint
//	float/double  -> double     bool          -> bool
//	string        -> string     duration      -> google.protobuf.Duration
//	timestamp     -> google.protobuf.Timestamp
//	list          -> list       struct        -> map
//	null          -> null       bytes         -> bytes
//
// In protoJSON, int64/uint64 serialise as strings (standard protobuf JSON
// mapping), so JavaScript clients keep precision via bigint.
//
// Canonical form (REQUIRED for conformance): a value stored for a field MUST
// use the variant matching the field's declared kind — e.g. an Int64 field's
// value is always `int64_value`, never `int32_value`, even when it fits.
type Value struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Value_NullValue
	//	*Value_BoolValue
	//	*Value_Int32Value
	//	*Value_Int64Value
	//	*Value_Uint32Value
	//	*Value_Uint64Value
	//	*Value_FloatValue
	//	*Value_DoubleValue
	//	*Value_StringValue
	//	*Value_DurationValue
	//	*Value_TimestampValue
	//	*Value_ListValue
	//	*Value_StructValue
	//	*Value_BytesValue
	Kind          isValue_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_schemapb_value_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_schemapb_value_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_schemapb_value_proto_rawDescGZIP(), []int{0}
}

func (x *Value) GetKind() isValue_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Value) GetNullValue() NullValue {
	if x != nil {
		if x, ok := x.Kind.(*Value_NullValue); ok {
			return x.NullValue
		}
	}
	return NullValue_NULL_VALUE
}

func (x *Value) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Kind.(*Value_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *Value) GetInt32Value() int32 {
	if x != nil {
		if x, ok := x.Kind.(*Value_Int32Value); ok {
			return x.Int32Value
		}
	}
	return 0
}

func (x *Value) GetInt64Value() int64 {
	if x != nil {
		if x, ok := x.Kind.(*Value_Int64Value); ok {
			return x.Int64Value
		}
	}
	return 0
}

func (x *Value) GetUint32Value() uint32 {
	if x != nil {
		if x, ok := x.Kind.(*Value_Uint32Value); ok {
			return x.Uint32Value
		}
	}
	return 0
}

func (x *Value) GetUint64Value() uint64 {
	if x != nil {
		if x, ok := x.Kind.(*Value_Uint64Value); ok {
			return x.Uint64Value
		}
	}
	return 0
}

func (x *Value) GetFloatValue() float32 {
	if x != nil {
		if x, ok := x.Kind.(*Value_FloatValue); ok {
			return x.FloatValue
		}
	}
	return 0
}

func (x *Value) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Kind.(*Value_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *Value) GetStringValue() string {
	if x != nil {
		if x, ok := x.Kind.(*Value_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *Value) GetDurationValue() *durationpb.Duration {
	if x != nil {
		if x, ok := x.Kind.(*Value_DurationValue); ok {
			return x.DurationValue
		}
	}
	return nil
}

func (x *Value) GetTimestampValue() *timestamppb.Timestamp {
	if x != nil {
		if x, ok := x.Kind.(*Value_TimestampValue); ok {
			return x.TimestampValue
		}
	}
	return nil
}

func (x *Value) GetListValue() *ListValue {
	if x != nil {
		if x, ok := x.Kind.(*Value_ListValue); ok {
			return x.ListValue
		}
	}
	return nil
}

func (x *Value) GetStructValue() *StructValue {
	if x != nil {
		if x, ok := x.Kind.(*Value_StructValue); ok {
			return x.StructValue
		}
	}
	return nil
}

func (x *Value) GetBytesValue() []byte {
	if x != nil {
		if x, ok := x.Kind.(*Value_BytesValue); ok {
			return x.BytesValue
		}
	}
	return nil
}

type isValue_Kind interface {
	isValue_Kind()
}

type Value_NullValue struct {
	NullValue NullValue `protobuf:"varint,1,opt,name=null_value,json=nullValue,proto3,enum=schemapb.NullValue,oneof"`
}

type Value_BoolValue struct {
	BoolValue bool `protobuf:"varint,2,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type Value_Int32Value struct {
	Int32Value int32 `protobuf:"varint,3,opt,name=int32_value,json=int32Value,proto3,oneof"`
}

type Value_Int64Value struct {
	Int64Value int64 `protobuf:"varint,4,opt,name=int64_value,json=int64Value,proto3,oneof"`
}

type Value_Uint32Value struct {
	Uint32Value uint32 `protobuf:"varint,5,opt,name=uint32_value,json=uint32Value,proto3,oneof"`
}

type Value_Uint64Value struct {
	Uint64Value uint64 `protobuf:"varint,6,opt,name=uint64_value,json=uint64Value,proto3,oneof"`
}

type Value_FloatValue struct {
	FloatValue float32 `protobuf:"fixed32,7,opt,name=float_value,json=floatValue,proto3,oneof"`
}

type Value_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,8,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type Value_StringValue struct {
	StringValue string `protobuf:"bytes,9,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type Value_DurationValue struct {
	DurationValue *durationpb.Duration `protobuf:"bytes,10,opt,name=duration_value,json=durationValue,proto3,oneof"`
}

type Value_TimestampValue struct {
	TimestampValue *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=timestamp_value,json=timestampValue,proto3,oneof"`
}

type Value_ListValue struct {
	ListValue *ListValue `protobuf:"bytes,12,opt,name=list_value,json=listValue,proto3,oneof"`
}

type Value_StructValue struct {
	StructValue *StructValue `protobuf:"bytes,13,opt,name=struct_value,json=structValue,proto3,oneof"`
}

type Value_BytesValue struct {
	BytesValue []byte `protobuf:"bytes,14,opt,name=bytes_value,json=bytesValue,proto3,oneof"`
}

func (*Value_NullValue) isValue_Kind() {}

func (*Value_BoolValue) isValue_Kind() {}

func (*Value_Int32Value) isValue_Kind() {}

func (*Value_Int64Value) isValue_Kind() {}

func (*Value_Uint32Value) isValue_Kind() {}

func (*Value_Uint64Value) isValue_Kind() {}

func (*Value_FloatValue) isValue_Kind() {}

func (*Value_DoubleValue) isValue_Kind() {}

func (*Value_StringValue) isValue_Kind() {}

func (*Value_DurationValue) isValue_Kind() {}

func (*Value_TimestampValue) isValue_Kind() {}

func (*Value_ListValue) isValue_Kind() {}

func (*Value_StructValue) isValue_Kind() {}

func (*Value_BytesValue) isValue_Kind() {}

// ListValue is an ordered sequence of values.
type ListValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Value               `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListValue) Reset() {
	*x = ListValue{}
	mi := &file_schemapb_value_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListValue) ProtoMessage() {}

func (x *ListValue) ProtoReflect() protoreflect.Message {
	mi := &file_schemapb_value_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListValue.ProtoReflect.Descriptor instead.
func (*ListValue) Descriptor() ([]byte, []int) {
	return file_schemapb_value_proto_rawDescGZIP(), []int{1}
}

func (x *ListValue) GetItems() []*Value {
	if x != nil {
		return x.Items
	}
	return nil
}

// StructValue is a string-keyed map of values: the representation of a whole
// form, an Object field's value, and a Map field's value.
type StructValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        map[string]*Value      `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StructValue) Reset() {
	*x = StructValue{}
	mi := &file_schemapb_value_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StructValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StructValue) ProtoMessage() {}

func (x *StructValue) ProtoReflect() protoreflect.Message {
	mi := &file_schemapb_value_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StructValue.ProtoReflect.Descriptor instead.
func (*StructValue) Descriptor() ([]byte, []int) {
	return file_schemapb_value_proto_rawDescGZIP(), []int{2}
}

func (x *StructValue) GetFields() map[string]*Value {
	if x != nil {
		return x.Fields
	}
	return nil
}

var File_schemapb_value_proto protoreflect.FileDescriptor

const file_schemapb_value_proto_rawDesc = "" +
	"\n" +
	"\x14schemapb/value.proto\x12\bschemapb\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x83\x05\n" +
	"\x05Value\x124\n" +
	"\n" +
	"null_value\x18\x01 \x01(\x0e2\x13.schemapb.NullValueH\x00R\tnullValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x02 \x01(\bH\x00R\tboolValue\x12!\n" +
	"\vint32_value\x18\x03 \x01(\x05H\x00R\n" +
	"int32Value\x12!\n" +
	"\vint64_value\x18\x04 \x01(\x03H\x00R\n" +
	"int64Value\x12#\n" +
	"\fuint32_value\x18\x05 \x01(\rH\x00R\vuint32Value\x12#\n" +
	"\fuint64_value\x18\x06 \x01(\x04H\x00R\vuint64Value\x12!\n" +
	"\vfloat_value\x18\a \x01(\x02H\x00R\n" +
	"floatValue\x12#\n" +
	"\fdouble_value\x18\b \x01(\x01H\x00R\vdoubleValue\x12#\n" +
	"\fstring_value\x18\t \x01(\tH\x00R\vstringValue\x12B\n" +
	"\x0eduration_value\x18\n" +
	" \x01(\v2\x19.google.protobuf.DurationH\x00R\rdurationValue\x12E\n" +
	"\x0ftimestamp_value\x18\v \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x0etimestampValue\x124\n" +
	"\n" +
	"list_value\x18\f \x01(\v2\x13.schemapb.ListValueH\x00R\tlistValue\x12:\n" +
	"\fstruct_value\x18\r \x01(\v2\x15.schemapb.StructValueH\x00R\vstructValue\x12!\n" +
	"\vbytes_value\x18\x0e \x01(\fH\x00R\n" +
	"bytesValueB\x06\n" +
	"\x04kind\"2\n" +
	"\tListValue\x12%\n" +
	"\x05items\x18\x01 \x03(\v2\x0f.schemapb.ValueR\x05items\"\x94\x01\n" +
	"\vStructValue\x129\n" +
	"\x06fields\x18\x01 \x03(\v2!.schemapb.StructValue.FieldsEntryR\x06fields\x1aJ\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12%\n" +
	"\x05value\x18\x02 \x01(\v2\x0f.schemapb.ValueR\x05value:\x028\x01*\x1b\n" +
	"\tNullValue\x12\x0e\n" +
	"\n" +
	"NULL_VALUE\x10\x00B*Z(github.com/gopherex/schemapb/go/schemapbb\x06proto3"

var (
	file_schemapb_value_proto_rawDescOnce sync.Once
	file_schemapb_value_proto_rawDescData []byte
)

func file_schemapb_value_proto_rawDescGZIP() []byte {
	file_schemapb_value_proto_rawDescOnce.Do(func() {
		file_schemapb_value_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_schemapb_value_proto_rawDesc), len(file_schemapb_value_proto_rawDesc)))
	})
	return file_schemapb_value_proto_rawDescData
}

var file_schemapb_value_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_schemapb_value_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_schemapb_value_proto_goTypes = []any{
	(NullValue)(0),                // 0: schemapb.NullValue
	(*Value)(nil),                 // 1: schemapb.Value
	(*ListValue)(nil),             // 2: schemapb.ListValue
	(*StructValue)(nil),           // 3: schemapb.StructValue
	nil,                           // 4: schemapb.StructValue.FieldsEntry
	(*durationpb.Duration)(nil),   // 5: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_schemapb_value_proto_depIdxs = []int32{
	0, // 0: schemapb.Value.null_value:type_name -> schemapb.NullValue
	5, // 1: schemapb.Value.duration_value:type_name -> google.protobuf.Duration
	6, // 2: schemapb.Value.timestamp_value:type_name -> google.protobuf.Timestamp
	2, // 3: schemapb.Value.list_value:type_name -> schemapb.ListValue
	3, // 4: schemapb.Value.struct_value:type_name -> schemapb.StructValue
	1, // 5: schemapb.ListValue.items:type_name -> schemapb.Value
	4, // 6: schemapb.StructValue.fields:type_name -> schemapb.StructValue.FieldsEntry
	1, // 7: schemapb.StructValue.FieldsEntry.value:type_name -> schemapb.Value
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_schemapb_value_proto_init() }
func file_schemapb_value_proto_init() {
	if File_schemapb_value_proto != nil {
		return
	}
	file_schemapb_value_proto_msgTypes[0].OneofWrappers = []any{
		(*Value_NullValue)(nil),
		(*Value_BoolValue)(nil),
		(*Value_Int32Value)(nil),
		(*Value_Int64Value)(nil),
		(*Value_Uint32Value)(nil),
		(*Value_Uint64Value)(nil),
		(*Value_FloatValue)(nil),
		(*Value_DoubleValue)(nil),
		(*Value_StringValue)(nil),
		(*Value_DurationValue)(nil),
		(*Value_TimestampValue)(nil),
		(*Value_ListValue)(nil),
		(*Value_StructValue)(nil),
		(*Value_BytesValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_schemapb_value_proto_rawDesc), len(file_schemapb_value_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_schemapb_value_proto_goTypes,
		DependencyIndexes: file_schemapb_value_proto_depIdxs,
		EnumInfos:         file_schemapb_value_proto_enumTypes,
		MessageInfos:      file_schemapb_value_proto_msgTypes,
	}.Build()
	File_schemapb_value_proto = out.File
	file_schemapb_value_proto_goTypes = nil
	file_schemapb_value_proto_depIdxs = nil
}
