// @generated
// This file is @generated by prost-build.
///
/// Value is the typed value container for schemapb. It replaces
/// google.protobuf.Value (a JSON model where every number is a double) so that
/// integer kinds keep full 64-bit precision across languages.
///
/// Mapping to CEL types is 1:1 and defined by the spec:
///    int32/int64   -> int        uint32/uint64 -> uint
///    float/double  -> double     bool          -> bool
///    string        -> string     duration      -> google.protobuf.Duration
///    timestamp     -> google.protobuf.Timestamp
///    list          -> list       struct        -> map
///    null          -> null       bytes         -> bytes
///
/// In protoJSON, int64/uint64 serialise as strings (standard protobuf JSON
/// mapping), so JavaScript clients keep precision via bigint.
///
/// Canonical form (REQUIRED for conformance): a value stored for a field MUST
/// use the variant matching the field's declared kind — e.g. an Int64 field's
/// value is always `int64_value`, never `int32_value`, even when it fits.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Value {
    #[prost(oneof="value::Kind", tags="1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14")]
    pub kind: ::core::option::Option<value::Kind>,
}
/// Nested message and enum types in `Value`.
pub mod value {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Kind {
        #[prost(enumeration="super::NullValue", tag="1")]
        NullValue(i32),
        #[prost(bool, tag="2")]
        BoolValue(bool),
        #[prost(int32, tag="3")]
        Int32Value(i32),
        #[prost(int64, tag="4")]
        Int64Value(i64),
        #[prost(uint32, tag="5")]
        Uint32Value(u32),
        #[prost(uint64, tag="6")]
        Uint64Value(u64),
        #[prost(float, tag="7")]
        FloatValue(f32),
        #[prost(double, tag="8")]
        DoubleValue(f64),
        #[prost(string, tag="9")]
        StringValue(::prost::alloc::string::String),
        #[prost(message, tag="10")]
        DurationValue(::prost_types::Duration),
        #[prost(message, tag="11")]
        TimestampValue(::prost_types::Timestamp),
        #[prost(message, tag="12")]
        ListValue(super::ListValue),
        #[prost(message, tag="13")]
        StructValue(super::StructValue),
        #[prost(bytes, tag="14")]
        BytesValue(::prost::alloc::vec::Vec<u8>),
    }
}
/// ListValue is an ordered sequence of values. 
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListValue {
    #[prost(message, repeated, tag="1")]
    pub items: ::prost::alloc::vec::Vec<Value>,
}
///
/// StructValue is a string-keyed map of values: the representation of a whole
/// form, an Object field's value, and a Map field's value.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StructValue {
    #[prost(map="string, message", tag="1")]
    pub fields: ::std::collections::HashMap<::prost::alloc::string::String, Value>,
}
/// NullValue is the singleton null. 
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum NullValue {
    NullValue = 0,
}
impl NullValue {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::NullValue => "NULL_VALUE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "NULL_VALUE" => Some(Self::NullValue),
            _ => None,
        }
    }
}
///
/// Schema is a runtime, dynamic form/config descriptor. A producer builds a
/// Schema and ships it (as a protobuf message) to any consumer — Go, TypeScript,
/// Python or Rust — which validates values, computes derived fields and renders
/// text output natively. Cross-implementation agreement is guaranteed by the
/// schemapb spec and its conformance suite, not by sharing a runtime.
///
/// Validation has two layers:
///    - per-kind structured rules (gt/gte/lt/lte/in/pattern/...) for the common,
///      single-field cases. Ergonomic to author and introspectable by renderers
///      (e.g. slider bounds).
///    - Field.rules / Schema.rules: CEL expressions (<https://cel.dev>) for
///      cross-field and conditional validation.
///
/// Expression language: full CEL spec plus the `strings` extension. Expressions
/// must be pure and deterministic (no now()/rand, no implicit timezones) so all
/// implementations agree. Variables bound by the engine:
///    `this` — the current field's value (field-level rules/normalize only)
///    `root` — the whole form as a map (inputs + already-computed values)
///
/// Render templates are Mustache (<https://mustache.github.io>); see
/// Schema.templates.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Schema {
    /// Stable identity of this schema. Required: the validator rejects a schema
    /// whose id is unset or whose name is empty. 
    #[prost(message, optional, tag="1")]
    pub id: ::core::option::Option<SchemaIdentity>,
    /// Human description of the schema. 
    #[prost(string, optional, tag="2")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
    /// The fields that make up the form. 
    #[prost(message, repeated, tag="3")]
    pub fields: ::prost::alloc::vec::Vec<schema::Field>,
    /// Form-wide invariant rules (`root` only, no `this`). 
    #[prost(message, repeated, tag="4")]
    pub rules: ::prost::alloc::vec::Vec<schema::field::Rule>,
    ///
    /// If true, any key in the values map that is not a declared field name is
    /// an error (ERROR_CODE_UNKNOWN_FIELD).
    #[prost(bool, tag="5")]
    pub strict: bool,
    /// Minimum number of properties that must be present in the values map. 
    #[prost(uint64, optional, tag="6")]
    pub min_properties: ::core::option::Option<u64>,
    /// Maximum number of properties allowed in the values map. 
    #[prost(uint64, optional, tag="7")]
    pub max_properties: ::core::option::Option<u64>,
    ///
    /// If true, scalar string inputs are coerced to the field's kind before
    /// validation (numeric kinds parse the string as a number; bool parses
    /// "true"/"false"; enum parses an integer string). Only applied when the
    /// current value is a string but the field's kind expects a different type
    /// and parsing succeeds; unparseable strings are left as-is so the type
    /// error is reported normally.
    #[prost(bool, tag="8")]
    pub coerce: bool,
    ///
    /// Named reusable sub-schemas ($defs). Fields of kind Ref resolve their
    /// value against the named def found here. Meaningful only on the root
    /// schema; defs inside nested schemas are ignored by the engine.
    #[prost(map="string, message", tag="9")]
    pub defs: ::std::collections::HashMap<::prost::alloc::string::String, Schema>,
    ///
    /// Named render templates (Mustache syntax, <https://mustache.github.io>) for
    /// serialising resolved values into a target text format, e.g. "conf" -> a
    /// postgresql.conf template. Portable data: every implementation renders
    /// them identically (per the Mustache spec and the schemapb render-context
    /// spec). The template executes against a context exposing the ordered
    /// fields, fields grouped by `group`, and the raw values; formatting
    /// helpers (on/off, yes/no, quoted, upper/lower) are precomputed context
    /// fields, not template functions. Complex logic belongs in Computed
    /// fields, not in templates. The validation/compute engine ignores these.
    #[prost(map="string, string", tag="10")]
    pub templates: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
}
/// Nested message and enum types in `Schema`.
pub mod schema {
    ///
    /// Field is one field of the form.
    ///
    /// Per-field evaluation order (each stage reads the form as resolved by the
    /// previous one):
    ///    1. when         — gate: if false the field is INACTIVE and every stage
    ///                      below is skipped; the field is treated as ABSENT (its
    ///                      value, if any, is preserved but ignored). For a
    ///                      container kind (Object/OneOf/List/Map/Ref) the WHOLE
    ///                      subtree is gated.
    ///    2. normalize    — map the field's own value.
    ///    3. Computed     — derive the value from `root`.
    ///    4. options_expr / count_expr — dynamic Choice options / List length.
    ///    5. rules + kind constraints — required/nullable, gt/lt/in/pattern, ...
    ///
    /// Renderer contract: an inactive field (when=false) MUST NOT be rendered.
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct Field {
        /// Field name; the key under which the value lives in the form. 
        #[prost(string, tag="1")]
        pub name: ::prost::alloc::string::String,
        /// Human description of the field. 
        #[prost(string, optional, tag="2")]
        pub description: ::core::option::Option<::prost::alloc::string::String>,
        /// If true, the value may be null/empty. 
        #[prost(bool, tag="3")]
        pub nullable: bool,
        /// If true, the value must be present. 
        #[prost(bool, tag="4")]
        pub required: bool,
        /// Cross-field CEL validation rules (`this` is bound to this field). 
        #[prost(message, repeated, tag="5")]
        pub rules: ::prost::alloc::vec::Vec<field::Rule>,
        ///
        /// If true, the value is system-fixed: it equals `default` and cannot be
        /// changed. The validator forces it to `default` and rejects any
        /// different submitted value; renderers show it disabled. A "system
        /// value" is therefore immutable + default.
        #[prost(bool, tag="20")]
        pub immutable: bool,
        ///
        /// Informative section label for grouping fields (e.g. "WAL"). Purely
        /// informative — the validation/compute engine ignores it.
        #[prost(string, optional, tag="21")]
        pub group: ::core::option::Option<::prost::alloc::string::String>,
        ///
        /// Informative unit of the value, e.g. "MB" or "ms". Purely informative —
        /// the engine ignores it; it is for renderers/serializers.
        #[prost(string, optional, tag="22")]
        pub unit: ::core::option::Option<::prost::alloc::string::String>,
        /// Informative human title for the field. Engine ignores it. 
        #[prost(string, optional, tag="23")]
        pub title: ::core::option::Option<::prost::alloc::string::String>,
        /// If true, this field is deprecated; renderers may warn. Informative. 
        #[prost(bool, tag="24")]
        pub deprecated: bool,
        /// Example values for documentation/rendering. Purely informative. 
        #[prost(message, repeated, tag="25")]
        pub examples: ::prost::alloc::vec::Vec<super::Value>,
        /// If true, the value is sensitive (e.g. a password). Informative. 
        #[prost(bool, tag="26")]
        pub secret: bool,
        ///
        /// Normalize expression: a CEL expression mapping the field's own value
        /// before validation. `this` = current value, `root` = whole form.
        /// Returns the new value. Applied after defaults/coercion and before
        /// Computed evaluation and validation.
        #[prost(string, optional, tag="27")]
        pub normalize: ::core::option::Option<::prost::alloc::string::String>,
        ///
        /// Conditional gate: a CEL boolean expression over `root` (the whole form
        /// as a map). When it evaluates to false the field is INACTIVE — the
        /// validator skips it ENTIRELY (no required/nullable, no rules, no kind
        /// constraints, no Computed/normalize) and treats it as ABSENT regardless
        /// of any value present in `values`. For a container kind the whole
        /// subtree is gated. Inactive fields do not count toward
        /// min/max_properties and their value key never raises a strict
        /// ERROR_CODE_UNKNOWN_FIELD. Their value is NOT deleted, so it reappears
        /// if the field becomes active again. Renderers MUST hide an inactive
        /// field. `this` is NOT bound (a field's own value must not gate its
        /// existence). Empty/absent => always active. A non-bool result is a
        /// runtime error.
        #[prost(string, optional, tag="30")]
        pub when: ::core::option::Option<::prost::alloc::string::String>,
        /// The field kind; exactly one must be set. 
        #[prost(oneof="field::Kind", tags="6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 28, 29, 31, 32, 33")]
        pub kind: ::core::option::Option<field::Kind>,
    }
    /// Nested message and enum types in `Field`.
    pub mod field {
        ///
        /// Float field kind and its single-field constraints.
        /// gt = exclusive min (> 0), gte = inclusive min (>= 1).
        /// lt = exclusive max, lte = inclusive max.
        #[derive(Clone, PartialEq, ::prost::Message)]
        pub struct Float {
            /// Default value used when the field is unset. 
            #[prost(float, optional, tag="1")]
            pub default: ::core::option::Option<f32>,
            /// Value must equal exactly this. 
            #[prost(float, optional, tag="2")]
            pub r#const: ::core::option::Option<f32>,
            /// Exclusive minimum: value > gt. 
            #[prost(float, optional, tag="3")]
            pub gt: ::core::option::Option<f32>,
            /// Inclusive minimum: value >= gte. 
            #[prost(float, optional, tag="4")]
            pub gte: ::core::option::Option<f32>,
            /// Exclusive maximum: value < lt. 
            #[prost(float, optional, tag="5")]
            pub lt: ::core::option::Option<f32>,
            /// Inclusive maximum: value <= lte. 
            #[prost(float, optional, tag="6")]
            pub lte: ::core::option::Option<f32>,
            /// Value must be one of these. 
            #[prost(float, repeated, tag="7")]
            pub r#in: ::prost::alloc::vec::Vec<f32>,
            /// Value must not be any of these. 
            #[prost(float, repeated, tag="8")]
            pub not_in: ::prost::alloc::vec::Vec<f32>,
            /// Divisibility: quotient value/multiple_of must be whole. 
            #[prost(float, optional, tag="9")]
            pub multiple_of: ::core::option::Option<f32>,
        }
        /// Double field kind and its single-field constraints. 
        #[derive(Clone, PartialEq, ::prost::Message)]
        pub struct Double {
            /// Default value used when the field is unset. 
            #[prost(double, optional, tag="1")]
            pub default: ::core::option::Option<f64>,
            /// Value must equal exactly this. 
            #[prost(double, optional, tag="2")]
            pub r#const: ::core::option::Option<f64>,
            /// Exclusive minimum: value > gt. 
            #[prost(double, optional, tag="3")]
            pub gt: ::core::option::Option<f64>,
            /// Inclusive minimum: value >= gte. 
            #[prost(double, optional, tag="4")]
            pub gte: ::core::option::Option<f64>,
            /// Exclusive maximum: value < lt. 
            #[prost(double, optional, tag="5")]
            pub lt: ::core::option::Option<f64>,
            /// Inclusive maximum: value <= lte. 
            #[prost(double, optional, tag="6")]
            pub lte: ::core::option::Option<f64>,
            /// Value must be one of these. 
            #[prost(double, repeated, tag="7")]
            pub r#in: ::prost::alloc::vec::Vec<f64>,
            /// Value must not be any of these. 
            #[prost(double, repeated, tag="8")]
            pub not_in: ::prost::alloc::vec::Vec<f64>,
            /// Divisibility: quotient value/multiple_of must be whole. 
            #[prost(double, optional, tag="9")]
            pub multiple_of: ::core::option::Option<f64>,
        }
        /// Int32 field kind and its single-field constraints. 
        #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
        pub struct Int32 {
            /// Default value used when the field is unset. 
            #[prost(int32, optional, tag="1")]
            pub default: ::core::option::Option<i32>,
            /// Value must equal exactly this. 
            #[prost(int32, optional, tag="2")]
            pub r#const: ::core::option::Option<i32>,
            /// Exclusive minimum: value > gt. 
            #[prost(int32, optional, tag="3")]
            pub gt: ::core::option::Option<i32>,
            /// Inclusive minimum: value >= gte. 
            #[prost(int32, optional, tag="4")]
            pub gte: ::core::option::Option<i32>,
            /// Exclusive maximum: value < lt. 
            #[prost(int32, optional, tag="5")]
            pub lt: ::core::option::Option<i32>,
            /// Inclusive maximum: value <= lte. 
            #[prost(int32, optional, tag="6")]
            pub lte: ::core::option::Option<i32>,
            /// Value must be one of these. 
            #[prost(int32, repeated, tag="7")]
            pub r#in: ::prost::alloc::vec::Vec<i32>,
            /// Value must not be any of these. 
            #[prost(int32, repeated, tag="8")]
            pub not_in: ::prost::alloc::vec::Vec<i32>,
            /// Divisibility: value % multiple_of must be 0. 
            #[prost(int32, optional, tag="9")]
            pub multiple_of: ::core::option::Option<i32>,
        }
        /// Int64 field kind and its single-field constraints. 
        #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
        pub struct Int64 {
            /// Default value used when the field is unset. 
            #[prost(int64, optional, tag="1")]
            pub default: ::core::option::Option<i64>,
            /// Value must equal exactly this. 
            #[prost(int64, optional, tag="2")]
            pub r#const: ::core::option::Option<i64>,
            /// Exclusive minimum: value > gt. 
            #[prost(int64, optional, tag="3")]
            pub gt: ::core::option::Option<i64>,
            /// Inclusive minimum: value >= gte. 
            #[prost(int64, optional, tag="4")]
            pub gte: ::core::option::Option<i64>,
            /// Exclusive maximum: value < lt. 
            #[prost(int64, optional, tag="5")]
            pub lt: ::core::option::Option<i64>,
            /// Inclusive maximum: value <= lte. 
            #[prost(int64, optional, tag="6")]
            pub lte: ::core::option::Option<i64>,
            /// Value must be one of these. 
            #[prost(int64, repeated, tag="7")]
            pub r#in: ::prost::alloc::vec::Vec<i64>,
            /// Value must not be any of these. 
            #[prost(int64, repeated, tag="8")]
            pub not_in: ::prost::alloc::vec::Vec<i64>,
            /// Divisibility: value % multiple_of must be 0. 
            #[prost(int64, optional, tag="9")]
            pub multiple_of: ::core::option::Option<i64>,
        }
        /// UInt32 field kind and its single-field constraints. 
        #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
        pub struct UInt32 {
            /// Default value used when the field is unset. 
            #[prost(uint32, optional, tag="1")]
            pub default: ::core::option::Option<u32>,
            /// Value must equal exactly this. 
            #[prost(uint32, optional, tag="2")]
            pub r#const: ::core::option::Option<u32>,
            /// Exclusive minimum: value > gt. 
            #[prost(uint32, optional, tag="3")]
            pub gt: ::core::option::Option<u32>,
            /// Inclusive minimum: value >= gte. 
            #[prost(uint32, optional, tag="4")]
            pub gte: ::core::option::Option<u32>,
            /// Exclusive maximum: value < lt. 
            #[prost(uint32, optional, tag="5")]
            pub lt: ::core::option::Option<u32>,
            /// Inclusive maximum: value <= lte. 
            #[prost(uint32, optional, tag="6")]
            pub lte: ::core::option::Option<u32>,
            /// Value must be one of these. 
            #[prost(uint32, repeated, tag="7")]
            pub r#in: ::prost::alloc::vec::Vec<u32>,
            /// Value must not be any of these. 
            #[prost(uint32, repeated, tag="8")]
            pub not_in: ::prost::alloc::vec::Vec<u32>,
            /// Divisibility: value % multiple_of must be 0. 
            #[prost(uint32, optional, tag="9")]
            pub multiple_of: ::core::option::Option<u32>,
        }
        /// UInt64 field kind and its single-field constraints. 
        #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
        pub struct UInt64 {
            /// Default value used when the field is unset. 
            #[prost(uint64, optional, tag="1")]
            pub default: ::core::option::Option<u64>,
            /// Value must equal exactly this. 
            #[prost(uint64, optional, tag="2")]
            pub r#const: ::core::option::Option<u64>,
            /// Exclusive minimum: value > gt. 
            #[prost(uint64, optional, tag="3")]
            pub gt: ::core::option::Option<u64>,
            /// Inclusive minimum: value >= gte. 
            #[prost(uint64, optional, tag="4")]
            pub gte: ::core::option::Option<u64>,
            /// Exclusive maximum: value < lt. 
            #[prost(uint64, optional, tag="5")]
            pub lt: ::core::option::Option<u64>,
            /// Inclusive maximum: value <= lte. 
            #[prost(uint64, optional, tag="6")]
            pub lte: ::core::option::Option<u64>,
            /// Value must be one of these. 
            #[prost(uint64, repeated, tag="7")]
            pub r#in: ::prost::alloc::vec::Vec<u64>,
            /// Value must not be any of these. 
            #[prost(uint64, repeated, tag="8")]
            pub not_in: ::prost::alloc::vec::Vec<u64>,
            /// Divisibility: value % multiple_of must be 0. 
            #[prost(uint64, optional, tag="9")]
            pub multiple_of: ::core::option::Option<u64>,
        }
        /// Bool field kind. 
        #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
        pub struct Bool {
            /// Default value used when the field is unset. 
            #[prost(bool, optional, tag="1")]
            pub default: ::core::option::Option<bool>,
            /// Value must equal exactly this. 
            #[prost(bool, optional, tag="2")]
            pub r#const: ::core::option::Option<bool>,
        }
        /// String field kind and its single-field constraints. 
        #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
        pub struct String {
            /// Default value used when the field is unset. 
            #[prost(string, optional, tag="1")]
            pub default: ::core::option::Option<::prost::alloc::string::String>,
            /// Value must equal exactly this. 
            #[prost(string, optional, tag="2")]
            pub r#const: ::core::option::Option<::prost::alloc::string::String>,
            /// Exact character (Unicode code point) length required. 
            #[prost(uint64, optional, tag="3")]
            pub len: ::core::option::Option<u64>,
            /// Minimum character length. 
            #[prost(uint64, optional, tag="4")]
            pub min_len: ::core::option::Option<u64>,
            /// Maximum character length. 
            #[prost(uint64, optional, tag="5")]
            pub max_len: ::core::option::Option<u64>,
            /// RE2 regular expression the value must match. 
            #[prost(string, optional, tag="6")]
            pub pattern: ::core::option::Option<::prost::alloc::string::String>,
            /// Value must be one of these. 
            #[prost(string, repeated, tag="7")]
            pub r#in: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
            /// Value must not be any of these. 
            #[prost(string, repeated, tag="8")]
            pub not_in: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
            ///
            /// Semantic format the value must conform to. An OPEN identifier
            /// resolved against the spec's format registry, not a closed enum:
            /// adding a format never changes this contract.
            ///
            /// Core formats (every implementation MUST support): "email", "url",
            /// "uuid", "ipv4", "ipv6", "ip", "hostname", "date", "time",
            /// "datetime". Registry extensions use namespaced ids (e.g.
            /// "k8s.quantity") and each ships with its own spec text and
            /// conformance fixtures; implementations declare which extensions
            /// they support. A format the implementation does not know is a
            /// validation failure (ERROR_CODE_UNSUPPORTED_FORMAT) — never a
            /// silent pass. Empty => no format check.
            #[prost(string, optional, tag="9")]
            pub format: ::core::option::Option<::prost::alloc::string::String>,
        }
        /// Bytes field kind and its single-field constraints. Values travel as
        /// protobuf bytes (base64 in protoJSON) and are CEL-native `bytes`. 
        #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
        pub struct Bytes {
            /// Default value used when the field is unset. 
            #[prost(bytes="vec", optional, tag="1")]
            pub default: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
            /// Value must equal exactly this. 
            #[prost(bytes="vec", optional, tag="2")]
            pub r#const: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
            /// Exact byte length required. 
            #[prost(uint64, optional, tag="3")]
            pub len: ::core::option::Option<u64>,
            /// Minimum byte length. 
            #[prost(uint64, optional, tag="4")]
            pub min_len: ::core::option::Option<u64>,
            /// Maximum byte length. 
            #[prost(uint64, optional, tag="5")]
            pub max_len: ::core::option::Option<u64>,
            /// Value must start with this prefix. 
            #[prost(bytes="vec", optional, tag="6")]
            pub prefix: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
            /// Value must end with this suffix. 
            #[prost(bytes="vec", optional, tag="7")]
            pub suffix: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
            /// Value must be one of these. 
            #[prost(bytes="vec", repeated, tag="8")]
            pub r#in: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
            /// Value must not be any of these. 
            #[prost(bytes="vec", repeated, tag="9")]
            pub not_in: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
        }
        ///
        /// Json field kind: a free-form value accepted WITHOUT structural
        /// validation — any Value variant (scalar, list, struct, null) passes.
        /// Use for passthrough configuration blobs, annotations, extension data.
        /// CEL sees the value as `dyn`; Field.rules still apply if authored.
        #[derive(Clone, PartialEq, ::prost::Message)]
        pub struct Json {
            /// Default value used when the field is unset. 
            #[prost(message, optional, tag="1")]
            pub default: ::core::option::Option<super::super::Value>,
        }
        ///
        /// Choice field kind: a closed (or advisory) set of allowed values with
        /// optional human labels — the "enum" of schemapb, generalised. Options
        /// carry typed Values, so string-valued domains ("ssd"/"hdd",
        /// "minimal"/"replica"/"logical") are first-class: no artificial integer
        /// codes. Renderers draw a select/dropdown from options (label falls
        /// back to the value's display form).
        #[derive(Clone, PartialEq, ::prost::Message)]
        pub struct Choice {
            /// The static allowed set (and the renderer's option list). 
            #[prost(message, repeated, tag="1")]
            pub options: ::prost::alloc::vec::Vec<choice::Option>,
            /// Default value used when the field is unset. 
            #[prost(message, optional, tag="2")]
            pub default: ::core::option::Option<super::super::Value>,
            ///
            /// If true the set is advisory: values outside options validate fine
            /// (options become suggestions). If false (default) a value not in the
            /// allowed set is ERROR_CODE_CHOICE_NOT_ALLOWED.
            #[prost(bool, tag="3")]
            pub open: bool,
            ///
            /// CEL expression over `root` returning the list of allowed values.
            /// When set it REPLACES the static options for validation and supplies
            /// the option list to renderers. Empty/absent => use options. A
            /// non-list result is a runtime error. Use cases: db versions by kind,
            /// zones by region.
            #[prost(string, optional, tag="4")]
            pub options_expr: ::core::option::Option<::prost::alloc::string::String>,
        }
        /// Nested message and enum types in `Choice`.
        pub mod choice {
            /// One selectable option. 
            #[derive(Clone, PartialEq, ::prost::Message)]
            pub struct Option {
                /// The value this option stands for (typed). 
                #[prost(message, optional, tag="1")]
                pub value: ::core::option::Option<super::super::super::Value>,
                /// Human label for renderers; empty => display the value itself. 
                #[prost(string, tag="2")]
                pub label: ::prost::alloc::string::String,
                /// Human description of the option. 
                #[prost(string, tag="3")]
                pub description: ::prost::alloc::string::String,
                /// Renderers may hide or warn on deprecated options. 
                #[prost(bool, tag="4")]
                pub deprecated: bool,
            }
        }
        /// Duration field kind with optional range bounds. 
        #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
        pub struct Duration {
            /// Default value used when the field is unset. 
            #[prost(message, optional, tag="1")]
            pub default: ::core::option::Option<::prost_types::Duration>,
            /// Exclusive minimum: value > gt. 
            #[prost(message, optional, tag="2")]
            pub gt: ::core::option::Option<::prost_types::Duration>,
            /// Inclusive minimum: value >= gte. 
            #[prost(message, optional, tag="3")]
            pub gte: ::core::option::Option<::prost_types::Duration>,
            /// Exclusive maximum: value < lt. 
            #[prost(message, optional, tag="4")]
            pub lt: ::core::option::Option<::prost_types::Duration>,
            /// Inclusive maximum: value <= lte. 
            #[prost(message, optional, tag="5")]
            pub lte: ::core::option::Option<::prost_types::Duration>,
        }
        /// Timestamp field kind with optional range bounds. 
        #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
        pub struct Timestamp {
            /// Default value used when the field is unset. 
            #[prost(message, optional, tag="1")]
            pub default: ::core::option::Option<::prost_types::Timestamp>,
            /// Exclusive minimum: value > gt. 
            #[prost(message, optional, tag="2")]
            pub gt: ::core::option::Option<::prost_types::Timestamp>,
            /// Inclusive minimum: value >= gte. 
            #[prost(message, optional, tag="3")]
            pub gte: ::core::option::Option<::prost_types::Timestamp>,
            /// Exclusive maximum: value < lt. 
            #[prost(message, optional, tag="4")]
            pub lt: ::core::option::Option<::prost_types::Timestamp>,
            /// Inclusive maximum: value <= lte. 
            #[prost(message, optional, tag="5")]
            pub lte: ::core::option::Option<::prost_types::Timestamp>,
        }
        /// List field kind: a repeated value described by its element field(s). 
        #[derive(Clone, PartialEq, ::prost::Message)]
        pub struct List {
            /// Element field definition(s) describing list items. 
            #[prost(message, repeated, tag="1")]
            pub items: ::prost::alloc::vec::Vec<super::Field>,
            /// Minimum number of items. 
            #[prost(uint64, optional, tag="2")]
            pub min_items: ::core::option::Option<u64>,
            /// Maximum number of items. 
            #[prost(uint64, optional, tag="3")]
            pub max_items: ::core::option::Option<u64>,
            /// If true, items must be unique. 
            #[prost(bool, tag="4")]
            pub unique: bool,
            ///
            /// CEL expression over `root` returning a non-negative int: the exact
            /// number of items the list must have. Renderers generate that many
            /// item slots. The list length must equal the result, else
            /// ERROR_CODE_LIST_COUNT_MISMATCH. Empty/absent => length bounded only
            /// by min_items/max_items. A non-int or negative result is a runtime
            /// error. Each item is still validated by the item schema; inside an
            /// item's rules the item's zero-based position is bound as `index`.
            /// Use case: per-machine settings where N = replicas + 1.
            #[prost(string, optional, tag="5")]
            pub count_expr: ::core::option::Option<::prost::alloc::string::String>,
        }
        /// Object field kind: a nested sub-form described by its own Schema. 
        #[derive(Clone, PartialEq, ::prost::Message)]
        pub struct Object {
            /// Nested object schema. 
            #[prost(message, optional, tag="1")]
            pub schema: ::core::option::Option<super::super::Schema>,
        }
        ///
        /// Map field kind: free-form string keys (never rejected — e.g. user-chosen
        /// subnet/VM names) with values validated against a single shared Schema.
        /// Unlike Object (fixed, named fields), a Map's key set is arbitrary and
        /// runtime-supplied; every value is validated against the same
        /// `value_schema`, so if that schema is `strict` an unknown key INSIDE a
        /// value is rejected while the map's own keys stay unconstrained. The
        /// rejected field path names the map key, e.g.
        /// "subnets.my-subnet-a.evil_key".
        #[derive(Clone, PartialEq, ::prost::Message)]
        pub struct Map {
            /// Schema every map value must satisfy. Absent => values are accepted
            /// unvalidated (any object). 
            #[prost(message, optional, tag="1")]
            pub value_schema: ::core::option::Option<super::super::Schema>,
            /// Minimum number of entries. 
            #[prost(uint64, optional, tag="2")]
            pub min_entries: ::core::option::Option<u64>,
            /// Maximum number of entries. 
            #[prost(uint64, optional, tag="3")]
            pub max_entries: ::core::option::Option<u64>,
        }
        ///
        /// Computed field kind: a value derived from other values, not entered by
        /// the user. Every implementation evaluates `expr` and writes the result
        /// under this field's name, so other expressions and validation rules can
        /// read it via `root`.
        ///
        /// Evaluation is dependency-ordered: a Computed field may reference inputs
        /// and other Computed fields. Cycles are rejected at schema-validation
        /// time. Referencing a value that is absent at evaluation time is an error
        /// (surfaced as a ValidationError on this field's path).
        ///
        /// `expr` must be a pure, deterministic CEL expression (no now()/rand) so
        /// all implementations agree.
        #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
        pub struct Computed {
            /// CEL expression producing the value. Reads `root` (inputs + already
            /// computed values). Bound the same way as Rule expressions. 
            #[prost(string, tag="1")]
            pub expr: ::prost::alloc::string::String,
            /// Result type, used to marshal the value back into the form as a
            /// canonical Value variant. Optional: if unset the implementation
            /// infers the type from the type-checked expression. 
            #[prost(enumeration="ResultType", optional, tag="2")]
            pub result: ::core::option::Option<i32>,
        }
        ///
        /// Rule is a CEL validation expression for cross-field / conditional
        /// checks.
        /// Context: `this` = this field's value (field-level rules only);
        ///           `root` = whole form as a map, any field reachable.
        /// expr must evaluate to bool; true means VALID.
        #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
        pub struct Rule {
            /// CEL boolean expression; true means the value is valid. 
            #[prost(string, tag="1")]
            pub expr: ::prost::alloc::string::String,
            /// Message shown to the user when expr is false. 
            #[prost(string, tag="2")]
            pub message: ::prost::alloc::string::String,
            /// Stable rule id, for mapping errors back to rules. 
            #[prost(string, optional, tag="3")]
            pub id: ::core::option::Option<::prost::alloc::string::String>,
            /// Severity; defaults to ERROR. 
            #[prost(enumeration="Severity", optional, tag="4")]
            pub severity: ::core::option::Option<i32>,
        }
        ///
        /// OneOf field kind: a discriminated union. The value must be an object
        /// whose discriminator property selects a variant schema.
        #[derive(Clone, PartialEq, ::prost::Message)]
        pub struct OneOf {
            /// Property name in the value object that selects the variant. 
            #[prost(string, tag="1")]
            pub discriminator: ::prost::alloc::string::String,
            /// Variant schemas keyed by the discriminator value. 
            #[prost(map="string, message", tag="2")]
            pub variants: ::std::collections::HashMap<::prost::alloc::string::String, super::super::Schema>,
        }
        ///
        /// Ref field kind: the value is an object validated against another
        /// schema. The target is selected one of two ways:
        ///    - name: a key in the root schema's defs map (local composition;
        ///      enables recursion — a def may Ref back to itself, terminating on
        ///      the finite data).
        ///    - id:   the SchemaIdentity of a separately-registered schema. The
        ///      identity is PRESERVED on the node (renderers can show/link the
        ///      target), and the referenced schema must be made resolvable —
        ///      either present in the root defs under its identity key, or pulled
        ///      in by Link(resolver) before validation. An id-ref to a schema not
        ///      present in defs is ERROR_CODE_UNKNOWN_REF at validate time.
        #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
        pub struct Ref {
            #[prost(oneof="r#ref::Target", tags="1, 2")]
            pub target: ::core::option::Option<r#ref::Target>,
        }
        /// Nested message and enum types in `Ref`.
        pub mod r#ref {
            #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
            pub enum Target {
                /// Name of the def in the root schema's defs map. 
                #[prost(string, tag="1")]
                Name(::prost::alloc::string::String),
                /// Identity of a registered schema (resolved via defs / Link). 
                #[prost(message, tag="2")]
                Id(super::super::super::SchemaIdentity),
            }
        }
        /// ResultType is the value type a Computed expression yields. 
        #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
        #[repr(i32)]
        pub enum ResultType {
            /// Unset: infer from the expression. 
            Unspecified = 0,
            Double = 1,
            Int64 = 2,
            Uint64 = 3,
            Bool = 4,
            String = 5,
            Duration = 6,
            Timestamp = 7,
            Bytes = 8,
            /// Arbitrary Value: the expression result is stored as-is (dyn). 
            Json = 9,
        }
        impl ResultType {
            /// String value of the enum field names used in the ProtoBuf definition.
            ///
            /// The values are not transformed in any way and thus are considered stable
            /// (if the ProtoBuf definition does not change) and safe for programmatic use.
            pub fn as_str_name(&self) -> &'static str {
                match self {
                    Self::Unspecified => "RESULT_TYPE_UNSPECIFIED",
                    Self::Double => "RESULT_TYPE_DOUBLE",
                    Self::Int64 => "RESULT_TYPE_INT64",
                    Self::Uint64 => "RESULT_TYPE_UINT64",
                    Self::Bool => "RESULT_TYPE_BOOL",
                    Self::String => "RESULT_TYPE_STRING",
                    Self::Duration => "RESULT_TYPE_DURATION",
                    Self::Timestamp => "RESULT_TYPE_TIMESTAMP",
                    Self::Bytes => "RESULT_TYPE_BYTES",
                    Self::Json => "RESULT_TYPE_JSON",
                }
            }
            /// Creates an enum from field names used in the ProtoBuf definition.
            pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
                match value {
                    "RESULT_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
                    "RESULT_TYPE_DOUBLE" => Some(Self::Double),
                    "RESULT_TYPE_INT64" => Some(Self::Int64),
                    "RESULT_TYPE_UINT64" => Some(Self::Uint64),
                    "RESULT_TYPE_BOOL" => Some(Self::Bool),
                    "RESULT_TYPE_STRING" => Some(Self::String),
                    "RESULT_TYPE_DURATION" => Some(Self::Duration),
                    "RESULT_TYPE_TIMESTAMP" => Some(Self::Timestamp),
                    "RESULT_TYPE_BYTES" => Some(Self::Bytes),
                    "RESULT_TYPE_JSON" => Some(Self::Json),
                    _ => None,
                }
            }
        }
        /// Severity of a failed rule. 
        #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
        #[repr(i32)]
        pub enum Severity {
            /// Unset: treated as ERROR. 
            Unspecified = 0,
            /// Blocks submit. 
            Error = 1,
            /// Surfaced to the user but does not block submit. 
            Warning = 2,
        }
        impl Severity {
            /// String value of the enum field names used in the ProtoBuf definition.
            ///
            /// The values are not transformed in any way and thus are considered stable
            /// (if the ProtoBuf definition does not change) and safe for programmatic use.
            pub fn as_str_name(&self) -> &'static str {
                match self {
                    Self::Unspecified => "SEVERITY_UNSPECIFIED",
                    Self::Error => "SEVERITY_ERROR",
                    Self::Warning => "SEVERITY_WARNING",
                }
            }
            /// Creates an enum from field names used in the ProtoBuf definition.
            pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
                match value {
                    "SEVERITY_UNSPECIFIED" => Some(Self::Unspecified),
                    "SEVERITY_ERROR" => Some(Self::Error),
                    "SEVERITY_WARNING" => Some(Self::Warning),
                    _ => None,
                }
            }
        }
        /// The field kind; exactly one must be set. 
        #[derive(Clone, PartialEq, ::prost::Oneof)]
        pub enum Kind {
            /// Float field. 
            #[prost(message, tag="6")]
            Float(Float),
            /// Double field. 
            #[prost(message, tag="7")]
            Double(Double),
            /// Int32 field. 
            #[prost(message, tag="8")]
            Int32(Int32),
            /// Int64 field. 
            #[prost(message, tag="9")]
            Int64(Int64),
            /// UInt32 field. 
            #[prost(message, tag="10")]
            Uint32(UInt32),
            /// UInt64 field. 
            #[prost(message, tag="11")]
            Uint64(UInt64),
            /// Bool field. 
            #[prost(message, tag="12")]
            Bool(Bool),
            /// String field. 
            #[prost(message, tag="13")]
            String(String),
            /// Choice (closed value set) field. 
            #[prost(message, tag="14")]
            Choice(Choice),
            /// Duration field. 
            #[prost(message, tag="15")]
            Duration(Duration),
            /// Timestamp field. 
            #[prost(message, tag="16")]
            Timestamp(Timestamp),
            /// List field. 
            #[prost(message, tag="17")]
            List(List),
            /// Nested object field. 
            #[prost(message, tag="18")]
            Object(Object),
            /// Computed (derived) field. 
            #[prost(message, tag="19")]
            Computed(Computed),
            /// Discriminated union field. 
            #[prost(message, tag="28")]
            OneOf(OneOf),
            /// Reference to a named definition in the root schema's defs. 
            #[prost(message, tag="29")]
            Ref(Ref),
            /// Free-key, typed-value map field. 
            #[prost(message, tag="31")]
            Map(Map),
            /// Bytes field. 
            #[prost(message, tag="32")]
            Bytes(Bytes),
            /// Free-form JSON value field. 
            #[prost(message, tag="33")]
            Json(Json),
        }
    }
}
///
/// SchemaIdentity is the stable, system-assigned identity of a Schema. A Schema
/// is addressed by this identity rather than a free-form name.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SchemaIdentity {
    /// Grouping namespace, e.g. a product or team. Optional. 
    #[prost(string, tag="1")]
    pub namespace: ::prost::alloc::string::String,
    /// Schema name, unique within its namespace. Required. 
    #[prost(string, tag="2")]
    pub name: ::prost::alloc::string::String,
    /// Schema version, e.g. "v1" or a semver string. Optional. 
    #[prost(string, tag="3")]
    pub version: ::prost::alloc::string::String,
}
///
/// ValidationError is a single validation failure. The contract fields are
/// path, code and the typed expected/actual values; ordering of errors in a
/// ValidationResult is deterministic (schema field order, then constraint
/// order) as defined by the spec, so conformance can compare results across
/// implementations byte-for-byte.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ValidationError {
    /// Path to the failed field, e.g. "max_connections",
    /// "subnets.my-subnet-a.cidr", "replicas\[3\].name". Empty for form-level
    /// failures. 
    #[prost(string, tag="1")]
    pub path: ::prost::alloc::string::String,
    /// Stable machine code identifying the kind of failure. 
    #[prost(enumeration="ErrorCode", tag="2")]
    pub code: i32,
    /// The constraint boundary that was violated (min/max/const/pattern/allowed
    /// set/...), as a canonical Value. Absent when not applicable. 
    #[prost(message, optional, tag="3")]
    pub expected: ::core::option::Option<Value>,
    /// The offending value, canonical form. Absent when not applicable; MASKED
    /// (absent) for fields marked secret. 
    #[prost(message, optional, tag="4")]
    pub actual: ::core::option::Option<Value>,
    /// Name of the structured constraint that failed ("gte", "pattern",
    /// "min_items", ...). Empty for CEL-rule and schema-level failures. 
    #[prost(string, tag="5")]
    pub constraint: ::prost::alloc::string::String,
    /// For CEL failures: the source expression that was violated or errored. 
    #[prost(string, tag="6")]
    pub expr: ::prost::alloc::string::String,
    /// Id of the authored rule that failed, if it declared one. 
    #[prost(string, optional, tag="7")]
    pub rule_id: ::core::option::Option<::prost::alloc::string::String>,
    /// Severity; defaults to ERROR. WARNING errors do not block submit. 
    #[prost(enumeration="schema::field::Severity", tag="8")]
    pub severity: i32,
    /// Human-readable message rendered from the spec's shared template set.
    /// Informative only — NOT part of the conformance contract. 
    #[prost(string, tag="9")]
    pub message: ::prost::alloc::string::String,
}
///
/// ValidationResult is the complete outcome of validating a form.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ValidationResult {
    /// All failures, in the spec's deterministic order. Empty means valid. 
    #[prost(message, repeated, tag="1")]
    pub errors: ::prost::alloc::vec::Vec<ValidationError>,
}
///
/// ErrorCode is the stable, machine-readable reason a validation failed. The
/// code (plus path and the typed fields on ValidationError) IS the
/// cross-implementation contract; human-readable text is rendered from a
/// shared, spec-owned template set and is not part of the contract.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ErrorCode {
    Unspecified = 0,
    /// Value/type shape. 
    TypeMismatch = 1,
    RequiredMissing = 2,
    NotNullable = 3,
    UnknownField = 4,
    ImmutableModified = 5,
    /// Scalar constraints. 
    ConstMismatch = 10,
    GtViolated = 11,
    GteViolated = 12,
    LtViolated = 13,
    LteViolated = 14,
    NotInAllowedSet = 15,
    InForbiddenSet = 16,
    MultipleOfViolated = 17,
    /// String constraints. 
    LenMismatch = 20,
    MinLenViolated = 21,
    MaxLenViolated = 22,
    PatternMismatch = 23,
    FormatMismatch = 24,
    /// String/bytes affix constraints. 
    PrefixMismatch = 25,
    SuffixMismatch = 26,
    /// The schema names a format this implementation does not support. Failing
    /// loudly is mandatory: a format may never be silently skipped. 
    UnsupportedFormat = 27,
    /// Choice constraints. 
    ChoiceNotAllowed = 30,
    /// List constraints. 
    MinItemsViolated = 40,
    MaxItemsViolated = 41,
    NotUnique = 42,
    ListCountMismatch = 43,
    /// Map constraints. 
    MinEntriesViolated = 50,
    MaxEntriesViolated = 51,
    /// Form-level constraints. 
    MinPropertiesViolated = 60,
    MaxPropertiesViolated = 61,
    /// Composition. 
    DiscriminatorMissing = 70,
    UnknownVariant = 71,
    UnknownRef = 72,
    /// CEL layer. 
    RuleViolated = 80,
    ExprError = 81,
    /// Schema descriptor itself is malformed (bad identity, no kind chosen,
    /// computed-field cycle, invalid CEL/Mustache/pattern source, ...). 
    InvalidSchema = 90,
}
impl ErrorCode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "ERROR_CODE_UNSPECIFIED",
            Self::TypeMismatch => "ERROR_CODE_TYPE_MISMATCH",
            Self::RequiredMissing => "ERROR_CODE_REQUIRED_MISSING",
            Self::NotNullable => "ERROR_CODE_NOT_NULLABLE",
            Self::UnknownField => "ERROR_CODE_UNKNOWN_FIELD",
            Self::ImmutableModified => "ERROR_CODE_IMMUTABLE_MODIFIED",
            Self::ConstMismatch => "ERROR_CODE_CONST_MISMATCH",
            Self::GtViolated => "ERROR_CODE_GT_VIOLATED",
            Self::GteViolated => "ERROR_CODE_GTE_VIOLATED",
            Self::LtViolated => "ERROR_CODE_LT_VIOLATED",
            Self::LteViolated => "ERROR_CODE_LTE_VIOLATED",
            Self::NotInAllowedSet => "ERROR_CODE_NOT_IN_ALLOWED_SET",
            Self::InForbiddenSet => "ERROR_CODE_IN_FORBIDDEN_SET",
            Self::MultipleOfViolated => "ERROR_CODE_MULTIPLE_OF_VIOLATED",
            Self::LenMismatch => "ERROR_CODE_LEN_MISMATCH",
            Self::MinLenViolated => "ERROR_CODE_MIN_LEN_VIOLATED",
            Self::MaxLenViolated => "ERROR_CODE_MAX_LEN_VIOLATED",
            Self::PatternMismatch => "ERROR_CODE_PATTERN_MISMATCH",
            Self::FormatMismatch => "ERROR_CODE_FORMAT_MISMATCH",
            Self::PrefixMismatch => "ERROR_CODE_PREFIX_MISMATCH",
            Self::SuffixMismatch => "ERROR_CODE_SUFFIX_MISMATCH",
            Self::UnsupportedFormat => "ERROR_CODE_UNSUPPORTED_FORMAT",
            Self::ChoiceNotAllowed => "ERROR_CODE_CHOICE_NOT_ALLOWED",
            Self::MinItemsViolated => "ERROR_CODE_MIN_ITEMS_VIOLATED",
            Self::MaxItemsViolated => "ERROR_CODE_MAX_ITEMS_VIOLATED",
            Self::NotUnique => "ERROR_CODE_NOT_UNIQUE",
            Self::ListCountMismatch => "ERROR_CODE_LIST_COUNT_MISMATCH",
            Self::MinEntriesViolated => "ERROR_CODE_MIN_ENTRIES_VIOLATED",
            Self::MaxEntriesViolated => "ERROR_CODE_MAX_ENTRIES_VIOLATED",
            Self::MinPropertiesViolated => "ERROR_CODE_MIN_PROPERTIES_VIOLATED",
            Self::MaxPropertiesViolated => "ERROR_CODE_MAX_PROPERTIES_VIOLATED",
            Self::DiscriminatorMissing => "ERROR_CODE_DISCRIMINATOR_MISSING",
            Self::UnknownVariant => "ERROR_CODE_UNKNOWN_VARIANT",
            Self::UnknownRef => "ERROR_CODE_UNKNOWN_REF",
            Self::RuleViolated => "ERROR_CODE_RULE_VIOLATED",
            Self::ExprError => "ERROR_CODE_EXPR_ERROR",
            Self::InvalidSchema => "ERROR_CODE_INVALID_SCHEMA",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ERROR_CODE_UNSPECIFIED" => Some(Self::Unspecified),
            "ERROR_CODE_TYPE_MISMATCH" => Some(Self::TypeMismatch),
            "ERROR_CODE_REQUIRED_MISSING" => Some(Self::RequiredMissing),
            "ERROR_CODE_NOT_NULLABLE" => Some(Self::NotNullable),
            "ERROR_CODE_UNKNOWN_FIELD" => Some(Self::UnknownField),
            "ERROR_CODE_IMMUTABLE_MODIFIED" => Some(Self::ImmutableModified),
            "ERROR_CODE_CONST_MISMATCH" => Some(Self::ConstMismatch),
            "ERROR_CODE_GT_VIOLATED" => Some(Self::GtViolated),
            "ERROR_CODE_GTE_VIOLATED" => Some(Self::GteViolated),
            "ERROR_CODE_LT_VIOLATED" => Some(Self::LtViolated),
            "ERROR_CODE_LTE_VIOLATED" => Some(Self::LteViolated),
            "ERROR_CODE_NOT_IN_ALLOWED_SET" => Some(Self::NotInAllowedSet),
            "ERROR_CODE_IN_FORBIDDEN_SET" => Some(Self::InForbiddenSet),
            "ERROR_CODE_MULTIPLE_OF_VIOLATED" => Some(Self::MultipleOfViolated),
            "ERROR_CODE_LEN_MISMATCH" => Some(Self::LenMismatch),
            "ERROR_CODE_MIN_LEN_VIOLATED" => Some(Self::MinLenViolated),
            "ERROR_CODE_MAX_LEN_VIOLATED" => Some(Self::MaxLenViolated),
            "ERROR_CODE_PATTERN_MISMATCH" => Some(Self::PatternMismatch),
            "ERROR_CODE_FORMAT_MISMATCH" => Some(Self::FormatMismatch),
            "ERROR_CODE_PREFIX_MISMATCH" => Some(Self::PrefixMismatch),
            "ERROR_CODE_SUFFIX_MISMATCH" => Some(Self::SuffixMismatch),
            "ERROR_CODE_UNSUPPORTED_FORMAT" => Some(Self::UnsupportedFormat),
            "ERROR_CODE_CHOICE_NOT_ALLOWED" => Some(Self::ChoiceNotAllowed),
            "ERROR_CODE_MIN_ITEMS_VIOLATED" => Some(Self::MinItemsViolated),
            "ERROR_CODE_MAX_ITEMS_VIOLATED" => Some(Self::MaxItemsViolated),
            "ERROR_CODE_NOT_UNIQUE" => Some(Self::NotUnique),
            "ERROR_CODE_LIST_COUNT_MISMATCH" => Some(Self::ListCountMismatch),
            "ERROR_CODE_MIN_ENTRIES_VIOLATED" => Some(Self::MinEntriesViolated),
            "ERROR_CODE_MAX_ENTRIES_VIOLATED" => Some(Self::MaxEntriesViolated),
            "ERROR_CODE_MIN_PROPERTIES_VIOLATED" => Some(Self::MinPropertiesViolated),
            "ERROR_CODE_MAX_PROPERTIES_VIOLATED" => Some(Self::MaxPropertiesViolated),
            "ERROR_CODE_DISCRIMINATOR_MISSING" => Some(Self::DiscriminatorMissing),
            "ERROR_CODE_UNKNOWN_VARIANT" => Some(Self::UnknownVariant),
            "ERROR_CODE_UNKNOWN_REF" => Some(Self::UnknownRef),
            "ERROR_CODE_RULE_VIOLATED" => Some(Self::RuleViolated),
            "ERROR_CODE_EXPR_ERROR" => Some(Self::ExprError),
            "ERROR_CODE_INVALID_SCHEMA" => Some(Self::InvalidSchema),
            _ => None,
        }
    }
}
///
/// SchemaRef selects a schema: either inline, or by identity (resolved from a
/// registry).
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SchemaRef {
    #[prost(oneof="schema_ref::Source", tags="1, 2")]
    pub source: ::core::option::Option<schema_ref::Source>,
}
/// Nested message and enum types in `SchemaRef`.
pub mod schema_ref {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Source {
        /// Resolve a registered schema by identity. 
        #[prost(message, tag="1")]
        Id(super::SchemaIdentity),
        /// Use this schema directly, without registering it. 
        #[prost(message, tag="2")]
        Schema(super::Schema),
    }
}
///
/// Filled is a runtime form: a reference to the schema plus the values entered
/// for it. The schema says what is allowed/derived; the values are what to
/// check/resolve. It is mutable input (the thing being edited/validated).
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Filled {
    /// Schema this form is filled against (by-id or inline). 
    #[prost(message, optional, tag="1")]
    pub schema: ::core::option::Option<SchemaRef>,
    /// Form values the expressions read and the validator checks. 
    #[prost(message, optional, tag="2")]
    pub values: ::core::option::Option<StructValue>,
}
///
/// Baked is a sealed result: the final values together with the schema they
/// were validated and resolved against. It is a self-contained, immutable
/// snapshot — "these exact values for this exact schema, not to be changed".
/// Unlike Filled (which only references a schema and is mutable), Baked embeds
/// the full schema and the frozen values, so it is portable and verifiable on
/// its own. Whether a Baked still matches a given schema is checked by deep
/// message equality of the embedded schema.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Baked {
    /// The schema these values were baked against (embedded, self-contained). 
    #[prost(message, optional, tag="1")]
    pub schema: ::core::option::Option<Schema>,
    /// The final, resolved values — frozen. 
    #[prost(message, optional, tag="2")]
    pub values: ::core::option::Option<StructValue>,
}
// @@protoc_insertion_point(module)
